### ISSUE TITLE
[bug] conflict between config and version variables

### ISSUE THREAD

**Issue by pioneer19** [build2/build2#101]
Can't use `$libhello.version.snapshot_id$` with `$config.libhello.fancy$` in `.hpp` file.
#### how to reproduce
1. I created simple `libhello` package, added config there (https://github.com/pioneer19/build2_config_error_example). Build work (`master` branch).

2. Then I added line
```
#define LIBHELLO_SNAPSHOT_ID   "$libhello.version.snapshot_id$"
```
to `libhello/config.hpp.in`. 
`b -v libhello/hxx{config}` will failure with
```libhello/config.hpp.in:6: error: undefined variable 'libhello.version.snapshot_id'```
(branch: `step1`)

3. Ok, I added `$src_root/manifest` dependency to `libhello/buildfile`
```
hxx{config}: in{config} $src_root/manifest
```
Now `b -v libhello/hxx{config}` will produce error
```
libhello/config.hpp.in:3: error: unknown dependency 'config'
  info: while updating libhello/hxx{config.hpp}
```
(branch: `step2`)

**Comment by boris-kolpackov** [comment]
Substitutions that are performed by the `version` module have special semantics, they are not the same as for the plain `in` module (see the `version` module documentation for details). The way to fix your example is to use the `in` module for `hxx{config}` (i.e., remove dependency on `manifest`) and then use normal variable substitution (`$version.snapshot_id$`).
