### ISSUE TITLE
How to install the toolchain for multiple compilers?

### ISSUE THREAD

**Issue by aminya** [build2/build2#104]
How can I install the toolchain for multiple compilers? I could not find any documentation, and the scripts seem to overwrite the previous toolchain.

**Comment by boris-kolpackov** [comment]
I am assuming this is addressed and closing the issue. If not, feel free to reopen with additional information.

**Comment by aminya** [comment]
Sorry, I don't use build2 anymore due to the lack of binaries (see [this](https://github.com/build2/build2-toolchain/pull/3)). 

I am not sure if this is fixed or not, but I think you know that better.
