### ISSUE TITLE
How to specify multiple extensions for C++ files?

### ISSUE THREAD

**Issue by alexchandel** [build2/build2#112]
The documentation states

> If you prefer the .cpp file extension and your source file is called hello.cpp, then the only line in our buildfile that needs changing is the extension variable assignment:
> ` cxx{*}: extension = cpp`

How can one specify *both* extensions, `cxx` and `cpp`, for legacy projects that use both and cannot be changed?

**Comment by boris-kolpackov** [comment]
If you are using multiple extensions, then you will have to specify one of them explicitly, for example, `cxx{foo.cpp}`.

BTW, in the future please use either the mailing list or the slack channel instead of creating issues to ask questions. See: https://build2.org/community.xhtml#help

**Comment by alexchandel** [comment]
How would this work in a rule?  Like `exe{hello}: {hxx ixx txx cxx}{**} {cxx}{**.cpp}`?

**Comment by boris-kolpackov** [comment]
Yes, that should work.
