### ISSUE TITLE
Duplication of poptions caused by multiple dependency paths to the same library

### ISSUE THREAD

**Issue by kamrann** [build2/build2#114]
### Context
Consider a simple project with two libraries and an executable.
```
# Root dependency library buildfile

lib{libA}: include/{hxx}{**}

lib{libA}:
{
  cxx.export.poptions += "-I$src_base"
}
```
```
# Intermediate library buildfile

intf_libs = # Interface dependencies.

import intf_libs += lib{libA}

lib{libB}: $intf_libs

lib{libB}:
{
  cxx.export.poptions += "-I$src_base"
  cxx.export.libs = $intf_libs
}
```
```
# Consuming executable buildfile

impl_libs = # Implementation dependencies.

import impl_libs += lib{libA} lib{libB}

exe{example}: {cxx}{example} $impl_libs
```

### Observed
The output from `b --verbose=4` shows the following (simplified) commandline. Note that the include path exported by `libA` is duplicated due to the combination of direct and transitive dependency.
`clang++ -IX:/.../libA -IX:/.../libB -IX:/.../libA`

### Expected
Ideally, redundant duplicated options should be removed to simplify the command lines. 
With a number of interdependent libraries, with some libraries occurring as both direct and indirect dependencies of many others, the command line will explode exponentially; even to the point of causing the compiler invocation to fail.

### Suggestion
There would appear to be two distinct levels at which this could be addressed, perhaps ideally both should be, but the first seems a priority:
- **Remove duplicate library dependencies**
I couldn't deduce much from a first look at the code so am not clear on the process of variable concatenation with library imports. However, conceptually it would seem to make sense to just accumulate the list of dependencies, which could be done in such a way as to avoid duplicates, and only expand and append their exported variables at the last step, when needed. This seems cleaner than trying to remove redundancies at the level of raw option strings.
- **Remove duplicate options**
While the above should fix the issue for include paths, other options are not library-specific and therefore can still end up duplicated. So it would be nice to have duplicate removal at the options string level too. This may be less trivial, however, since it's not clear that duplicate entries are necessarily always redundant?

[dup-poptions-repro.zip](https://github.com/build2/build2/files/5541067/dup-poptions-repro.zip)

**Comment by boris-kolpackov** [comment]
Yes, general de-duplication of options can get tricky. A few immediate examples that come to mind:

```
-DFOO -UFOO -DFOO
-lbar -lfoo -lbaz -lfoo
```

In the second example, if `foo` is a static library, then we cannot generally remove the second occurrence of `-lfoo` since `baz` may depend on additional (to `bar`) symbols from `foo`.

In case of libraries specifically, we have `poptions` for compilation and `libs` (which may also include any associated `loptions`) for linking.

In case of linking, I don't think we can suppress any duplicate libraries being linked due to the static library case described above. We could suppress shared libraries but I am not sure the resulting asymmetry is worth it ("my projects links fine when using shared libraries but not static"). We could probably safely suppress duplicate `-L`/`/LIBPATH`.

In case of compilation, while a library can conspire to undefine other library's macro, we can probably ignore this as a pathological case and skip all of the subsequent options. We could also tighten this a bit and skip subsequent options only if they are all `-I` and `-D`.

Thoughts?

**Comment by kamrann** [comment]
Okay, so yeah I agree, looks like removal of duplicates at the command-line level is tough and also perhaps just not really worth it. To be honest, I think realistically the only case where this is potentially a problem in practice is going to be `-I`. Taking `-D` as an example, I think most compilers report warnings for duplications there anyway so seems best to just leave as is.

The static lib case is interesting, I wasn't aware of how that worked until just now reading up on it.
I want to step back from the command-line level for a moment though. Consider the case given in the attachment above. I'm showing explicit, direct dependencies only here:
```
libA [no dependencies]
libB -> libA
exe -> libA, libB
```

Now I don't think I could be sure from looking at the codebase so I'm just going to take a guess at what's happening based on what I've seen. Let me know if I'm off.
It seems that exported options are not explicitly appended to the corresponding option of dependent targets at each level; rather each target just stores its own values (internal and export), and they're amalgamated by the rule as needed, at the end? This definitely makes the most sense to me, and as far as I can see is how it works.

So then the compilation rule, presumably, is recursively expanding the above dependencies when compiling a source file of `exe`, in this case into `libA`, `libA`, `libB` (or maybe `libA`, `libB`, `libA`; but I don't think it matters for the point I want to make), appending to the command line arguments as it goes?

Maybe there's more to it, but assuming I'm not too far off the mark then it seems to me there should be no need to do that 'target properties -> command line append' step more than once for any prerequisite. If you think of it as a directed graph with (non-duplicated) prerequisite library targets as nodes, then isn't a dependency (topological) sort on the nodes followed by appending arguments from each in that order sufficient?
From what I've read, I believe this would work for `-l` too, since it sounds like the important thing with ld (as far as not missing symbols) is to ensure dependents come first, dependencies last. 

As an example, topological sort in the above case for prerequisites of exe has only one result: `libA`, `libB`.
I believe if you then append `poptions` and `coptions` (perhaps `loptions` too with the exception of `-l`) in that order, and `-l` in the reverse order, you should get the correct results without the duplication that arises from recursive evaluation of all paths.

Now, I've never written a build tool before, so perhaps I'm missing some things? And of course this becomes somewhat more complex if you intend to support cyclic dependencies between libraries...

**Comment by boris-kolpackov** [comment]
> It seems that exported options are not explicitly appended to the corresponding option of dependent targets at each level; rather each target just stores its own values (internal and export), and they're amalgamated by the rule as needed, at the end?

Correct.

> So then the compilation rule, presumably, is recursively expanding the above dependencies when compiling a source file of `exe`, [...], appending to the command line arguments as it goes?

Correct.

> If you think of it as a directed graph with (non-duplicated) prerequisite library targets as nodes, then isn't a dependency (topological) sort on the nodes followed by appending arguments from each in that order sufficient? From what I've read, I believe this would work for `-l` too, since it sounds like the important thing with ld (as far as not missing symbols) is to ensure dependents come first, dependencies last.

Yes, that's a good point regarding linking. It won't be always 100% equivalent (due to `-L`/`/LIBPATH` search order) but one can argue any setup that depends on this is just asking for trouble.

> Now, I've never written a build tool before, so perhaps I'm missing some things? And of course this becomes somewhat more complex if you intend to support cyclic dependencies between libraries...

I don't think we will be supporting cyclic dependencies between libraries any time soon. So I think overall this is a good plan. The tricky part is how to implement it efficiently (ideally without any extra dynamic memory allocation, at least for the common cases) and without too much additional complexity.

I think the compilation part is relatively straightforward: we can add the `poptions` on the first encounter and remember (for example, in a `small_vector`) that we've already processed this library (there is a complication in that the callback is called several times for the same pass over a library, but we can handle that).

For the linking part we would need to do it in the reverse order, that is, add `loptions`/`libs` on the last encounter, not the first. Of course, we don't know whether it is the last encounter until we've seen all of them. So that would require first collecting all the libraries and then having another pass over them, which would be unfortunate. An alternative would be to remember the range of options added for every encountered library and then "hoist" these options to the back on every subsequent encounter of the same library.

**Comment by kamrann** [comment]
Yeah I'd assume command line equivalency is not something to really strive for, even if you could define it, since it would necessitate burdening the user with thinking of mappings between buildfile and compiler command lines. For myself, I suppose I just want a build tool to hide as much as possible so long as I can specify the important things (in this case, the dependency structure) and have it do something reasonable.

> So that would require first collecting all the libraries and then having another pass over them, which would be unfortunate. 

Okay so this is what I don't understand, or there's something I'm still missing. Is there something done within `process_libraries` that actually _needs_ to be done for every repeat occurrence of a library in the dependency graph, rather than merely once for each dependency? Because if not, the prepass approach would seem both cleaner and also signficantly more performant. If we're building `D` which depends on `B` and `C`, both of which depend on `A`, do we care that there are two distinct paths to `A`? It's not obvious to me why we would. If you recurse in the prepass just to find all dependencies so you can sort them, then you don't need to recurse when doing all the work, giving you a huge time save as soon as you have any non-trivial dependency graph. 

To add, I did note the `Remove this library from the chain` comment at the end and am unsure if that implies the recurse isn't quite what I think it is? But from the results I saw on my project, it seems to be.

**Comment by boris-kolpackov** [comment]
> Okay so this is what I don't understand, or there's something I'm still missing. Is there something done within `process_libraries` that actually needs to be done for every repeat occurrence of a library in the dependency graph, rather than merely once for each dependency?

No. But what `process_libraries()` does is traverse the libraries graph and call a number of callback to perform appropriate actions in appropriate order depending on many factors (what is being linked, what is being traversed, etc).

As a result, if we were to do a prepass, then we have two choices: (1) just collect the libraries and recreate this "appropriateness" on the postpass or (2) save the results of appropriately called callback (essentially a vector of vector of strings) to be copied over on the postpass. Option (1) will be quite hairy to implement while (2) I feel will have pretty poor performance due to the extra memory allocations.

 > To add, I did note the Remove this library from the chain comment at the end and am unsure if that implies the recurse isn't quite what I think it is?

Yes, that's another complication that will be hard to recreate with option (1): we keep track (on the stack) of the chain of libraries being traversed all the way to the top (which is needed to decide what to link when it comes to utility libraries).

In any case, I went ahead and implemented the hoisting approach and it came out not too hairy (I even got to use `std::rotate()` which is a clear sign we are on the right track, right? ;-)). Here are some before/after command lines on one of our projects.

Compilation:

```
BEFORE:
g++ -I.../builds/gcc7-asan/brep
-I.../brep -I/usr/include/apache2
-I.../builds/gcc7-asan/libodb-2.5.0-b.20.20200721131340.06b9bef1edf4
-I.../builds/gcc7-asan/libodb-2.5.0-b.20.20200721131340.06b9bef1edf4
-DLIBODB_BUILD2 -DLIBODB_SHARED
-I.../builds/gcc7-asan/libodb-pgsql-2.5.0-b.20.20200721131340.5d04da922fbf
-I.../builds/gcc7-asan/libodb-pgsql-2.5.0-b.20.20200721131340.5d04da922fbf
-DLIBODB_PGSQL_BUILD2 -DLIBODB_PGSQL_SHARED
-I.../builds/gcc7-asan/libodb-2.5.0-b.20.20200721131340.06b9bef1edf4
-I.../builds/gcc7-asan/libodb-2.5.0-b.20.20200721131340.06b9bef1edf4
-DLIBODB_BUILD2 -DLIBODB_SHARED
-I.../builds/gcc7-asan/libbutl
-I.../libbutl -DLIBBUTL_SHARED
-I.../builds/gcc7-asan/libbpkg
-I.../libbpkg -DLIBBPKG_SHARED
-I.../builds/gcc7-asan/libbutl
-I.../libbutl -DLIBBUTL_SHARED
-I.../builds/gcc7-asan/libbbot
-I.../libbbot -DLIBBBOT_SHARED
-I.../builds/gcc7-asan/libbutl
-I.../libbutl -DLIBBUTL_SHARED
-I.../builds/gcc7-asan/libbpkg
-I.../libbpkg -DLIBBPKG_SHARED
-I.../builds/gcc7-asan/libbutl
-I.../libbutl -DLIBBUTL_SHARED
-Wall -Wextra -Werror -g
-fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer
-Wno-unknown-pragmas -fPIC -std=c++1z -o
../../builds/gcc7-asan/brep/libbrep/common.so.o -c -x c++
.../brep/libbrep/common.cxx

AFTER:
g++ -I.../builds/gcc7-asan/brep
-I.../brep -I/usr/include/apache2
-I.../builds/gcc7-asan/libodb-2.5.0-b.20.20200721131340.06b9bef1edf4
-I.../builds/gcc7-asan/libodb-2.5.0-b.20.20200721131340.06b9bef1edf4
-DLIBODB_BUILD2 -DLIBODB_SHARED
-I.../builds/gcc7-asan/libodb-pgsql-2.5.0-b.20.20200721131340.5d04da922fbf
-I.../builds/gcc7-asan/libodb-pgsql-2.5.0-b.20.20200721131340.5d04da922fbf
-DLIBODB_PGSQL_BUILD2 -DLIBODB_PGSQL_SHARED
-I.../builds/gcc7-asan/libbutl
-I.../libbutl -DLIBBUTL_SHARED
-I.../builds/gcc7-asan/libbpkg
-I.../libbpkg -DLIBBPKG_SHARED
-I.../builds/gcc7-asan/libbbot
-I.../libbbot -DLIBBBOT_SHARED
-Wall -Wextra -Werror -g
-fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer
-Wno-unknown-pragmas -fPIC -std=c++1z -o
../../builds/gcc7-asan/brep/libbrep/common.so.o -c -x c++
.../brep/libbrep/common.cxx
```

Linking:

```
BEFORE:
g++ -Wall -Wextra -Werror -g -fsanitize=address -fsanitize=undefined
-fno-omit-frame-pointer -Wno-unknown-pragmas -fuse-ld=gold
-Wl,--threads,--thread-count,4 -Wl,-soname,libbrep-0.14.0-a.0.069e21c82557.so
-std=c++1z -L /usr/local/lib -shared -o
../../builds/gcc7-asan/brep/libbrep/libbrep-0.14.0-a.0.069e21c82557.so
-Wl,-rpath,.../builds/gcc7-asan/libodb-2.5.0-b.20.20200721131340.06b9bef1edf4/odb
-Wl,-rpath,.../builds/gcc7-asan/libodb-pgsql-2.5.0-b.20.20200721131340.5d04da922fbf/odb/pgsql
-Wl,-rpath,.../builds/gcc7-asan/libodb-2.5.0-b.20.20200721131340.06b9bef1edf4/odb
-Wl,-rpath,.../builds/gcc7-asan/libbutl/libbutl
-Wl,-rpath,.../builds/gcc7-asan/libbpkg/libbpkg
-Wl,-rpath,.../builds/gcc7-asan/libbutl/libbutl
-Wl,-rpath,.../builds/gcc7-asan/libbbot/libbbot
-Wl,-rpath,.../builds/gcc7-asan/libbutl/libbutl
-Wl,-rpath,.../builds/gcc7-asan/libbpkg/libbpkg
-Wl,-rpath,.../builds/gcc7-asan/libbutl/libbutl
../../builds/gcc7-asan/brep/libbrep/build.so.o
../../builds/gcc7-asan/brep/libbrep/package.so.o
../../builds/gcc7-asan/brep/libbrep/common.so.o
../../builds/gcc7-asan/brep/libbrep/database-lock.so.o
../../builds/gcc7-asan/brep/libbrep/package-traits.so.o
../../builds/gcc7-asan/brep/libbrep/common-odb.so.o
../../builds/gcc7-asan/brep/libbrep/package-odb.so.o
../../builds/gcc7-asan/brep/libbrep/build-odb.so.o
../../builds/gcc7-asan/brep/libbrep/build-package-odb.so.o
../../builds/gcc7-asan/libodb-2.5.0-b.20.20200721131340.06b9bef1edf4/odb/libodb-2.5.0-b.20.06b9bef1edf4.so
../../builds/gcc7-asan/libodb-pgsql-2.5.0-b.20.20200721131340.5d04da922fbf/odb/pgsql/libodb-pgsql-2.5.0-b.20.5d04da922fbf.so
../../builds/gcc7-asan/libodb-2.5.0-b.20.20200721131340.06b9bef1edf4/odb/libodb-2.5.0-b.20.06b9bef1edf4.so
../../builds/gcc7-asan/libbutl/libbutl/libbutl-0.14.0-a.0.ae43c5780651.so
../../builds/gcc7-asan/libbpkg/libbpkg/libbpkg-0.14.0-a.0.09702fc27c67.so
../../builds/gcc7-asan/libbutl/libbutl/libbutl-0.14.0-a.0.ae43c5780651.so
../../builds/gcc7-asan/libbbot/libbbot/libbbot-0.14.0-a.0.a44db60af81d.so
../../builds/gcc7-asan/libbutl/libbutl/libbutl-0.14.0-a.0.ae43c5780651.so
../../builds/gcc7-asan/libbpkg/libbpkg/libbpkg-0.14.0-a.0.09702fc27c67.so
../../builds/gcc7-asan/libbutl/libbutl/libbutl-0.14.0-a.0.ae43c5780651.so

AFTER:
g++ -Wall -Wextra -Werror -g -fsanitize=address -fsanitize=undefined
-fno-omit-frame-pointer -Wno-unknown-pragmas -fuse-ld=gold
-Wl,--threads,--thread-count,4 -Wl,-soname,libbrep-0.14.0-a.0.069e21c82557.so
-std=c++1z -L /usr/local/lib -shared -o
../../builds/gcc7-asan/brep/libbrep/libbrep-0.14.0-a.0.069e21c82557.so
-Wl,-rpath,.../builds/gcc7-asan/libodb-2.5.0-b.20.20200721131340.06b9bef1edf4/odb
-Wl,-rpath,.../builds/gcc7-asan/libodb-pgsql-2.5.0-b.20.20200721131340.5d04da922fbf/odb/pgsql
-Wl,-rpath,.../builds/gcc7-asan/libbutl/libbutl
-Wl,-rpath,.../builds/gcc7-asan/libbpkg/libbpkg
-Wl,-rpath,.../builds/gcc7-asan/libbbot/libbbot
../../builds/gcc7-asan/brep/libbrep/build.so.o
../../builds/gcc7-asan/brep/libbrep/package.so.o
../../builds/gcc7-asan/brep/libbrep/common.so.o
../../builds/gcc7-asan/brep/libbrep/database-lock.so.o
../../builds/gcc7-asan/brep/libbrep/package-traits.so.o
../../builds/gcc7-asan/brep/libbrep/common-odb.so.o
../../builds/gcc7-asan/brep/libbrep/package-odb.so.o
../../builds/gcc7-asan/brep/libbrep/build-odb.so.o
../../builds/gcc7-asan/brep/libbrep/build-package-odb.so.o
../../builds/gcc7-asan/libodb-pgsql-2.5.0-b.20.20200721131340.5d04da922fbf/odb/pgsql/libodb-pgsql-2.5.0-b.20.5d04da922fbf.so
../../builds/gcc7-asan/libodb-2.5.0-b.20.20200721131340.06b9bef1edf4/odb/libodb-2.5.0-b.20.06b9bef1edf4.so
../../builds/gcc7-asan/libbbot/libbbot/libbbot-0.14.0-a.0.a44db60af81d.so
../../builds/gcc7-asan/libbpkg/libbpkg/libbpkg-0.14.0-a.0.09702fc27c67.so
../../builds/gcc7-asan/libbutl/libbutl/libbutl-0.14.0-a.0.ae43c5780651.so
```

Static linking:

```
BEFORE:
g++ -Wall -Wextra -Werror -g -fsanitize=address -fsanitize=undefined
-fno-omit-frame-pointer -Wno-unknown-pragmas -fuse-ld=gold
-Wl,--threads,--thread-count,4 -std=c++1z -L /usr/local/lib -o brep-load
load.o types-parsers.o load-options.o
../libbrep/libbrep.a
../../libodb-2.5.0-b.20.20200721131340.06b9bef1edf4/odb/libodb.a
../../libodb-pgsql-2.5.0-b.20.20200721131340.5d04da922fbf/odb/pgsql/libodb-pgsql.a
/usr/lib/x86_64-linux-gnu/libpq.a
/usr/lib/x86_64-linux-gnu/libssl.a -ldl
/usr/lib/x86_64-linux-gnu/libcrypto.a -ldl -ldl
/usr/lib/x86_64-linux-gnu/libcrypto.a -ldl
/usr/lib/x86_64-linux-gnu/mit-krb5/libgssapi_krb5.so -lcrypt
/usr/lib/x86_64-linux-gnu/libldap_r.a
../../libodb-2.5.0-b.20.20200721131340.06b9bef1edf4/odb/libodb.a
../../libbutl/libbutl/libbutl.a -ldl -lpthread
../../libbpkg/libbpkg/libbpkg.a
../../libbutl/libbutl/libbutl.a -ldl -lpthread
../../libbbot/libbbot/libbbot.a
../../libbutl/libbutl/libbutl.a -ldl -lpthread
../../libbpkg/libbpkg/libbpkg.a
../../libbutl/libbutl/libbutl.a -ldl -lpthread
../../libodb-2.5.0-b.20.20200721131340.06b9bef1edf4/odb/libodb.a
../../libodb-pgsql-2.5.0-b.20.20200721131340.5d04da922fbf/odb/pgsql/libodb-pgsql.a
/usr/lib/x86_64-linux-gnu/libpq.a
/usr/lib/x86_64-linux-gnu/libssl.a -ldl
/usr/lib/x86_64-linux-gnu/libcrypto.a -ldl -ldl
/usr/lib/x86_64-linux-gnu/libcrypto.a -ldl
/usr/lib/x86_64-linux-gnu/mit-krb5/libgssapi_krb5.so -lcrypt
/usr/lib/x86_64-linux-gnu/libldap_r.a
../../libodb-2.5.0-b.20.20200721131340.06b9bef1edf4/odb/libodb.a
../../libbutl/libbutl/libbutl.a -ldl -lpthread
../../libbpkg/libbpkg/libbpkg.a
../../libbutl/libbutl/libbutl.a -ldl -lpthread

AFTER:
g++ -Wall -Wextra -Werror -g -fsanitize=address -fsanitize=undefined
-fno-omit-frame-pointer -Wno-unknown-pragmas -fuse-ld=gold
-Wl,--threads,--thread-count,4 -std=c++1z -L /usr/local/lib -o brep-load
load.o types-parsers.o load-options.o
../libbrep/libbrep.a
-ldl -ldl -ldl -ldl
-lcrypt -ldl -lpthread -ldl -lpthread
../../libbbot/libbbot/libbbot.a -ldl -lpthread -ldl -lpthread
../../libodb-pgsql-2.5.0-b.20.20200721131340.5d04da922fbf/odb/pgsql/libodb-pgsql.a
/usr/lib/x86_64-linux-gnu/libpq.a
/usr/lib/x86_64-linux-gnu/libssl.a -ldl -ldl -ldl
/usr/lib/x86_64-linux-gnu/libcrypto.a -ldl
/usr/lib/x86_64-linux-gnu/mit-krb5/libgssapi_krb5.so -lcrypt
/usr/lib/x86_64-linux-gnu/libldap_r.a
../../libodb-2.5.0-b.20.20200721131340.06b9bef1edf4/odb/libodb.a -ldl -lpthread
../../libbpkg/libbpkg/libbpkg.a
../../libbutl/libbutl/libbutl.a -ldl -lpthread
```

I still want to see if I can get rid of those heinous `-ldl -ldl -ldl -ldl` using the same mechanism. Feels like it should be doable.

**Comment by kamrann** [comment]
Understood. And for sure whether or not the approach I had in mind is feasible depends on the details of those actions and factors. Realistically I'm not going to have sufficient understanding of all those details any time soon, but I think I can now at least summarize a bit more clearly. And anyway the results of your changes are looking much better already, so with a bit of luck the immediate issue will be addressed sufficiently without need for larger scale refactoring.

So, for future reference - I think the crux of why what I had in mind may not be so straightforward is this. I had been assuming that
```lib{foo}: lib{bar} lib{baz}```
and
```lib{foo}: lib{baz} lib{bar}```
were equivalent, but it seems they're not. I would ask, though, in theory could they be made equivalent without unduly limiting a user's control? And if so, I really think it would be worth striving for.

- It lets the user think in terms of dependencies rather than linker command line idiosyncrasies (note link.exe does not have the same restrictions as ld in regards to input ordering).
- It means you're dealing with a regular dependency graph, rather than a kind of graph hybrid with an additional notion of branch ordering; this simplifies things for you as the implementer, not least because you can now just dependency sort and process linearly (above mentioned other factors permitting).

Now, what came up in the Slack is interesting. It may be that if you remove that meaning of prerequisite declaration order, then that negates the ability to solve the case given. But I'd argue that it ideally shouldn't be supported anyway. Essentially it's inverting dependencies in a way that I don't think makes sense (exactly the same as with the mentioned header file issue I'd say, just a little less immediately offensive!). Technically, the `hooks.cpp` is a dependency of the library. Of course, you can't make it such whilst also allowing the user to specify it; but that's really because you're twisting the idea of what a library is. Better to force the user to conform (runtime approach), or perhaps solve it using object libraries, which would better reflect that the 'library' is not yet a complete thing.

Of course, all this very much depends on where you stand on the spectrum of 'supporting all real world use cases' vs 'it's a new build tool, things should be sane'. You can probably guess I favour the latter!

Sorry for the text wall, conciseness is not my strong point. If I can assist by testing changes on my project, just let me know.

**Comment by boris-kolpackov** [comment]
Ok, I've completed the implementation to also handle `-l`. Here is what the final result for the static link looks like:

```
g++-7 -Wall -Wextra -Werror -g -fsanitize=address -fsanitize=undefined
-fno-omit-frame-pointer -Wno-unknown-pragmas -fuse-ld=gold
-Wl,--threads,--thread-count,4 -std=c++1z -L /usr/local/lib -o brep-load
load.o types-parsers.o load-options.o
../libbrep/libbrep.a
../../libbbot/libbbot/libbbot.a
../../libodb-pgsql-2.5.0-b.20.20200721131340.5d04da922fbf/odb/pgsql/libodb-pgsql.a
/usr/lib/x86_64-linux-gnu/libpq.a
/usr/lib/x86_64-linux-gnu/libssl.a
/usr/lib/x86_64-linux-gnu/libcrypto.a
/usr/lib/x86_64-linux-gnu/mit-krb5/libgssapi_krb5.so
-lcrypt
/usr/lib/x86_64-linux-gnu/libldap_r.a
../../libodb-2.5.0-b.20.20200721131340.06b9bef1edf4/odb/libodb.a
../../libbpkg/libbpkg/libbpkg.a
../../libbutl/libbutl/libbutl.a
-ldl -lpthread
```

The changes are available in the latest [staged version](https://build2.org/community.xhtml#stage) of the toolchain. If you could give it a try and confirm it works for you, that would be great.

> I would ask, though, in theory could they be made equivalent without unduly limiting a user's control?

Not if you want to support static libraries (or are willing to always link them in the "whole archive" mode). On both POSIX and Windows the semantics is that only object files that satisfy symbols unresolved *up to this point* are picked.

> Of course, all this very much depends on where you stand on the spectrum of 'supporting all real world use cases' vs 'it's a new build tool, things should be sane'. You can probably guess I favour the latter!

Our goal is to hopefully make simple things sane and complex things possible. I also don't think not supporting most real-world use cases is an option for a general-purpose built system since then we won't be able to handle the fundamental building block of modern software, things like `openssl`, for example.

**Comment by kamrann** [comment]
> Not if you want to support static libraries (or are willing to always link them in the "whole archive" mode). On both POSIX and Windows the semantics is that only object files that satisfy symbols unresolved up to this point are picked.
> 
> Our goal is to hopefully make simple things sane and complex things possible. I also don't think not supporting most real-world use cases is an option for a general-purpose built system since then we won't be able to handle the fundamental building block of modern software, things like openssl, for example.

Yep fair enough. It must only be an issue in corner cases though, presumably? I've used CMake on various projects and have never once paid any attention to the order in which I specified static dependencies for a given target; hence my assumption that the implicit dependency graph alone was sufficient to derive a correct ordering for the invoked command line.

Will pull latest soon and report back. I'd had to get creative with my interface library imports to avoid the build failure, so if I re-enable them all as they should be, it should prove a good test. I've added a fair number more libraries than I had when it first failed.

**Comment by kamrann** [comment]
All seems good. To workaround the issue I'd commented out a lot of library dependencies in my buildfiles in cases where I knew they were being inherited transitively anyway. I did a build on the latest staged version, then went through the buildfiles reenabling all those dependencies and rebuilt again; the compiler command lines are essentially the same between the two, no duplication. Nice job!

**Comment by boris-kolpackov** [comment]
Great thanks for testing and helping to flesh out the details.

**Comment by boris-kolpackov** [comment]
I think we've done everything we can here so I am closing the issue (but feel free to reopen if anything pops up).
