### ISSUE TITLE
Paths in option-files should be relative to that file's location.

### ISSUE THREAD

**Issue by Klaim** [build2/build2#115]
When using `--options-files` , if in the file we also use `--options-file`, then the path is relative to the initial call, not to the location of the first option-file. It makes a bit hard to script because we need to make sure the path in the first option file is relative to the caller's path.

**Comment by boris-kolpackov** [comment]
This has been fixed in the latest staged version of the toolchain. If you could give it a try and confirm it works as expected, that would be great.

**Comment by Klaim** [comment]
I confirm it works in today's stage version.
