### ISSUE TITLE
buildfile function list?

### ISSUE THREAD

**Issue by alexchandel** [build2/build2#116]
Where are the builtin buildfile functions documented?  [Buildfile Language](https://build2.org/build2/doc/build2-build-system-manual.xhtml#intro-lang) mentions a few like `$regex.match` and `$path.leaf`, but I'm looking for ones like Makefile's `addprefix`.

If there is no list, can this be added to the documentation?

**Comment by alexchandel** [comment]
To add to this, a glossary of builddfile directives.  Many directives are haphazardly mentioned [in the build system manual](https://build2.org/build2/doc/build2-build-system-manual.xhtml), like `include`, `source`, `using`…  But the manual never details a complete descriptions of their effects (search "source directive" returns 0 results).

This makes it very difficult to adopt `build2`.  Please document these.

**Comment by boris-kolpackov** [comment]
Yes, we need to document these. I've started documenting the directives. For functions we plan to automatically extract their documentation from source code, just haven't gotten around to it. But all the documentation is already there so if you open one of `build2/libbuild2/functions-*.cxx`, you should be able to find all the information (some modules also define functions which would be in the `functions.cxx` file, for example `build2/libbuild2/install/functions.cxx`). Here is the current list of the relevant files:

```
functions-builtin.cxx
functions-filesystem.cxx
functions-name.cxx
functions-path.cxx
functions-process.cxx
functions-process-path.cxx
functions-project-name.cxx
functions-regex.cxx
functions-string.cxx
functions-target-triplet.cxx
```

**Comment by boris-kolpackov** [comment]
I think this is done: in the last couple of releases the build system manual includes the list of functions and their documentation (auto-extracted from the source files). See the "Functions" chapter: https://build2.org/build2/doc/build2-build-system-manual.xhtml
