### ISSUE TITLE
Broken repository state due to case-sensitive paths on Windows

### ISSUE THREAD

**Issue by kamrann** [build2/build2#117]
### Output
```
> bpkg fetch
fetching dir:D:\Coding\Kantan\kantan-build2
[various prerequisite fetches here]
fetching dir:D:\coding\kantan\build2-repro
fetching dir:D:\coding\kantan\kantan-build2
error: external package kantan/0.1.0 is available from two repositories
  info: repository dir+file:///D:/Coding/Kantan/kantan-build2
  info: repository dir+file:///D:/coding/kantan/kantan-build2
warning: repository state is now broken and will be cleaned up
  info: run 'bpkg rep-fetch' to update
```
```
> bpkg list
dir:D:\Coding\Kantan\kantan-build2 dir+file:///D:/Coding/Kantan/kantan-build2
dir:D:\coding\kantan\build2-repro dir+file:///D:/coding/kantan/build2-repro
dir:D:\coding\kantan\kantan-build2 dir+file:///D:/coding/kantan/kantan-build2
```

### Further info/questions
I'm on Windows 10, and using Powershell. It's not clear precisely what sequence of actions leads to this, though it has happened a number of times, mostly after adding a new external git prerequisite to my project's repositories.manifest and then trying to update. I'm also reasonably confident that at no point would I have directly typed the lower case version of the above paths in any command.

Two other minor things:
- Does _external_ package have some specific meaning in the above output? It seems a little strange to me since this is a package that lives inside the project repository.
- The diagnostic's suggestion to run the exact same command that just gave the error is a little confusing!

**Comment by boris-kolpackov** [comment]
Ok, this was a bit more involved than initially thought (always the story when it comes to Windows), but it should be fixed now. The changes are available in the latest [staged version](https://build2.org/community.xhtml#stage) of the toolchain. If you could give it a try and confirm it works for you, that would be great. Note that you will need to re-create all your build configurations -- if you continue using the old ones, then the different-case repository names will still sit in the database (unfortunately doing automatic migration is pretty difficult because they are primary keys).

**Comment by kamrann** [comment]
Okay I updated to the latest staged version yesterday.
I was getting the following in relation to the existing configurations,
```
Assertion failed: o.name == o.location.canonical_name (), file E:\build2-build\build2-toolchain-0.14-a.0\bpkg-0.14.0-a.0.20201123144830.d153e1530e87\bpkg\package-odb.cxx, line 3966
```

which I assume is probably expected. It made things a bit difficult to uninitialize the project but I got there eventually.

Since the original issue was happening sporadically, I can't directly verify that it's now fixed, however it is working fine so far in new configurations. If I hit any path/case related issues again, I'll report back here.

**Comment by boris-kolpackov** [comment]
I am assuming this is fixed and closing the issue (but feel free to reopen if anything new pops up).

**Comment by kamrann** [comment]
Running into a slightly different but related problem. Demonstrated pretty clearly from the following terminal (again Powershell) commands:
```
D:\Coding\Kantan\kantan-build2\packages\kbuild [main ≡ +2 ~15 -5 !]> bdep update -@clang
info: ..\..\..\k-b2-clang\dir{kbuild\} is up to date
D:\Coding\Kantan\kantan-build2\packages\kbuild [main ≡ +2 ~15 -5 !]> cd /coding/kantan/kantan-build2/packages/kbuild
D:\coding\kantan\kantan-build2\packages\kbuild [main ≡ +2 ~15 -5 !]> bdep update -@clang
error: repository 'git+file:///D:/coding/kantan/kantan-build2' does not exist in this configuration
```
As you can see, I'm getting errors from `bdep` commands when I cd into the same directory but specified with non-matching case.

**Comment by karen-arutyunov** [comment]
Thanks for the report! 

The fix is staged. It would be great if you could confirm it works for you.

**Comment by kamrann** [comment]
Sorry for long delay. Just upgraded to latest staged build and the issue does appear to be resolved. Thanks!
