### ISSUE TITLE
Support for libodb-boost?

### ISSUE THREAD

**Issue by yssource** [build2/build2#12]
build2 is going to support [libodb-boost](https://git.codesynthesis.com/odb/libodb-boost.git) , isn't it?

And,  [conan](https://conan.io/) goes well with boost. But, So far I have not found libodb-boost in https://www.cppget.org/

**Comment by yssource** [comment]
I don't know why there is no such a file "configure" in tag-2.4.0 https://git.codesynthesis.com/cgit/odb/libodb-boost/tree/?h=2.4.0

But, the configure file exist in [libodb-boost-2.4.0.tar.bz](https://www.codesynthesis.com/download/odb/2.4/libodb-boost-2.4.0.tar.bz2).

It's **NOT** easy to build2 it from git repository.

**Comment by boris-kolpackov** [comment]
Correct, `libodb-boost` is not yet packaged for `build2`. It is on our TODO list, however.

**Comment by yssource** [comment]
May be it is not the proper place to open such a issue about libodb-boost, but I don't know where is the libodb-boost on github.


- git clone https://git.codesynthesis.com/odb/libodb-boost.git
- cd libodb-boost && automake
- Error report.

``` bash
configure.ac:7: error: required directory ./config does not exist
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
configure.ac:16: error: required file 'config/config.guess' not found
configure.ac:16:   'automake --add-missing' can install 'config.guess'
configure.ac:16: error: required file 'config/config.sub' not found
configure.ac:16:   'automake --add-missing' can install 'config.sub'
automake: error: no 'Makefile.am' found for any configure output
automake: Did you forget AC_CONFIG_FILES([Makefile]) in configure.ac?
```

another way using `make`
- make

``` bash
Please select the optimization level you would like to use:

(1) -O1 [Tries to reduce code size and execution time, without
         performing any optimizations that take a great deal of
         compilation time.]
(2) -O2 [Performs nearly all supported optimizations that do not
         involve a space-speed tradeoff.]
(3) -O3 [Optimize even more.]
(4) -Os [Optimize for size.]

[2]: 
c++ /home/jimmy/workspace/git/libodb-boost/odb/boost/date-time/exceptions.cxx
make: *** No rule to make target '-lodb', needed by '/home/jimmy/workspace/git/libodb-boost/odb/boost/odb-boost.l'.  Stop.
```

**Comment by boris-kolpackov** [comment]
FYI, `libodb-bbost` (and `libodb-qt`) are now packaged: https://cppget.org/libodb-boost
