### ISSUE TITLE
Add `--recursive` to `bdep clean`

### ISSUE THREAD

**Issue by Klaim** [build2/build2#121]
Sometimes, I want projects and their dependencies to be completely cleaned (without changing the code). This can be because 
 - I want to force a clean build of the whole code, usually because some information depends on the time of the build (like build info constants embedded in the program);
 - I want to clear dependencies binaries for a time because they take a lot of space and I wont be using them for now;
 - I'm seeing an issue only in build from scratch (either a buildsystem or compiler or code issue) and try to reproduce it quickly;

By reflex, I tend to try `bdep clean -r` because `bdep test -r` and `bdep status -r` works and to me the `--recursive` argument makes sense to apply with `clean` for the precedent reasons.

And alternative is to do `bdep deinit && bdep init` but that's a bit overkill for what we want here, and it also will probably re-downloading dependencies (depends on the exact situation).

**Comment by boris-kolpackov** [comment]
This has been implemented in the latest staged version of the toolchain. Specifically, both `update` and `clean` now accept the `-r|--recursive` and `-i|--immediate` options. If you could give it a try and confirm it works as expected, that would be great.

**Comment by Klaim** [comment]
I can confirm this works as expected in today's stage version.
