### ISSUE TITLE
During Stage on Bootstrapping on Windows with MinGW produces178 skipped

### ISSUE THREAD

**Issue by Rdna123** [build2/build2#124]
I have changed no File name, and edit command prompt to match generated directories.

Command: 
`
build2-0.13.0\build2\b-boot install: build2-0.13.0/ bpkg-0.13.0/
`

Errors look similar to:
 `error: unable to execute install: no such file or directory
  info: while installing bpkg-0.13.0\manifest{manifest}
  info: while installing dir{bpkg-0.13.0\}`

File Structure:
![image](https://user-images.githubusercontent.com/54755407/101814722-63b13380-3ad3-11eb-9727-7021ddf54a63.png)

**Comment by Rdna123** [comment]
Install a different g++.exe  and it worked

**Comment by boris-kolpackov** [comment]
Ok, glad you've sorted yourself out. FYI, we provide a minimal MinGW distribution (`build2-mingw-*` package, essentially a slightly tweaked MSYS2 version) which is what we test and therefore guarantee to work. Custom MinGW distributions vary widely and things may or may not work with figuring out why they don't work left as an exercise to the user ;-)

**Comment by Rdna123** [comment]
I did a hard lead to the executable  instead of a command call for a for it, e.i. I did C:/build2/bin/g++.exe instead of g++.exe
