### ISSUE TITLE
Document how to configure flat source layouts.

### ISSUE THREAD

**Issue by alexchandel** [build2/build2#127]
Some legacy projects' setups cannot yet be moved to [source subdirectory layouts](https://build2.org/build2-toolchain/doc/build2-toolchain-intro.xhtml#proj-struct-src-dir), and must keep everything in their root folder (except build2's `build/`).  The documentation advises against this, but doesn't elaborate.  How can this be achieved?

[Using the tutorial's example of 1 exe and 1 lib package in the same overarching project](https://build2.org/build2-toolchain/doc/build2-toolchain-intro.xhtml#guide-dev-multi), I tried merging `libhello/libhello/*` into `libhello/`, deleted `libhello/tests/`, and I modified `libhello/build/export.build` to `export $out_root/$import.target` instead.  Building the library succeeds.  But building the executable now errors on the first line of `hello/hello/buildfile`,

```
import libs += libhello%lib{hello}

exe{hello}: {hxx ixx txx cxx}{**} $libs testscript

cxx.poptions =+ "-I$out_root" "-I$src_root"
```

with

```
error: unable to import target libhello%lib{hello}
  info: use config.import.libhello configuration variable to specify its project out_root
  info: while applying rule cxx.link to update hello/hello/exe{hello}
  info: while applying rule alias to update hello/dir{hello/}
  info: while applying rule alias to update dir{hello/}
  info: while applying rule alias to update dir{./}
info: failed to update dir{./}
```

What must be added to the dependent's buildfile when the dependency is a flat package?  Could a doc subsection be added explaining this?

**Comment by boris-kolpackov** [comment]
The `bdep-new` command has the [SOURCE LAYOUT](https://build2.org/bdep/doc/bdep-new.xhtml#src-layout) section which shows how to create various project structures, including the "flat" one you are after. Can you try that and see if you can make it work?

And if something still doesn't work, then access to the project repository that I can try to debug would be helpful.

**Comment by boris-kolpackov** [comment]
Ok, I assume this is no longer an issue.
