### ISSUE TITLE
build2-install-0.8.0.sh unable to find ar

### ISSUE THREAD

**Issue by hazelnusse** [build2/build2#13]
I'm running Gentoo and wanted to use clang++7.0 as the c++ compiler to bootstrap build2 so I did:
```
$ sh build2-install-0.8.0.sh --cxx /usr/lib/llvm/7/bin/clang++ ~/.local
...
+ build2/b-boot --version
build2 999.999.999
libbutl 999.999.999
host x86_64-pc-linux-gnu
Copyright (c) 2014-2018 Code Synthesis Ltd
This is free software released under the MIT license.
+ build2/b-boot config.cxx=/usr/lib/llvm/7/bin/clang++ config.bin.lib=static build2/exe{b}
error: unable to execute /usr/lib/llvm/7/bin/ar: no such file or directory
```
So it looks like the script is assuming that ar is installed in the same place as the cxx compiler and is called `ar`. In the clang dir it is called `llvm-ar` and my /usr/bin/ar is a symlink to binutils ar. I'm not sure whether the llvm-ar would be suitable or not; but if not, an option to specify the location to binutils might be handy.

**Comment by boris-kolpackov** [comment]
Yes, this is a bug that has been fixed for the next release (which is almost ready). In the meantime, can you try the staged version by following the same installation instructions but getting the script from here:

https://stage.build2.org/0/

P.S. There are configuration variables to specify binutils locations (`config.bin.ar`, etc), but not the install script options.

**Comment by hazelnusse** [comment]
`build2-install-0.9.0-a.0-stage.sh` from the link above worked as expected. Thanks for the quick response.

To clarify your P.S.: You mean `build2-install-*.sh` doesn't permit specifying which binutils to use, but the result of that script (`b`, `bdep` `bpkg`), does permit these variables to be configured -- is this accurate?

**Comment by hazelnusse** [comment]
Great! Reading the documentation now.
