### ISSUE TITLE
Using build2 to render large(-ish) document+asset trees

### ISSUE THREAD

**Issue by daviddeutsch** [build2/build2#135]
Note: @boris-kolpackov agreed to move [this discussion](https://news.ycombinator.com/item?id=26397954) over here, so this is meant to be a discussion and not really an "issue".

-----------------

I'm currently using `make` to render html document trees and associated assets. The underlying assumption is that most websites are embarrassingly static making `make` a more appropriate tool than the currently prevailing "let's assume everything is dynamic and then cache stuff" approach.

This has been working well for me for a few years but I'm running into performance issues now that I deal with larger sites and partially dynamic code like admin interfaces where, for instance, the content of an edit screen changes depending on user input. Furthermore, I need to generate a LOT of Makefiles that I include during a `make` run which isn't very performant when I run `make` over and over again. I've filed an issue discussing this for `remake` over [here](https://github.com/rocky/remake/issues/114). The tl:dr; is that `make` has to build the same graph over and over again from thousands of Makefiles only to run on or two recipes. This seems especially wasteful because I have complete knowledge over what files have changed before I run `make`… which then goes on to infer the same information by reading the filesystem.

I also need to generate a lot of dependency files (so, Makefiles that only list dependencies for targets) and have to include them in `make` which results in a lot of `make` reruns during initial builds.

-----------------

The underlying setup is rather simple. I have build helper files that I call `make` "blueprints" which look like this:
```Makefile
rendered/public/{{ path }}.jpg: cache/src/{{ path }}.moz.jpg | rendered/public/{{ path|dirname }}/
	-@rsync --checksum $< $@

cache/src/{{ path }}.moz.jpg: src/{{ path }}.jpg | cache/src/{{ path|dirname }}/
	cat $(CURDIR)/$< | mozjpeg -quality 90 -optimize -progressive > $@
```
So in my html file that gets rendered to `rendered/public/index.html`, I might have a dependency for the browser (the browser is basically a PHONY target in my setup) to want to request a .jpg file. The recipe in the above blueprint takes the source file and compresses and copies it to the public folder that the browser can access.

When I build the index.html.public.d file, this then results in a long line of dependencies and includes like this:
```Makefile
Browser: \
  $(publicdir)/public.min.css \
  $(publicdir)/public.min.js \
  $(publicdir)/assets/img/image.jpg \

ifeq (,$(findstring $(makedir)/$(publicdir)/public.min.css.mk,$(MAKEFILE_LIST)))
-include $(makedir)/$(publicdir)/public.min.css.mk
endif

ifeq (,$(findstring $(makedir)/$(publicdir)/public.min.js.mk,$(MAKEFILE_LIST)))
-include $(makedir)/$(publicdir)/public.min.js.mk
endif

ifeq (,$(findstring $(makedir)/$(publicdir)/assets/img/image.jpg.mk,$(MAKEFILE_LIST)))
-include $(makedir)/$(publicdir)/assets/img/image.jpg.mk
endif
```
And in that `image.jpg.mk` would be the blueprint with the `{{ path }}` evaluated to 'image'.

The blueprints are also a way to get around the `make` restriction of having only one "%". So you can do things like:
```Makefile
rendered/public/assets/img/{{ path }}-w{{ width }}-h{{ height }}.png: src/assets/img/{{ path }}.png | rendered/public/assets/{{ path|dirname }}/
	cat $(CURDIR)/$< | convert -resize {{ width }}x{{ height }} - png:- > $@
```

That covers most of the "things that are used in a lot of places" scenarios.

However, documents can also have their own recipes embedded in them, so evaluating a document for its dependencies might also return recipes for building them.

-----------------

Another issue that I run into a lot is having to determine whether a target file has actually changed which I currently solve by writing everything in an intermediate folder and then doing an `rsync --checksum`.

This gets particularly weird because I store my data in .json files and, for instance, when I want to build a list html file of all the data files, I have to do gymnastics like this:
```Makefile

cache/src/products.json: cache/src/products.json.force
	-@rsync --checksum $< $@

cache/src/products.json.force: cache/src/products.raw
	cat $< | jq -s 'sort_by(.created)' >?> $@

cache/src/products.raw: cache/src/ls/data$(subdir)/product.ls | data/product/
	find data$(subdir)/product -maxdepth 1 -name "*.json" | xargs cat >?> $@


cache/src/ls{{ path }}.ls: cache/src/ls{{ path }}.stat.comp | cache/src/ls{{ path|dirname }}/
	-@compgen -G {{ path }}/* > /dev/null && stat -c "%n" {{ path }}/* | xargs -n 1 basename | tr '\n' ' ' > $@ || echo "" > $@

cache/src/ls{{ path }}.stat.comp: cache/src/ls{{ path }}.stat.comp.force
	-@rsync --checksum $< $@

cache/src/ls{{ path }}.stat.comp.force: FORCE | cache/src/ls{{ path|dirname }}/
	-@compgen -G {{ path }}/* > /dev/null && stat -c "%y %n" {{ path }}/* >?> $@ || echo "" > $@

FORCE:

```
So that is basically how I implemented "having a dependency on a database" by implementing "having a dependency on a directory".

-----------------

Another "fun" thing that I implemented was informing the browser over changes in the html via websocket, like so:
```Makefile

+cache/src/{{ path }}.prefinal.html:
	@util/bin/domDataDiffer $(CURDIR)/$@.old $(CURDIR)/$@ /{{ path }}.html | ifne curl -H "content-type: application/json" -s -f -d @- $(cfg.config.slug).internal/pubsub > /dev/null

```
(this generates a json message and copies the current copy of the target file over to the .old copy)

Any "plus rule" is attached to recipes when those are compiled. (The target is converted into a regex like `cache\/src\/(?<path>\S*)\.prefinal\.html` and those regexes are matched against the path and the recipe appended.)

-----------------

The most pressing thing I'm after is avoiding pre-rendering makefiles for almost every file I want to build and instead have the dependencies and recipes queried dynamically as the graph is built.

Furthermore, ideally, it would be great to keep a process running that holds the build graph in memory instead of rebuilding it over and over again and which I can query for an update, _somehow_

**Comment by daviddeutsch** [comment]
**on no. 1**: Yeah, regex captures would be great because I'm using those anyhow when I generate my Makefiles

**2&3** are kind of connected for me. Let me try to make an example that might help illustrate my situation. This would be a redacted version of the dependency graph of an html file where the build is basically:

1. convert the source html file into an AST
2. Generate a rendering script from that AST
3. Execute the rendering script to write the output html

```
# The file that the browser downloads
rendered/public/index.html: cache/src/index.html
    cp $< $@

# An intermediate file to ensure the final target is only updated if the checksum is different
cache/src/index.html: cache/src/index.prefinal.html cache/src/index.prefinal.html.d
    rsync --checksum $< $@

# The dependencies of the rendered html
cache/src/index.prefinal.html.d: cache/src/index.prefinal.html
    bin/renderedDependenciesFinder $< > $@

-include cache/src/index.html.d

# Rendering the output html
cache/src/index.prefinal.html: cache/src/index.html.render.script
    $< > $@

# The script used to render the html
cache/src/index.html.render.script: cache/src/index.html.ast cache/src/index.html.render.script.d
    bin/renderScriptBuilder $< > $@

# Dependencies in the AST (components etc.) for generating the render script
cache/src/index.html.render.script.d: cache/src/index.html.ast
    bin/astDependenciesFinder $< > $@

-include cache/src/index.html.render.script.d

# Making a syntax tree from the source html
cache/src/index.html.ast: src/index.html
    bin/astBuilder $< > $@
```
And the `.d` files are just Makefiles that declare further dependencies (including further Makefiles) for their associated target and/or provide the recipes for those dependencies.

> My impression is that you have the "makefile generation" step to work around `make` limitations and the first prize would be to get rid of it entirely?

Yes, many, MANY "makefile generation" steps. A current project that has 34 html source templates which get expanded to 2.2k html target files (plus associated assets for a total of 8.5k files) has 3.5k Makefiles with 180k LOC of `make` directives.

> "Documents can also have their own recipes embedded in them" … I must say I haven't seen that before

Maybe my initial explanation was a bit too convoluted, but the gist of it is that there is a chain of build steps between the source and the target document where I first figure out what dependencies are needed, then resolve those dependencies and then move on to the next build step.

The problem is that within `make`, each of those steps means that I have to use an `-include` so `make` basically tries to run a Makefile and fails because the include isn't there yet, builds the include and restarts… again and again until all the includes are resolved. All of this is astonishingly fast, but also obviously very wasteful and only scalable up to a point.

An example for a document declaring a dependency would be something like this:
```html
<make target="rendered/public/assets/img/qr-code/{{ someCustomString }}.png" recipe="qrencode -o $@ '{{ someCustomString }}'"/>

<img src="/assets/img/qr-code/{{ someCustomString }}.png">
```
resulting in an entry in the `.d` file that looks something like this:
```Makefile
Browser: rendered/public/assets/img/qr-code/STRING.png

rendered/public/assets/img/qr-code/STRING.png
    qrencode -o $@ 'STRING'
```

**on no.4**: I guess it depends on how the build process caches and updates the dependency graph between runs. If build2 is efficient enough to handle this then sure, just rerunning might be fine. `make` on the other hand reads everything into memory on each startup which results in an "empty" run of `make` where nothing needs to be rebuilt taking 200-500ms. And that is with me already splitting up the tree and only redoing the parts that I know to be changed. A full system "empty run" currently takes up to almost 2 seconds.

**Comment by boris-kolpackov** [comment]
> The problem is that within `make`, each of those steps means that I have to use an `-include` so make basically tries to run a `Makefile` and fails because the include isn't there yet, builds the include and restarts.

In `build2` we have three phases: `load` (loading `buildfiles`), `match` (matching rules to targets), and `execute` (executing matched rules) and we can switch between them freely. I think all of what you've described can be implemented as custom rules in C++. But I am not sure we will be able to expose the same level of "sophistication" in Buildscript. Take the document with embedded recipes for example: in C++ you could parse the document, extract this information, and synthesize the necessary dependency declarations and recipes. I am not sure how the same can be achieved from a script. Maybe execute some external tool that does the extraction and then dumps a `buildfile` fragment that can be loaded?

> A full system "empty run" currently takes up to almost 2 seconds.
> A current project that has 34 html source templates which get expanded to 2.2k html target files (plus associated assets for a total of 8.5k files) has 3.5k Makefiles.

So an up-to-date check on 12K targets (8.5K + 3.5K) takes 2 seconds? I don't think that's bad, actually. The bulk of this time is probably taken up by `stat`'ing all the files, especially if we are talking about a cold run.

**Comment by daviddeutsch** [comment]
> Maybe execute some external tool that does the extraction and then dumps a buildfile fragment that can be loaded?

Well yeah, that's what I'm currently doing with `make` - use an external script to read the document and return a Makefile which I then include. So in a way, that is part of the "dyndep" thing I'm after - just that in addition to dependencies, it can also return recipes for those dependencies. The document is basically just html with comments embedded that start with the word "make" which get read out, so… it's not really a highly complicated matter :wink: I just use my templating to do both - produce the document _and_ makefile syntax at the same time.

> So an up-to-date check on 12K targets (8.5K + 3.5K) takes 2 seconds? I don't think that's bad, actually. The bulk of this time is probably taken up by stat'ing all the files, especially if we are talking about a cold run.

Well, half-cold. But yeah, as I've said - it works surprisingly well given the amount of targets involved. The problem is that I'm running this so often that most of what `make` ends up doing is indeed `stat`ing files. The resulting commands that are executed may just be 30-60ms and make booting up easily takes an order of magnitude longer than that. I guess that drives home the point why I would like to keep it in memory.

The benefit of all this is that I have a fully featured shell at my disposal, straight from the template, which is quite powerful. The downside is that I'm trying to include all of this in a dynamic web interface :joy: so my time budget is more in the 100-200ms budget range.

**Comment by boris-kolpackov** [comment]
FYI, ad hoc regex pattern rules are now implemented: https://github.com/build2/build2/commit/0baeb5209d3a111a53070c032d7cdb1e609e3516 You can try them with the [staged version](https://build2.org/community.xhtml#stage) of the toolchain.
