### ISSUE TITLE
Unable to bootstrap using GCC built with Clang

### ISSUE THREAD

**Issue by Tachi107** [build2/build2#136]
I'm trying to build and install `build2` on a machine without root access and with an "old" version of GCC and Clang installed (9). I need a C++20 compiler, so I've built and installed [GCC 10 from source](https://gcc.gnu.org/git/?p=gcc.git;a=tree;h=refs/heads/releases/gcc-10) using Clang 9 (I can't use GCC 9 because the source passes `-Wformat-diag` at the building compiler, making GCC 9 throw an error).
Unfortunately, when I try to build and install `b2` using the automated [installation script](https://build2.org/install.xhtml#unix) I get some errors regarding the compiler version I'm using:
```
+ build2/b-boot config.cxx=g++ config.bin.lib=static build2/exe{b}
warning: g++ looks like gcc but it is not
  info: use config.cxx to override
error: unable to extract Clang version from 'Configured with: ../gcc/configure CC=clang CXX=clang++ CFLAGS='-march=native -w' CXXFLAGS='-march=native -w' --prefix=/opt/work/.local --enable-checking=release --enable-languages=c,c++ --disable-werror --enable-lto --disable-multilib --disable-bootstrap --disable-libada --disable-libsanitizer --enable-silent-rules --quiet --silent'
  info: use config.cxx.version to override
```

I then tried to follow the [manual bootstrapping](https://build2.org/build2-toolchain/doc/build2-toolchain-install.xhtml#bootstrap-unix) instructions, but when running `build2/b-boot config.c=gcc config.c.version=10.2.1 config.c.version.build="20210312 (GCC)" config.c.std=c17 config.cxx=g++ config.cxx.id=gcc config.cxx.version=10.2.1 config.cxx.version.build="20210312 (GCC)" config.cxx.std=c++17 config.bin.lib=static build2/exe{b}` I get the following error:
```
warning: g++ looks like gcc but it is not
  info: use config.cxx to override
b-boot: libbuild2/cc/guess.cxx:778: build2::cc::guess_result build2::cc::guess(const char*, build2::cc::lang, const path&, const strings&, const butl::optional<build2::cc::compiler_id>&, build2::cc::pre_guess_result&, butl::sha256&): Assertion `!xi || (xi->type == pre.type && xi->variant == *pre.variant)' failed.
```

I think this issue could related to [this old issue](https://lists.build2.org/archives/users/2020-April/000764.html), since prebuilt GCC version shipped by distros usually have a version string like `gcc (Debian 10.2.1-6) 10.2.1 20210110`, but when built from source it looks like `gcc (GCC) 10.2.1 20210312`, without any spaces in the parenthesis.

This is fully reproducible on Ubuntu 19.10 and on Debian Testing, with the following steps:
```shell
export LC_ALL=C.UTF-8
export CC=clang
export CXX=clang++
alias cc=$CC
alias c++=$CXX
git clone https://gcc.gnu.org/git/gcc.git --branch=releases/gcc-10 --depth=1 --quiet
mkdir gcc-build
cd gcc-build
../gcc/configure CC=clang CXX=clang++ CFLAGS="-march=native -w" CXXFLAGS="-march=native -w" --prefix=$HOME/.local --enable-checking=release --enable-languages=c,c++ --with-default-libstdcxx-abi=new --disable-werror --enable-lto --with-cpu=native --with-arch=native --with-tune=native --disable-multilib --disable-bootstrap --disable-libada --disable-libsanitizer --enable-silent-rules --quiet >/dev/null 2>&1
make --jobs=$(nproc) --quiet >/dev/null 2>&1
make install --quiet >/dev/null 2>&1
export LD_LIBRARY_PATH=$HOME/.local/lib64:$HOME/.local/lib:$LD_LIBRARY_PATH
export LD_RUN_PATH=$HOME/.local/lib64:$HOME/.local/lib:$LD_RUN_PATH
export PATH=$HOME/.local/bin:$PATH
unalias cc
unalias c++
unset CC
unset CXX
cd ..

ln --symbolic $HOME/.local/bin/gcc $HOME/.local/bin/cc
export CC=$HOME/.local/bin/gcc
export CXX=$HOME/.local/bin/g++
mkdir build2-build
cd build2-build
curl --silent --remote-name https://download.build2.org/0.13.0/build2-toolchain-0.13.0.tar.gz
tar xf build2-toolchain-0.13.0.tar.gz
cd build2-toolchain-0.13.0
cd build2
./bootstrap.sh g++
build2/b-boot config.c=gcc config.c.version=$(gcc -dumpspecs | grep --after-context=1 "*version:" | tail --lines=1) config.c.version.build="$(date +%Y%m%d) (GCC)" config.c.std=c17 config.cxx=g++ config.cxx.id=gcc config.cxx.version=$(g++ -dumpspecs | grep --after-context=1 "*version:" | tail --lines=1) config.cxx.version.build="$(date +%Y%m%d) (GCC)" config.cxx.std=c++17 config.bin.lib=static build2/exe{b}
*** error occurs here ***
```
I have to use `$(gcc -dumpspecs | grep --after-context=1 "*version:" | tail --lines=1)` instead of simply 10.2.1 since I'm tracking a GCC branch, not a release, and this script runs in a CI environment.

Output of `g++ --version`
```
g++ (GCC) 10.2.1 20210312
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Output of `g++ -v`
```
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/work/.local/libexec/gcc/x86_64-pc-linux-gnu/10.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc/configure CC=clang CXX=clang++ CFLAGS='-march=native -w' CXXFLAGS='-march=native -w' --prefix=/home/tachi/.local --enable-checking=release --enable-languages=c,c++ --with-default-libstdcxx-abi=new --disable-werror --enable-lto --with-cpu=native --with-arch=native --with-tune=native --disable-multilib --disable-bootstrap --disable-libada --disable-libsanitizer --enable-silent-rules --quiet --silent
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.2.1 20210312 (GCC) 
```

**Comment by boris-kolpackov** [comment]
Thanks for the report. The trigger here is the fact that GCC is built with Clang. It turns out we mis-detected `Configured with: ../gcc/configure CC=clang ` as Clang (because we checked for `"clang "`). I've now tighten this check and the fix is available in the [latest staged version](https://build2.org/community.xhtml#stage) of the toolchain. If you could give it a try and confirm it works for you, that would be great.

**Comment by Tachi107** [comment]
Thanks, I'll let you know as soon as possible

**Comment by Tachi107** [comment]
I can confirm that `build2` is now able to compile itself, thank you for the fast fix!
