### ISSUE TITLE
Support for module file names different than the file

### ISSUE THREAD

**Issue by nwotero** [build2/build2#138]
While playing with the latest build2 update with modules support, I attempted and failed to build a library with a module contained in a file with a different name. While I don't believe I will be using this in practice, I wanted to try it out to feel out the build system. If the names matched, everything builds fine. If I changed the name of the file, I got the following error:

```
fun_with_modules/fun_with_modules.cpp: error: unable to resolve module my_module
  info: verify module interface is listed as a prerequisite, otherwise
  info: consider adjusting module interface file names or
  info: consider specifying module name with cxx.module_name
  info: while extracting module dependencies from fun_with_modules/cxx{fun_with_modules}
  info: while applying rule cxx.compile to update fun_with_modules/obja{fun_with_modules}
  info: while applying rule cxx.link to update fun_with_modules/liba{fun_with_modules}
  info: while applying rule bin.lib to update fun_with_modules/lib{fun_with_modules}
  info: while applying rule alias to update dir{fun_with_modules/}
  info: while applying rule alias to update dir{./}
```
Based on the following comment taken from [here](https://build2.org/blog/build2-cxx20-modules-gcc.xhtml), I thought this should work. Did I misunderstand, did I miss a step, or is this a bug?

> Specifically, it does not expect the user to manually specify and maintain module name to file name mapping

**Comment by boris-kolpackov** [comment]
One doesn't have to manually specify the module name to file name mapping provided we can unambiguously guess the mapping (we need this guess as an optimization -- we actually verify that what we have guessed is correct before building anything). We expect this to work seamlessly for most real-world situations but for those few cases where the names have nothing in common for some reason, one can specify the mapping manually (as suggested in the diagnostics you have quoted):

```
mxx{fun_with_modules}: cxx.module_name = my_module
```

I suppose we could have been pedantic and mentioned this in the announcement.

**Comment by nwotero** [comment]
Sounds reasonable to me. Thanks!
