### ISSUE TITLE
Looking to use build2 -- should I use release 13? or git master?

### ISSUE THREAD

**Issue by jonesmz** [build2/build2#139]
It looks like the velocity of build2 is pretty fast. I don't want to start with release 13 if a new release is coming up.

**Comment by boris-kolpackov** [comment]
If you are interested to try newer stuff, then the [staged version](https://build2.org/community.xhtml#stage) of the toolchain is recommended. It is fairly stable and the release is a few months out.

Also in the future could you ask questions (as opposed to reporting issues) in a more appropriate channel (currently either slack or mailing list): https://build2.org/community.xhtml#help Thanks!

**Comment by boris-kolpackov** [comment]
> I did not believe reaching out on the mailing list would result in an answer.

Personally, mailing list is my preferred medium and I make a point of answering most emails.

> Github has a discussions feature that you can activate.

Yes, we are considering this though I am not sure we need a third channel. Do you know if such discussions are searchable with third-party search engines (Google, etc; like, say, stackoverflow Q&A are)? One big issue with Slack is that the content is not searchable form the outside.
