### ISSUE TITLE
Sometimes build2-install-msvc-0.13.0.bat --local aborts early complaining about missing "bin" dir under the install parameter

### ISSUE THREAD

**Issue by jonesmz** [build2/build2#140]
It does not happen every time. I have only been able to trigger it twice, out of the 5 builds I've run.

**Comment by boris-kolpackov** [comment]
This is probably a variant of the ["strange/other errors"](https://build2.org/install-faq.xhtml#windows-errors) case. We've done some work for the next release in this area so you may want to try the latest staged version of the toolchain to see if there is an improvement.

**Comment by boris-kolpackov** [comment]
I am assuming this is addressed and closing the issue. If not, feel free to reopen with additional information.
