### ISSUE TITLE
How do I make build2 not remember what compiler it was built with?

### ISSUE THREAD

**Issue by jonesmz** [build2/build2#142]
I want to use build2 for a pre-existing project where all builds must build all target types. This is a requirement from above my paygrade, so it's not something I have a say in.

Currently I'm in the early evaluation phase, and I'm struggling to deal with build2's compiled-in behavior. I want to have direct control over what compilers are called, with what arguments, when e.g. the cxx target type is used.

I see no way to influence the decisions that build2 has decided when it was compiled.

Where do I go?

**Comment by jonesmz** [comment]
Furthermore, the compiler originally used to build build2 using the msvc.bat script is *not* the compiler that will be used when build2 builds projects. Totally disconnected.

**Comment by Klaim** [comment]
The `config.cxx` and `config.c` variables controls the compilers being used for C++ and C respectively: ` b config.cxx=clang++` will build with my locally available `clang++`.

In any configuration directory there is a `build2/config.build` file where the variables (flags, toolsets, etc.) for that configuration are set.
You can set the compiler for c++ in `config.cxx` variable (either the name or a path) etc.

On Windows 10 I compile with the preview MSVC, the stable MSVC and Clang.
On Linux I use gcc, clang (several versions of both), emcc (emscripten's clang wrapper to target WebAssembly)
On MacOS I also build with  apple-clang to target iOS.

Using any compiler with `build2` is not a problem at all, the default is just there for when you want to do some dummy project quickly. See the manual for more details.

**Comment by jonesmz** [comment]
How can I completely remove the default?

The use of build2 that I have in mind is for a heavily curated codebase that doesn't involve dummy projects. Everything always gets built with the global configuration, or not at all.

**Comment by boris-kolpackov** [comment]
There are two preprocessor macros, `BUILD2_DEFAULT_C` and `BUILD2_DEFAULT_CXX`, which can be used to control this. In particular, if you define them to empty strings while building the `build2` build system, then there will be no default C/C++ compiler. For example (POSIX shell version):

```
b config.cc.poptions='-DBUILD2_DEFAULT_C=\"\" -DBUILD2_DEFAULT_CXX=\"\"'
```

Then, if you try to build a project with such a build system without explicitly specifying the compiler, you will get:

```
error: not built with default C++ compiler
  info: use config.cxx to specify
```

**Comment by boris-kolpackov** [comment]
I am assuming this is addressed and closing the issue. If not, feel free to reopen with additional information.
