### ISSUE TITLE
How to install only b.exe on windows?

### ISSUE THREAD

**Issue by jonesmz** [build2/build2#143]
I have my own system for packaging projects, and acquiring dependencies.

On windows:
```
build2-install-msvc-0.13.0.bat --yes --local --no-check C:\build2
```

Drops a whole mess of programs onto my system. Most (all?) of which I don't want except for b.exe

```
build2>ls *
README

bin:
b.exe          bsdtar.exe                 build2-bin-0.13.dll      build2-cxx-0.13-0.13.dll      build2-version-0.13.dll  diff.exe              git.exe      mingw32-make.exe           pkgconf-4.dll  ssl
bdep.exe       build2-0.13.dll            build2-c-0.13-0.13.dll   build2-cxx-0.13.dll           busybox.exe              git-receive-pack.exe  gzip.exe     msys                       rm.exe         tar.exe
bpkg-0.13.dll  build2-bash-0.13-0.13.dll  build2-c-0.13.dll        build2-in-0.13-0.13.dll       butl-0.13.dll            git-remote-http.exe   install.exe  odb-2.5.0-b.19.dll         rmdir.exe      unzip.exe
bpkg.exe       build2-bash-0.13.dll       build2-cc-0.13-0.13.dll  build2-in-0.13.dll            bzip2.exe                git-remote-https.exe  less.exe     odb-sqlite-2.5.0-b.19.dll  sha256sum.exe  xz.exe
bsdcat.exe     build2-bin-0.13-0.13.dll   build2-cc-0.13.dll       build2-version-0.13-0.13.dll  curl.exe                 git-upload-pack.exe   mingw        openssl.exe                sqlite3-1.dll  zip.exe

etc:
fstab

include:
libbpkg  libbuild2  libbutl  odb  pkgconf  sqlite3.h  sqlite3ext.h

lib:
bpkg.dll.lib         build2-bin.dll.lib  build2-cc.dll.lib   build2-in.dll.lib       build2.dll.lib  odb-sqlite.dll.lib  pkgconf.dll.lib  sqlite3.dll.lib
build2-bash.dll.lib  build2-c.dll.lib    build2-cxx.dll.lib  build2-version.dll.lib  butl.dll.lib    odb.dll.lib         pkgconfig

share:
doc  git-core  locale  man

ssl:
ct_log_list.cnf  ct_log_list.cnf.dist  openssl.cnf  openssl.cnf.dist

usr:
lib  share
```

I've inspected the build2-install-msvc-0.13.0.bat script and see that there are no options for skipping the installation of these third party programs.

Will b.exe fail to work if I remove everything except for b.exe and build2-*.dll ?

**Comment by boris-kolpackov** [comment]
It will work but large chunk of its functionality will be inoperable (`install`, `dist` operations, `version` module, Testscript language, etc). I think pretty much the only thing that is guaranteed to function is the `update`/`clean` core.

If you want just the build system, then perhaps it will be easier to bootstrap it directly as described in [`build2/INSTALL`](https://build2.org/build2/INSTALL).

**Comment by jonesmz** [comment]
> It will work but large chunk of its functionality will be inoperable (install, dist operations, version module, Testscript language, etc). I think pretty much the only thing that is guaranteed to function is the update/clean core.

Right, that's desired.

We're replacing a custom in house build system with (potentially) build2. CMake isn't suitable because it doesn't natively understand multiple compilers in the same build, but build2 does.

Any functionality that goes above and beyond just "turn C++ code into binaries" is dangerous, because jr developers will use them as foot-guns, and they wouldn't be compatible with our existing tools that accomplish those goals. So we want to remove as much functionality from the build2 installation as we can. There's always room for re-adding those features to our internal distribution of build2 in the future, but there's currently clear marching orders not to over-complicate the number of foot-guns we provide during the initial rollout.

**Comment by boris-kolpackov** [comment]
Then I think a static build of the build system should work for you. It's true that linking-in additional modules later shouldn't be too difficult.

**Comment by jonesmz** [comment]
> It will work but large chunk of its functionality will be inoperable (install, dist operations, version module, Testscript language, etc). I think pretty much the only thing that is guaranteed to function is the update/clean core.

Right, that's desired.

We're replacing a custom in house build system with (potentially) build2. CMake isn't suitable because it doesn't natively understand multiple compilers in the same build, but build2 does.

Any functionality that goes above and beyond just "turn C++ code into binaries" is dangerous, because jr developers will use them as foot-guns, and they wouldn't be compatible with our existing tools that accomplish those goals. So we want to remove as much functionality from the build2 installation as we can. There's always room for re-adding those features to our internal distribution of build2 in the future, but there's currently clear marching orders not to over-complicate the number of foot-guns we provide during the initial rollout.

**Comment by boris-kolpackov** [comment]
I am assuming this is addressed and closing the issue. If not, feel free to reopen with additional information.
