### ISSUE TITLE
How to statically link b.exe?

### ISSUE THREAD

**Issue by jonesmz** [build2/build2#144]
On Windows, I see that b.exe has several dlls as dependencies.
```
b.exe
build2-bin-0.13.dll
build2-cxx-0.13-0.13.dll
build2-version-0.13.dll  diff.exe
build2-0.13.dll
build2-c-0.13-0.13.dll
build2-cxx-0.13.dll
build2-bash-0.13-0.13.dll
build2-c-0.13.dll
build2-in-0.13-0.13.dll
```

and so on.

How do I tell build2-install-msvc-0.13.0.bat to statically link these dlls into b.exe? I want a single portable exe file that can be used to compile my projects. I don't want to carry around a large collection of dlls.

**Comment by boris-kolpackov** [comment]
I am assuming this is addressed and closing the issue. If not, feel free to reopen with additional information.
