### ISSUE TITLE
[UX] Allow specifying a version scheme for several package dependencies

### ISSUE THREAD

**Issue by Klaim** [build2/build2#146]
Feature Request
------------------

Let's assume that we have Boost libraries available.

If I want all the Boost libraries I use to be from the same version (which is usually how we use boost, as each version can break interface and behavior), in the manifest I have to copy-paste the version scheme in each depends.

```
depends: libboost-array ~1.75.0-
depends: libboost-variant2 ~1.75.0-
depends: libboost-chrono ~1.75.0-
depends: libboost-system ~1.75.0-
```

Ideally, I would like to have a way to express that several packages should have the same version.

Potential Solutions
---------------------

1. Maybe being able to name a version scheme and then be able to use it in the `depends` fields would help. Example:

```
boost_version = ~1.75.0-

depends: libboost-array $boost_version
depends: libboost-variant2 $boost_version
depends: libboost-chrono $boost_version
depends: libboost-system $boost_version

```

This solution does not reduce verbosity but does make the information located uniquely.

2. Another potential way would be to be able to "group" dependencies that should share the same version:

```
depends: {libboost-array libboost-variant2 libboost-chrono libboost-system} ~1.75.0-
```

This solution would reduce verbosity, but would also probably make harder for humans to read dependencies.

There might be other ways to explore.

**Comment by boris-kolpackov** [comment]
This is supported in `0.15.0` via dependency groups: https://build2.org/release/0.15.0.xhtml#bpkg-dependency-groups
