### ISSUE TITLE
`b install`: Allow to install everything BUT headers/sources (or other explicitly excluded set of files).

### ISSUE THREAD

**Issue by Klaim** [build2/build2#147]
Problem
---------

Let's assume that we are making an end-user application (with gui, or a game or a tool etc.).

Currently, doing `b install` will install all the dependencies of the application project in the install root, including headers and other source files marked to be installed.

This is useful for distributing libraries. An easy way to setup such distribution is to use `b install` with an empty directory to install into, then zip/archive that directory and send it to the user. 

However, we often do not want to send sources or headers to users when distributing an end-user application.
For that specific case, we need to remove the headers from libraries we use that have been installed through `b install` before being able to zip the install directory and send it to the end user.

It would be helpful if we had a way to specify to the `b install` command to NOT install source files, in particular headers.

Possible Solutions
--------------------

1. Boris said: 
  >  I suppose we could supporting something like `config.install.include=/dev/null`

That solution would then not install the files that should have been installed in the include directory.
I believe that it would work for most cases, but I wonder if that's enough. Are there other things from libraries that should not be installed in this situation?
  
2. Maybe an option to exclude whole types of targets would work? For example something like `config.install.exclude={cxx hxx ixx}`

**Comment by boris-kolpackov** [comment]
I think docs could be handled similarly, with `config.install.doc=/dev/null` (or perhaps more globally, with `config.install.share=/dev/null`). I think we have a pretty good categorization of things being installed with `config.install.*` variables: https://build2.org/build2/doc/build2-build-system-manual.xhtml#intro-operations-install

**Comment by boris-kolpackov** [comment]
This has been implemented and is available for testing in the latest staged toolchain. Until the release, the documentation can be found here: https://build2.org/stage/build2/doc/build2-build-system-manual.xhtml#install-filter

@helmesjo FYI

**Comment by helmesjo** [comment]
Great!

**Comment by Klaim** [comment]
Very nice! I'll try it ASAP
