### ISSUE TITLE
Interleaved compiler output in Powershell

### ISSUE THREAD

**Issue by kamrann** [build2/build2#148]
Output from running `b`/`bdep` in Windows Powershell is frequently interleaved.

[Sample terminal output](https://github.com/build2/build2/files/6286905/b-sample-powershell-terminal-output.txt)
Interleaving occurs beginning line 23, and again towards the end of the attached output.

This may be a Powershell terminal-specific issue, since a number of attempts to reproduce the same effect when redirecting the output to file (`bdep update *> output.txt`) all resulted in correct, non-interleaved output.

**Comment by boris-kolpackov** [comment]
Reportedly this also happens on Mac OS (Catalina).

**Comment by boris-kolpackov** [comment]
Perhaps this could also be the place/time to convert absolute paths to relative in diagnostics. Currently we have to pass an absolute path to the source file in order to be able to make sense of the headers (especially missing headers) in the compiler-produced dependency file (see the `-M*` family of options). This makes the diagnostics quite noisy.

**Comment by boris-kolpackov** [comment]
Ok, we've now implemented diagnostics buffering and it is available in the latest staged toolchain. Please test and report any issues.

One unfortunate side-effect of this change is that tools (for example, GCC, Clang) no longer see their `stderr` as terminal and disable the use of color in their diagnostics. We are still thinking whether we should handle this on the `build2` side, that is, recreate the tool's check for terminal and force color when buffering diagnostics. If we do go this route, then it opens the door to using color in `build2`'s own diagnostics (including in low-verbosity command lines; see issue #40).

**Comment by boris-kolpackov** [comment]
Ok, we've now implemented diagnostics buffering and it is available in the latest staged toolchain. Please test and report any issues.

One unfortunate side-effect of this change is that tools (for example, GCC, Clang) no longer see their `stderr` as terminal and disable the use of color in their diagnostics. We are still thinking whether we should handle this on the `build2` side, that is, recreate the tool's check for terminal and force color when buffering diagnostics. If we do go this route, then it opens the door to using color in `build2`'s own diagnostics (including in low-verbosity command lines; see issue #40).

**Comment by boris-kolpackov** [comment]
This fix has been out for a while now without any new complaints so far, so I am going to close this issue to keep things organized. But feel free to reopen if there are still any issues.
