### ISSUE TITLE
[DOCUMENTATION] Small typo in the documentation introduction

### ISSUE THREAD

**Issue by fmichaut-dev** [build2/build2#152]
Hello,

I wasn't exactly sure were to report this (since there is no option on the website to leave feedback), so I'm reporting it here

There is a typo in the build2 [documentation introduction](https://build2.org/build2-toolchain/doc/build2-toolchain-intro.xhtml#guide-add-remove-deps) (bullet point 2.3).

As you can see on the following picture, the `carret constraint` as been swapped with `tilde constraint` in the note below the explaination about version constraints.

![image](https://user-images.githubusercontent.com/33881730/117897661-3985bc80-b291-11eb-9dcc-184c31f57f14.png)

The `tilde constraint` doesn't have any "special treatment" for the major version, but the carret one does.

**Comment by boris-kolpackov** [comment]
Fixed, thanks for the bug report!
