### ISSUE TITLE
Fails to build for macOS

### ISSUE THREAD

**Issue by ambye85** [build2/build2#153]
When installing for macOS (Intel, BigSur 11.3), the build fails with:
```
...
Undefined symbols for architecture x86_64:
  "std::__1::__match_any_but_newline<build2::script::regex::line_char>::__exec(std::__1::__state<build2::script::regex::line_char>&) const", referenced from:
      vtable for std::__1::__match_any_but_newline<build2::script::regex::line_char> in run.b.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [build2/b-boot] Error 1
```

I found a similar issue previously at https://lists.build2.org/archives/users/2020-April/000789.html, and changed `#if defined(_LIBCPP_VERSION) && _LIBCPP_VERSION <= 10000` to `#if defined(_LIBCPP_VERSION) && _LIBCPP_VERSION <= 12000` in `build2-toolchain-0.13.0/build2/libbuild2/script/regex.hxx`. However, this approach still fails.

Clang info:
```
clang++ --version
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

How can this be fixed?

**Comment by karen-arutyunov** [comment]
Can you try to change it to just  ```#ifdef _LIBCPP_VERSION```?

**Comment by ambye85** [comment]
It gets as far as just after fetching dependencies, then also fails with a similar error:
```
...
ld build2-0.13.0/libbuild2/libs{build2}
Undefined symbols for architecture x86_64:
  "std::__1::__match_any_but_newline<build2::script::regex::line_char>::__exec(std::__1::__state<build2::script::regex::line_char>&) const", referenced from:
      vtable for std::__1::__match_any_but_newline<build2::script::regex::line_char> in libbuild2.dylib.u.a(run.dylib.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
info: failed to update (for install) dir{build2-0.13.0/}
```

**Comment by karen-arutyunov** [comment]
You can either proceed with a local installation (see --local option for the installation script) not to build build2 from the unpatched package or consider using the [Staged Toolchain](https://build2.org/community.xhtml#stage) where this issue is fixed.

**Comment by ambye85** [comment]
The Staged Toolchain works, thanks for your help.
