### ISSUE TITLE
Improve diagnostic when version constraint is violated

### ISSUE THREAD

**Issue by cdeln** [build2/build2#155]
Initializing a new package configuration with a violated version constraint gives a misleading diagnostic.

For example, if `hello` executable project (initialized with `bdep new -l c++ -t exe hello`) depends on `libhello ^0.1.0`, but `libhello` version is `^0.1.0-a.0.z`, then, initializing a project configuration for `hello` gives a log like this

```
initializing in project /tmp/hello/
created configuration /tmp/hello-out/ 1 default,forwarded,auto-synchronized
fetching dir:/tmp/libhello (prerequisite of dir:/tmp/hello)
error: unknown dependency libhello ^0.1.0 of package hello
  info: repository dir+file:///tmp/hello appears to be broken
  info: or the repository state could be stale
  info: run 'bpkg rep-fetch' to update
info: while satisfying hello/0.1.0-a.0.19700101000000
```
as you can see, the user gets informed that `libhello` is fetched, but then the issued diagnostic `error: unknown dependency libhello ^0.1.0 of package hello` indicates that it failed to find it (or that is how I first interpreted it).
Instead, a more informative diagnostic can be issued, showing the user that it just failed to find a matching version.

Suggested format: `error: dependency version constraint violated, required libhello ^0.1.0, found 0.1.0-a.0.z`

While this would be sufficient for the dummy example I tried out, in general there will be more versions of `libhello`.
Then, it would be more suitable to issue a set of versions that was found but that still does not meet the requirements of `hello`.

**Comment by karen-arutyunov** [comment]
The diagnostics is fixed in the latest staged version of the toolchain. Now it should be:

```
initializing in project /tmp/hello/
created configuration /tmp/hello-out/ 1 target default,forwarded,auto-synchronized
fetching dir:/tmp/libhello (prerequisite of dir:/tmp/hello)
error: unable to satisfy dependency constraint (libhello ^1.0.0) of package hello
  info: available libhello versions: 0.1.0-a.0.19700101000000
info: while satisfying hello/0.1.0-a.0.19700101000000

```
