### ISSUE TITLE
Initializing cross-compilation build configuration on Ubuntu 20.04 fails

### ISSUE THREAD

**Issue by cdeln** [build2/build2#156]
I am following the toolchain introduction.
In the introduction for configuring builds with `bdep`, I get a failure when setting up a build configuration for `mingw`.
I installed the compiler as a Debian package: `apt-get install g++-mingw-w64`.
Then I initialize a build configuration of the `hello` executable tutorial project by running `bep init -C ../hello-mingw @mingw cc config.cxx=x86_64-w64-mingw32-g++ -V`, which gives the following output
```
mkdir /tmp/hello/.bdep/tmp/
initializing in project /tmp/hello/
bpkg --verbose 3 create -d /tmp/hello-mingw cc config.cxx=x86_64-w64-mingw32-g++
mkdir -p /tmp/hello-mingw/
b --verbose 3 config.cxx=x86_64-w64-mingw32-g++ "create('/tmp/hello-mingw/', cc)"
mkdir /tmp/hello-mingw/build/
cat >/tmp/hello-mingw/build/bootstrap.build
cat >/tmp/hello-mingw/build/root.build
cat >/tmp/hello-mingw/buildfile
LC_ALL=C x86_64-w64-mingw32-g++ -v
error: unable to extract GCC minor version from '20200320'
  info: use config.cxx.version to override
rmdir -r /tmp/hello/.bdep/tmp/
```
It looks from the log that `bdep` tries to extract the compiler version from the output of `LC_ALL=C x86_64-w64-mingw32-g++ -v`, which on my machine gives
```
Using built-in specs.
COLLECT_GCC=x86_64-w64-mingw32-g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-w64-mingw32/9.3-win32/lto-wrapper
Target: x86_64-w64-mingw32
Configured with: ../../src/configure --build=x86_64-linux-gnu --prefix=/usr --includedir='/usr/include' --mandir='/usr/share/man' --infodir='/usr/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir='/usr/lib/x86_64-linux-gnu' --libexecdir='/usr/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --enable-shared --enable-static --disable-multilib --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --libdir=/usr/lib --enable-libstdcxx-time=yes --with-tune=generic --with-headers=/usr/x86_64-w64-mingw32/include --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libgomp --enable-languages=c,c++,fortran,objc,obj-c++,ada --enable-lto --enable-threads=win32 --program-suffix=-win32 --program-prefix=x86_64-w64-mingw32- --target=x86_64-w64-mingw32 --with-as=/usr/bin/x86_64-w64-mingw32-as --with-ld=/usr/bin/x86_64-w64-mingw32-ld --enable-libatomic --enable-libstdcxx-filesystem-ts=yes --enable-dependency-tracking
Thread model: win32
gcc version 9.3-win32 20200320 (GCC)
```

**Comment by cdeln** [comment]
As suggested by the first log (with the `-V` flag), you can override the compiler version with `config.cxx.version`. After setting it to `9.3.0` (I added a 0 for patch version since the compiler does not tell you), it also fails, again with the helpful message to set `config.c.version` . After overriding that config as well, I can successfully configure a cross compilation build with this command
`bdep init -C ../hello-mingw @mingw cc config.cxx=x86_64-w64-mingw32-g++ config.c.version=9.3.0 config.cxx.version=9.3.0`.

**Comment by boris-kolpackov** [comment]
Thanks for the report. Unfortunately we are playing constant catch-up with new ways people decide to mangle GCC's version. This is also the reason why we provide the `config.*.version` overrides. I will look into fixing this.

**Comment by cdeln** [comment]
Understandable. As a user, I wonder why does the build-chain need to know the compiler version? I would expect that by setting the compiler through `config.cxx=x86_64-w64-mingw32-g++`, the build system should just try it's best to compile my code with it.

**Comment by boris-kolpackov** [comment]
> As a user, I wonder why does the build-chain need to know the compiler version?

We need it in the implementation of the compile rule (which often does things differently/better for newer versions of the compiler). We also expose the version in the user's buildfiles which can be handy if you want to add an option (e.g., `-Wno-*`) that is only available starting from a certain version of the copiler.

Overall, compiling C++ without knowing the compiler/version only works for simple projects.

**Comment by cdeln** [comment]
I see, makes sense. Thanks for the info!

**Comment by boris-kolpackov** [comment]
This should be fixed in the latest staged version of the toolchain, if you would like to give it a try: https://build2.org/community.xhtml#stage

**Comment by cdeln** [comment]
I will check it out tomorrow!

**Comment by cdeln** [comment]
It works!

**Comment by boris-kolpackov** [comment]
Great, thanks for testing!
