### ISSUE TITLE
Inconsistent failure of the staging version of build2

### ISSUE THREAD

**Issue by zcorniere** [build2/build2#159]
Hello !
I have encountered a strange behaviour when working with `build2 0.14` on Linux. I have a [repo](https://github.com/EIP-Pivot/game-engine) which use build2 and c++20 modules. When I clone the repo in my home partition, `b` would fail, but in any other partition, it is working fine.

```
error: unable to import target libhello%lib{hello}
  info: use config.import.libhello configuration variable to specify its project out_root
  info: while applying rule cxx.link to update build-gcc/hello/hello/exe{hello}
  info: while applying rule alias to update build-gcc/hello/dir{hello/}
  info: while applying rule alias to update build-gcc/dir{hello/}
  info: while applying rule alias to update dir{./}
```
And the output of `b --verbose 6` : [build.6.log](https://github.com/build2/build2/files/6910793/build.6.log) (the error is around line 954)

**Comment by boris-kolpackov** [comment]
Hm, I've tried to reproduce this but so far no luck. One thing I've noticed from the log (thanks for providing, BTW) is that your build configuration directory (`build-gcc`) is inside your project directory (`game-engine/`) and is actually pulled into the build by the glue `buildfile`. This arrangement is definitely not supported and we should actually add a check to catch this. While I still couldn't reproduce the error even with this setup, it's possible that things are sensitive to the order in which the directories are returned by the filesystem. Therefore could you try the more canonical arrangement and see if it makes a difference? Here is what I did:

```
git clone https://github.com/EIP-Pivot/game-engine
cd game-engine
bdep init -C ../build-gcc cc config.cxx=g++-11
b
```

**Comment by zcorniere** [comment]
It is working as expected when following your instructions. Thanks !
But why the build configuration shouldn't be in the same directory as the project ?

**Comment by boris-kolpackov** [comment]
>But why the build configuration shouldn't be in the same directory as the project ?

In `build2` we keep sources and output in parallel directory structures. And the project directory is now made a simple build system project with a "glue" `buildfile` that pulls all the sub-directories. But if you remove this glue `buildfile`, then there should be no reason why you can't keep your build configurations inside your project. 

In fact, it would be great if you could confirm this works for you. That is, remove the root `buildfile` from your project and confirm that you no longer get an error with your original setup. Thanks!

**Comment by zcorniere** [comment]
If I removed the root buildfile, and run `bdep init --config-create build-gcc @gcc cc config.cxx=g++`, the project doesn't build at all in the root directory, but build fine if run inside the packages.

So I tried to alter the buildfile and give it an explicit path to the two module, instead of `*/`.
```
import pkgs = ./libecs/
pkgs += ./libgraphics/

./: $pkgs
```
I then ran the same `bdep` command as above.The bdep run fine, but now the `b` command does not work, and the reason differs at each run. A lot of time it is this message :
```
libgraphics/libgraphics/buildfile:7:1: error: unknown target type lib in lib{graphics}
  info: while applying rule alias to update dir{libgraphics/}
  info: while applying rule alias to update dir{./}
info: failed to update dir{./}
```
[lib.6.log](https://github.com/build2/build2/files/6929053/lib.6.log)

sometimes it is this one
```
libgraphics/tests/basics/buildfile:3:14: error: unknown target type hxx
  info: while applying rule alias to update libgraphics/dir{tests/}
  info: while applying rule alias to update dir{libgraphics/}
  info: while applying rule alias to update dir{./}
info: failed to update dir{./}
```
[hpp.6.log](https://github.com/build2/build2/files/6929050/hpp.6.log)

**Comment by boris-kolpackov** [comment]
> the project doesn't build at all in the root directory, but build fine if run inside the packages.

Yes, that's expected since you've removed the glue `buildfile`.

> So I tried to alter the buildfile and give it an explicit path to the two module [...]

The proper way do this would be:

```
import pkgs = libecs/ libgraphics/

./: $pkgs
```

That is, you need to import all your packages, not just list them as prerequisites. Can you try that?

**Comment by zcorniere** [comment]
It is working perfectly ! Thank you so much for your help !

**Comment by boris-kolpackov** [comment]
BTW, inspired but this, I've changed `bdep-new` to generate a smarter glue `buildfile` that reads `packages.manifest` rather than using directory wildcard:

```
# Glue buildfile that "pulls" all the packages in the project.
#
import pkgs = [dir_paths] $process.run_regex(\
  cat $src_root/packages.manifest, '\s*location\s*:\s*(\S+)\s*', '\1')

./: $pkgs
```
