### ISSUE TITLE
Using Emulators as Test Runners for Cross-Compilation Testing

### ISSUE THREAD

**Issue by lyrahgames** [build2/build2#161]
Hello,

assume for example that I would like to cross-compile a program on my x86_64 host architecture running Linux for an AArch64 target architecture also running Linux. All the required compilation tools, like `aarch64-linux-gnu-g++`, have already been installed in `/usr/aarch64-linux-gnu` with a correct subdirectory structure, `include`, `lib`, `lib64`, and `bin`, by the system's package manager.

First, I define a test project and create a cross-compile configuration. For simplicity, static compilation is used to get rid of errors while loading shared libraries. Afterwards, compiling this project should not emit any errors and indeed create an application which runs without problems on an AArch64 host machine.

```
bdep new -t exe -l c++ hello
cd hello
bdep init -C @aarch64-linux-gcc cc \
  config.cxx=aarch64-linux-gnu-g++ \
  config.cxx.loptions="-static -static-libgcc -static-libstdc++" \
  config.bin.exe.lib=static
bdep update @aarch64-linux-gcc
```
But using `bdep test @aarch64-linux-gcc` will fail because the host x86_64 system is not able to run an AArch64 executable without using an emulator. As a consequence, I would like to use QEMU with the command `qemu-aarch64` to test the executable without transferring it to an AArch64 host machine after every change.

```
$ qemu-aarch64 ../hello-aarch64-linux-gcc/hello/hello/hello
error: missing name
$ qemu-aarch64 ../hello-aarch64-linux-gcc/hello/hello/hello World
Hello, World!
```

Is it possible to do this kind of testing with build2's test module by providing something like a test runner variable `config.test.runner=qemu-aarch64` which shall be used to invoke a test program? Of course, the chosen architectures and platforms are only meant as an example.

**Comment by Klaim** [comment]
`config.test.runner=...` already exists in `v0.14.0` (current stage version): 
We had a similar issue when trying to use `emcscripten` (to build for WebAssembly, which will be officially supported soon but already work in the curernt `v0.14.0` staging of `build2`) where we needed the built binaries of the tests to be run in the `node` provided by `emscripten`.
We worked with the devs and among other things they provided `config.test.runner` so that we can set `config.test.runner=node` as part of the official support.
I have it set in my `wasm` configurations for example.

**Comment by lyrahgames** [comment]
Thanks. Very nice. I was not aware of that. Running the following in the staged toolchain works without problems.

```
bdep new -t exe -l c++ hello
cd hello
bdep init -C @aarch64-linux-gcc cc \
  config.cxx=aarch64-linux-gnu-g++ \
  config.cxx.loptions="-static -static-libgcc -static-libstdc++" \
  config.bin.exe.lib=static \
  config.test.runner=qemu-aarch64
bdep test @aarch64-linux-gcc
```

> Not sure if it can take arguments though.

I have also removed `-static` and tested it which results in an error due to the missing `/lib/ld-linux-aarch64.so.1' in emulation.

```
bdep init -C @aarch64-linux-gcc cc \
  config.cxx=aarch64-linux-gnu-g++ \
  config.cxx.loptions="-static-libgcc -static-libstdc++" \
  config.bin.exe.lib=static \
  config.test.runner=qemu-aarch64
bdep test @aarch64-linux-gcc
```

In QEMU, one can use `-L /usr/aarch64-linux-gnu` to provide the toolchain's base directory. Using the test runner variable with such an argument seems to work without problems.

```
bdep init -C @aarch64-linux-gcc cc \
  config.cxx=aarch64-linux-gnu-g++ \
  config.cxx.loptions="-static-libgcc -static-libstdc++" \
  config.bin.exe.lib=static \
  config.test.runner="qemu-aarch64 -L /usr/aarch64-linux-gnu"
bdep test @aarch64-linux-gcc
```

**Comment by Klaim** [comment]
Very nice! I'm taking notes because I'm interested in running some stuffs in `qemu` soon too.

> I was not aware of that. 

I don't think it's documented yet. `Emscripten` It wasn't officially announced yet either anyway, it's probably for the release.

**Comment by boris-kolpackov** [comment]
`config.test.runner` is documented in the 0.14.0 build system manual: https://build2.org/stage/build2/doc/build2-build-system-manual.xhtml#module-test

**Comment by lyrahgames** [comment]
Thank you. I think this issue can then assumed to be solved.

**Comment by boris-kolpackov** [comment]
BTW, can I ask which Linux distribution are you trying this on and how did you get the contents of `/usr/aarch64-linux-gnu`?

**Comment by lyrahgames** [comment]
> BTW, can I ask which Linux distribution are you trying this on and how did you get the contents of `/usr/aarch64-linux-gnu`?

Yes, of course.
I am using a custom installation of Arch Linux on both my laptop and desktop computer.
The `aarch64` or `riscv64` cross-compile toolchains are available in the official community package repositories of `pacman`.
You can install them by using the following commands.
```
sudo pacman -S aarch64-linux-gnu-gcc
sudo pacman -S riscv64-linux-gnu-gcc
```
