### ISSUE TITLE
Specify additional system search paths explicitly

### ISSUE THREAD

**Issue by r-burns** [build2/build2#164]
Hi! I'm trying to use build2 to build packages for Nixpkgs. Since all my dependencies are also installed through Nix, I'm not using `bpkg` or `bdep`, just `b` directly with system libraries. The problem is that Nix puts these libraries in goofy locations, so build2 doesn't know where to find them:

```
$ nix-build -A bpkg.buildInputs 
/nix/store/zwya0vfh02hqdwkf92505xpvcar7gd13-libbpkg-0.13.0-dev
/nix/store/y0nnvac7a3igvv1jq4hzch1jn4hsl037-libbutl-0.13.0-dev
/nix/store/an6h7avplzny3np3gbscmn07s8q1yxwl-libodb-2.5.0-b.19-dev
/nix/store/4xlvsl3l9s5zpyicqppgfhzrs39v96xl-libodb-sqlite-2.5.0-b.19-dev
```

Basically, each package is installed to its own prefix, and may even be further split into dev (headers/pkg-config) / doc (documentation/manpages) / libraries / etc.

Nixpkgs implements some workarounds so that typical projects compile out-of-the-box, such as:
* `-isystem $prefix/include` and `-L $prefix/lib` are respectively added to `NIX_CFLAGS_COMPILE` and `NIX_LDFLAGS` environment variables for each dependency, and these environment variables are implicitly used by the compiler when building packages
* all dependencies have their `$prefix/lib/pkgconfig` added to `PKG_CONFIG_PATH`
* all dependencies have their `$prefix` added to `CMAKE_PREFIX_PATH`

Despite this, build2 configuration usually fails with e.g. `error: unable to import target libbutl%lib{butl}`. I can get build2 to detect libbutl if I specify `config.cc.loptions+=-L$libbutl-dev/lib`. Since this is already on `NIX_LDFLAGS`, I tested out a very hacky patch which adds `NIX_CFLAGS_COMPILE`/`NIX_LDFLAGS` to the argument list parsed by `gcc_extract_library_search_dirs` et al.

That solution seems a bit unsanitary though - ideally I would want something like `config.extra_search_paths=<colon-separated-list-of-paths>`. Does something like this exist? Sorry for the brain dump. I'm sure there's a proper way to do this from build2's perspective.

**Comment by boris-kolpackov** [comment]
You can call `build2` functions in variable overrides so one way to achieve this would be to get the value of `NIX_LDFLAGS` (or `NIX_CFLAGS_COMPILE`), split it into elements, and set as the value of `config.cc.loptions` (or `config.cc.poptions`):

```
b config.cc.loptions='$regex.split($getenv(NIX_LDFLAGS), " +", "")'
```

(That `$regex.split()` call is a bit wicked in that it actually eliminates all the spaces with the result being all the unmatched parts as individual elements). 

The functions used:

`getenv`: https://github.com/build2/build2/blob/master/libbuild2/functions-builtin.cxx#L83

`regex.split`: https://github.com/build2/build2/blob/master/libbuild2/functions-regex.cxx#L683

**Comment by r-burns** [comment]
Thanks! That works great for `NIX_CFLAGS_COMPILE` into `cc.poptions`. (`NIX_LDFLAGS` is intended directly for `ld`; for example, it may contain raw `-rpath` flags without the `-Wl`. Does build2 have a corresponding `config.*` option for that?)

It seems a bit roundabout for my build scripts to transform dependency paths into compiler/linker flags, only for build2 to deconstruct them back into the dependency paths. (The flags will also end up duplicated on the final link line if I understand correctly, since NIX_LDFLAGS will be added by both build2 and Nix's compiler wrapper.) Is there a way to bypass the compiler argument parsing, and pass a list of paths directly to e.g. `sys_hdr_dirs`/`sys_lib_dirs`? (Maybe this desire is unique to Nix, and I should simply patch in a `NIX_BUILD2_LIB_DIRS` trapdoor or something.)

**Comment by r-burns** [comment]
I played around with this a little more, and all I actually need to add is `config.cc.loptions+=-L$prefix-dev/lib` for each dependency. I find this strange because the `-dev` outputs only contain headers and pkg-config files, so there are no actual libs in these `-L` directories. Maybe adding these to build2's linker flags fixing the problem because it adds them to the pkg-config search path, and that's all that's needed to detect dependencies?

**Comment by r-burns** [comment]
Sorry, I was mistaken. I need to add `config.cc.loptions` for the library dirs as well for build2 to detect the dependencies. However, since I still don't don't need to set any `poptions`, maybe build2 just isn't seeing the NIX_LDFLAGS. The Nixpkgs compiler wrapper only enables these when linking a library, so they might just not show up in build2's `-print-search-dirs` queries.

**Comment by boris-kolpackov** [comment]
Not sure if you've figured it out or gave up ;-), but just to clarify a few points:

> Maybe adding these to build2's linker flags fixes the problem because it adds them to the pkg-config search path, and that's all that's needed to detect dependencies?

Yes, if a library (including a header-only library) provides a `pkg-config` file, then all you need is `-L`.

> [...] so they might just not show up in build2's -print-search-dirs queries.

Header/library search paths specified with `poptions/loptions` are not considered (by `build2`) as system (which is what `-print-search-dirs`, etc is used to discover). I you want some `-L`/`-I` to be considered system, then you need to pass them as part of the "compiler mode" options in `config.c`/`config.cxx` variables:

```
b config.cxx="g++ -I/usr/local2/include -L/usr/local2/lib"
```

Though I don't see why you would necessarily want to do this (i.e., make them system) for ordinary dependencies.

**Comment by r-burns** [comment]
> Not sure if you've figured it out or gave up ;-)

Well, I think I've figured out enough to realize it's Nixpkgs weirdness causing my troubles, and not anything on build2's end :P 

Thank you for the clarification, it's making much more sense to me now. The "compiler mode" options seems like a neat trick, but I think you're right that it's not really correct to treat ordinary dependencies as system. I'll keep playing around with various approaches to see what's most ergonomic for packaging automation. For now, adding the libraries with `-L` seems to be working well.
