### ISSUE TITLE
Unwanted back-references to dependency headers in shared libs

### ISSUE THREAD

**Issue by r-burns** [build2/build2#165]
As some background, I'm using build2 to build packages for consumption by Nix. For libraries, I might split the outputs into runtime libraries, development headers + pkg-config files, and documentation. This is intended to reduce runtime closure size, as the `-dev` outputs are only needed at build time.

For reference, here are the output paths for libbutl and libbpkg:

```
$ tree -L 2 $(nix-build -A libbutl.all)
/nix/store/l465s4y8b0snbwrg8iax2aizxrnhwb43-libbutl-0.13.0
└── lib
    ├── libbutl-0.13.so
    └── libbutl.so -> libbutl-0.13.so
/nix/store/dqwjp4l6zya2p74zlnqf6asfk8dk6r04-libbutl-0.13.0-dev
├── include
│   └── libbutl
├── lib
│   └── pkgconfig
└── nix-support
    └── propagated-build-inputs
/nix/store/rxbcy2bibz63f7j6c9g3zwm4h53lwivl-libbutl-0.13.0-doc
└── share
    └── doc
```

```
$ tree -L 2 $(nix-build -A libbpkg.all)
/nix/store/p76z4w5ihc38m2f9v77ga8cmbsknl851-libbpkg-0.13.0
└── lib
    ├── libbpkg-0.13.so
    └── libbpkg.so -> libbpkg-0.13.so
/nix/store/dhc61axkaf3ml2ss1qqm6l0m1hlq5gnh-libbpkg-0.13.0-dev
├── include
│   └── libbpkg
├── lib
│   └── pkgconfig
└── nix-support
    └── propagated-build-inputs
/nix/store/l98g3i85yyg496c9s5brarh9866lis40-libbpkg-0.13.0-doc
└── share
    └── doc
```

However, when I look at a runtime library's dependencies (`nix-store -qR` = query requisites), I typically find that it references one or more of its development-only build dependencies:
```
$ nix-store -qR /nix/store/p76z4w5ihc38m2f9v77ga8cmbsknl851-libbpkg-0.13.0
/nix/store/7v6ck5q9f540qsni7pkc9pwk1yd9yygn-libunistring-0.9.10
/nix/store/js5xyvpmw5x6n29b2cg6k0gh1nxaw98j-libidn2-2.3.2
/nix/store/9bh3986bpragfjmr32gay8p95k91q4gy-glibc-2.33-47
/nix/store/0kiykyrnrpfhmjwxwx89kxr20hmf5304-gcc-10.3.0-lib
/nix/store/fpp7j8niqf6scahsmbilbqn2vykrs7vn-util-linux-2.36.2
/nix/store/l465s4y8b0snbwrg8iax2aizxrnhwb43-libbutl-0.13.0
/nix/store/dqwjp4l6zya2p74zlnqf6asfk8dk6r04-libbutl-0.13.0-dev
/nix/store/p76z4w5ihc38m2f9v77ga8cmbsknl851-libbpkg-0.13.0
```

These back-references seem to be caused by absolute paths to the dependency headers in the shared library.
```
$ strings /nix/store/p76z4w5ihc38m2f9v77ga8cmbsknl851-libbpkg-0.13.0/lib/libbpkg.so | grep '/nix/store/dqwjp4l6zya2p74zlnqf6asfk8dk6r04-libbutl-0.13.0-dev'
/nix/store/dqwjp4l6zya2p74zlnqf6asfk8dk6r04-libbutl-0.13.0-dev/include/libbutl/url.mxx
/nix/store/dqwjp4l6zya2p74zlnqf6asfk8dk6r04-libbutl-0.13.0-dev/include/libbutl/small-allocator.mxx
/nix/store/dqwjp4l6zya2p74zlnqf6asfk8dk6r04-libbutl-0.13.0-dev/include/libbutl/url.txx
/nix/store/dqwjp4l6zya2p74zlnqf6asfk8dk6r04-libbutl-0.13.0-dev/include/libbutl/path.txx
```

Why are these references in the shared library? Can they be avoided?

**Comment by boris-kolpackov** [comment]
> Why are these references in the shared library?

Well, strictly speaking we don't know for sure they are "references". All we know is that there is a sequence of printable characters in the shared library that happens to be a path to a header. My guess is the compiler adds them for some reason (debug info?). From our side, I am pretty sure we don't embed/reference header paths to/from our code. Have you tried:

1. To use `strings -d` instead?

2. To strip the shared library and see if it makes a difference?


> Can they be avoided?

I am not sure of the exact background here. It seems Nix sees an absolute path and jumps to conclusions. If that's the case and "absolute" is the key here, you can try to re-map them to something relative with GCC's `-ffile-prefix-map`.

**Comment by r-burns** [comment]
Hmm, well I'm stumped then.

The libraries are built without debug info and are stripped on installation. Switching to `strings -d` doesn't change the output. Using relative paths wouldn't help, as it's the hash component of the store path that triggers Nix's dependency detection.

I reconfigured/built/installed with `--verbose 4` and the logs don't contain any mention of `.mxx`/`.txx`, so I don't think the compiler is adding these.

**Comment by r-burns** [comment]
I looked at the disassembled functions and saw that the strings are being used by assertions. For instance, the full url.mxx path is used for these assertions:
https://github.com/build2/libbutl/blob/v0.13.0/libbutl/url.mxx#L137
https://github.com/build2/libbutl/blob/v0.13.0/libbutl/url.mxx#L160

Indeed, building consumers of libbutl with `config.cc.poptions+=-DNDEBUG` fixes the issue. It seems to me that libbpkg.so shouldn't ever refer to libbutl's headers, but maybe this is working as intended.

Also, setting `-DNDEBUG` globally when building libbutl breaks its tests. Should I open an issue there? Or is there a generic way to define `NDEBUG` but keep it undefined for tests which rely on assertions?

**Comment by boris-kolpackov** [comment]
Nice detective work!

> It seems to me that libbpkg.so shouldn't ever refer to libbutl's headers, but maybe this is working as intended.

Yes, I think this is working as intended. The path is embedded into the binary for diagnostics (`assert`). I think the fundamental problem here is that if a binary embeds a path to something, it doesn't necessarily mean it depends on this something.

> Also, setting `-DNDEBUG` globally when building libbutl breaks its tests. Should I open an issue there?

Yes, we don't currently support testing of `NDEBUG` builds but probably should. So, yes, please, open an issue!

> Or is there a generic way to define `NDEBUG` but keep it undefined for tests which rely on assertions?

Currently, the only way is to build tests separately, for example (assuming `libbutl/` is the package directory):

```
b  update: libbutl/ config.cc.poptions=-DNDEBUG
b test: libbutl/tests/@libbutl-tests-out/ config.import.libbutl=libbutl/
```

(`libbutl/tests/@libbutl-tests-out/` in the second command means "use `libbutl/tests/` as source directory and `libbutl-tests-out/` as output)

**Comment by r-burns** [comment]
Awesome, many thanks for all your help.

> Yes, I think this is working as intended. The path is embedded into the binary for diagnostics (assert). I think the fundamental problem here is that if a binary embeds a path to something, it doesn't necessarily mean it depends on this something.

Ok, makes sense. In Nix land, any literal mention of a store path creates a dependency, so in cases like this, it's my job to "nuke" the references by zeroing out the path's hash component. Fortunately this is unnecessary when using `NDEBUG`, which I probably should have been using from the start ;)

> Yes, we don't currently support testing of `NDEBUG` builds but probably should. So, yes, please, open an issue!

Great! I will open an issue on libbutl shortly.
