### ISSUE TITLE
User config for build2 tools

### ISSUE THREAD

**Issue by masterspline** [build2/build2#17]
For customizing build2 tools we can currently use command line arguments and edit generated files. Arguments are too difficult to remember and user can have their preferences for all his projects. So user configuration can help (also see here #16 and here https://github.com/build2/bdep/pull/1)

The aim of this feature request is to make build2 configuration easier (command line arguments are too difficult to remember and some `bdep new` generated file, .gitignore for example, need editing too)

Some suggested solutions:
1. explisot config file (`bdep new --config path/to/file.conf`)
2. global and user configuration as in `git`
3. config searched from current directory until found or `/` reached.
4. make `bdep new` interactive

**Comment by masterspline** [comment]
We can use 1, then fallback to 2 or 3 or 4.

**Comment by boris-kolpackov** [comment]
In the `0.12.0` release we've added support for default options files (aka tool config files). For details see the `DEFAULT OPTIONS FILES` section in `b(1)`, `bdep-<command>(1)` and `bpkg-<command>(1)`.

Also, in this release `bdep-new` support creation from existing files as well as the `--pre-hook` option. While this doesn't complete eliminate the need for the interactive mode, it probably reduces it somewhat. So I am going to close this but we will keep an eye on whether interactive mode is requested in the future.
