### ISSUE TITLE
[Feature request]: Include project variables while installing targets

### ISSUE THREAD

**Issue by Swat-SomeBug** [build2/build2#173]
Following our [discussion](https://cpplang.slack.com/archives/CDJ0Z991S/p1637350730070600) on the [build2 slack channel](https://cpplang.slack.com/archives/CDJ0Z991S), this issue requests the a feature to include target/project variables during target installation.
The motivation is to allow consumers to selectively modify the build process based on the configuration of the consumed project.

#### What is already available and some discussion
When projects are build completely using build2, a consumer may access target set variables using `$(target: var)` syntax, where `target` is exported by the consumed project.

This mechanism can be extended to installed targets by writing variables in `.pc` files. Here the project/package should control what variables are to be written out. Question:
1. How to decide what variables should be written out?
2. Should all `config.<project>` variables be written to `.pc` file, as this represents the full configuration of the consumed project/target?

**Comment by boris-kolpackov** [comment]
This has been implemented and now available in the latest staged toolchain, please test. The documentation can be found here: https://github.com/build2/HOWTO/blob/master/entries/convey-additional-information-with-exe-lib.md

**Comment by boris-kolpackov** [comment]
This functionality is now available in the released version so I am closing this issue.
