### ISSUE TITLE
Dry run mode is broken

### ISSUE THREAD

**Issue by minerva** [build2/build2#175]
Despite the dry-run mode's promise to not touch the filesystem, `b -nv update` generates build output as if the `-n` flag was ignored on my Windows machine. Interestingly, `b -nv clean` however respects the `-n` flag.

**Comment by boris-kolpackov** [comment]
> Despite the dry-run mode's promise to not touch the filesystem

Hm, I don't believe we've made such a promise. Quoting from [`b(1)`](https://build2.org/build2/doc/b.xhtml):

> Print commands without actually executing them. Note that commands that are required to create an accurate build state will still be executed and the extracted auxiliary dependency information saved. In other words, this is not the _"don't touch the filesystem"_ mode but rather _"do minimum amount of work to show what needs to be done"_.

Where in the documentation did you see such a promise (so that we can fix it)?

> `b -nv update` generates build output as if the `-n` flag was ignored on my Windows machine

Are you sure you get the same build output with and without `-n`? Including object files, libraries, and executables? Or are you mistaking the presence of `.d` files for the complete build output?

**Comment by minerva** [comment]
> Are you sure you get the same build output with and without -n? Including object files, libraries, and executables? Or are you mistaking the presence of .d files for the complete build output?

No, every component is generated as if `-n` was missing: object files, the executable and the `.d` file.

**Comment by boris-kolpackov** [comment]
Hm, can you try this and see if you get a different result:

```
> bdep new -t lib libhello
created new library project libhello in C:\tmp\libhello\

> b -nv libhello\
...

> dir libhello\libhello\

Directory of C:\tmp\libhello\libhello

2021/12/13  07:26                45 .gitignore
2021/12/13  07:26             1 553 buildfile
2021/12/13  07:26             1 850 export.hxx
2021/12/13  07:27               371 hello-0.1.0-a.0.19700101000000.dll.d
2021/12/13  07:26               292 hello.cxx
2021/12/13  07:27            10 799 hello.dll.obj.d
2021/12/13  07:26               330 hello.hxx
2021/12/13  07:27               436 hello.lib.d
2021/12/13  07:27            10 799 hello.lib.obj.d
2021/12/13  07:27             1 072 version.hxx
2021/12/13  07:27             1 005 version.hxx.d
2021/12/13  07:26             1 238 version.hxx.in

> dir libhello\tests\basics\

 Directory of C:\tmp\libhello\tests\basics

2021/12/13  07:26                94 buildfile
2021/12/13  07:26               551 driver.cxx
2021/12/13  07:27               371 driver.exe.d
2021/12/13  07:27            11 227 driver.exe.obj.d
```

**Comment by boris-kolpackov** [comment]
I will assume this is no longer an issue and close it. But feel free to reopen (with more information) if you believe this is still an issue.
