### ISSUE TITLE
bdep ignores "forwarded", b doesn't

### ISSUE THREAD

**Issue by helmesjo** [build2/build2#177]
```
bdep --version
bdep 0.14.0
libbpkg 0.14.0
libbutl 0.14.0
Copyright (c) 2014-2021 the build2 authors.
This is free software released under the MIT license.
```

I have the following configuration setup:
`@gcc11 /<path>/project-gcc11/ 8 target default,forwarded,auto-synchronized`

When I run `b update` (or just `b`), it builds and executables are backlinked as expected.
When I run `bdep update`, it builds but no executables are backlinked.

Running with `-v` I see that the initial command is _almost_ the same:

**`b update -v`**
```
bpkg -v build -d /<path>/project-gcc11 --no-fetch --no-refinement --no-private-config 125 --noop-exit 124 --configure-only --keep-out --plan "synchronizing /<path>/project-gcc11/:" --yes project@/<path>/project
                                                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**`bdep update -v`**
```
bpkg -v build -d /<path>/project-gcc11 --no-fetch --no-refinement --no-private-config 125 --noop-exit 124 --configure-only --keep-out --plan synchronizing: --yes project@/<path>/project
                                                                                                                                      ^^^^^^^^^^^^^^^^^^^^^
bpkg -v update -d /<path>/project-gcc11 convertible
b -v update('/<path>/project-gcc11/project/')
```

Note the flag `--plan` which differs, and also the trailing two commands for `bdep`. Can't find anything in the documentation regarding this difference.

**Comment by boris-kolpackov** [comment]
Thanks for the report. Yes, this behavior is incorrect: `bdep` should update forwarded configurations through the source directory. Will aim to fix for 0.15.0.

**Comment by helmesjo** [comment]
Any chance this will get fixed soon? It's one of those small things I have to repeatedly explain to team members why it doesn't work as expected.

**Comment by boris-kolpackov** [comment]
Yes, will try to fix in the coming week or two (it's the "polishing before the release" time).

**Comment by boris-kolpackov** [comment]
This has been fixed in the latest staged toolchain, please test.

**Comment by helmesjo** [comment]
Yep, works fine for me.

**Comment by boris-kolpackov** [comment]
Perfect, thanks for testing. I am going to close this issue to keep things organized. But feel free to reopen if there are still any issues.
