### ISSUE TITLE
"error: process b terminated abnormally"

### ISSUE THREAD

**Issue by helmesjo** [build2/build2#179]
```
bdep --version
bdep 0.14.0
libbpkg 0.14.0
libbutl 0.14.0
Copyright (c) 2014-2021 the build2 authors.
This is free software released under the MIT license.
```

## Reproduce
1. `bdep new --no-init -l c++ -t lib hello`
2. `cd hello && bdep init -C @gcc config.cxx=g++`
3. Add `dummy.cxx` & `dummy.test.cxx` in `/hello/hello` ([repro.zip](https://github.com/build2/build2/files/7875071/repro.zip))
4. Replace `/hello/hello/buildfile` with attached `buildfile`^.
5. ```
    bdep update @gcc
    error: process b terminated abnormally: segmentation fault (SIGSEGV) (core dumped)
    ```

**Notes:**
* Not compiler related (same thing happened with GCC, Clang & Mingw).
* This is not a buildfile I'm using, I just stumbled upon the issue and compressed a minimal repro

**Comment by boris-kolpackov** [comment]
This should be fixed in the latest staged toolchain: https://build2.org/community.xhtml#stage

Thanks for the report and the reproducer! Feel free to reopen this issue if there are still any problems.
