### ISSUE TITLE
compiler does not support modules

### ISSUE THREAD

**Issue by shitpoet** [build2/build2#2]
I can manually build a simple c++ modules TS project with my clang++ (7.0.0 trunk), but when i try to use build2 `b` command it prints "compiler does not support modules" message.

```
$ clang++ --version
clang version 7.0.0- (trunk)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

What can be wrong?

To enable modules support I added following lines to root `buildfile`:

```
cxx.std = experimental

using cxx

assert $cxx.features.modules 'compiler does not support modules'

mxx{*}: extension = mxx
cxx{*}: extension = cxx
```

**Comment by boris-kolpackov** [comment]
Can you tell which version of `build2` you are using (`--version`) and show the C++ compiler configuration printed with `-V`. I tried your setup with clang 6.0 and it works for me (with the latest staged toolchain):

```
cxx hello@/tmp/hello-clang/hello/
  cxx        clang++-6.0@/usr/bin/clang++-6.0
  id         clang
  version    6.0.1-svn334776-1~exp1~20180627160618.85 (branches/release_60)
  major      6
  minor      0
  patch      1
  build      svn334776-1~exp1~20180627160618.85 (branches/release_60)
  signature  clang version 6.0.1-svn334776-1~exp1~20180627160618.85 (branches/release_60)
  checksum   ae8c3ac438dcba2acb4885217c91142f0ec2b748d3a11e79c5fa69f90864d112
  target     x86_64-linux-gnu (x86_64-pc-linux-gnu)
  runtime    libgcc
  stdlib     libstdc++
  c stdlib   glibc
  std        -std=c++2a -D__cpp_modules=201704 -fmodules-ts
  pattern    *-6.0
```

**Comment by shitpoet** [comment]
build2 version:

```
$ bdep --version
bdep 0.7.0
libbpkg 0.7.0
libbutl 0.7.0
```
How to see C++ compiler config? I extracted this from `b -V`, it seems like it what you are asking?

```
cxx cult@/home/ors/fun/cult/build/cult-clang/cult/
  cxx        clang++@/usr/bin/clang++
  id         clang
  version    7.0.0- (trunk)
  major      7
  minor      0
  patch      0
  build       (trunk)
  signature  clang version 7.0.0- (trunk)
  checksum   976cd6ecfb2318efe3e22a276c8d6d2344da0cecc3aa4c4c04d91ae4062ccfd8
  target     x86_64-linux-gnu (x86_64-pc-linux-gnu)
  runtime    libgcc
  stdlib     libstdc++
  c stdlib   glibc
  std        -std=c++2a
```

I think I can try to remove clang 7 and try with clang 6.

**Comment by shitpoet** [comment]
Also I noticed that we have different `std` configs.

**Comment by boris-kolpackov** [comment]
Can you try with the latest staged version of the toolchain rather (it has the most up to date modules support)? It's the same install procedure but get the script from here:

https://stage.build2.org/0/

**Comment by shitpoet** [comment]
I downloaded sh-script and tried to execute it with compiler option (to use clang++ during installation).

And there're some messages at the end:

```
$ sh build2-install-0.8.0-a.0-stage.sh --cxx clang++
...
cli build2/build2/cli{b}           
Unknown command line option: '--output-suffix'
version.in libodb/odb/version-build2.hxx.in
cli libodb-sqlite/odb/sqlite/details/cli{options}
Unknown command line option: '--include-with-brackets'
info: failed to update (for install) dir{build2/}
info: failed to update (for install) dir{bpkg/}
```

Full log - https://pastebin.com/aGESCNNc

**Comment by shitpoet** [comment]
The same with default compiler (gcc)

```
+ build2/build2/b-boot install: build2/ bpkg/
version.in libbpkg/libbpkg/version.hxx.in
version.in libodb-sqlite/odb/sqlite/version-build2.hxx.in
cli build2/build2/cli{b}           
Unknown command line option: '--output-suffix'
version.in libodb/odb/version-build2.hxx.in
cli libodb-sqlite/odb/sqlite/details/cli{options}
Unknown command line option: '--include-with-brackets'
info: failed to update (for install) dir{build2/}
info: failed to update (for install) dir{bpkg/}
```

**Comment by boris-kolpackov** [comment]
Hm, looks like you have old/wrong `cli`. What does `cli --version` print?

**Comment by shitpoet** [comment]
```
$ cli --version
Mono JIT compiler version 5.12.0.226 (tarball Thu May  3 09:49:46 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

**Comment by shitpoet** [comment]
Restarting the project from scratch, I somehow managed it to work (clang 7.0.0 & build2 0.7.0). So, i think, we can close this issue.

**Comment by boris-kolpackov** [comment]
Ok, you have something else called `cli`, I guess we need to handle that.

Re "managed it to work" did you build 0.8.0 (staged) or 0.7.0 (public) and does "work" mean your original modules example works as expected?

**Comment by boris-kolpackov** [comment]
BTW, I've just staged the latest master which should handle your `cli`, if you want to give it a try.

**Comment by shitpoet** [comment]
> Re "managed it to work" did you build 0.8.0 (staged) or 0.7.0 (public) and does "work" mean your original modules example works as expected?

I reinstalled build2 0.7.0, then created empty project with one c++ module, changed some config files (buildfile and root.build), and it started compiling a project with c++ modules using my clang++ 7.0.0.

> BTW, I've just staged the latest master which should handle your cli, if you want to give it a try.

Yes, now build2 builds with gcc and with clang++ ok. 

One small "problem" I noticed is that I erroneously specified option `--cxx clang` instead of `--cxx clang++` first time. Build started but after some time generated a wall of errors. Not the error, but may be it can be not bad idea to make the installer more forgiving - f.ex. generating a warning, than not an C++ compiler was specified?

**Comment by boris-kolpackov** [comment]
We do it in the build system itself but doing it 100% reliably during bootstrap from a (POSIX) script is not easy. But I've added a few patterns and a warning that should cover most common cases (like `clang`, `clang-6.0`, etc., as well as the equivalent for GCC).

**Comment by boris-kolpackov** [comment]
I am assuming all is working now so closing the issue. But feel free to reopen if that's not the case.
