### ISSUE TITLE
[Windows] Using directory wildcards `*/` with relative-path-to-library in end-user projects leads to errors

### ISSUE THREAD

**Issue by Klaim** [build2/build2#20]
```
PS G:\test\test-wildcard> b --version
build2 0.11.0-a.0.fbf648a6bf69
libbutl 0.11.0-a.0.ede5f2102b20
host x86_64-microsoft-win32-msvc14.1
Copyright (c) 2014-2019 Code Synthesis Ltd
This is free software released under the MIT license.
```

Feel free to rename this ticket, the title is'nt perfect and you might find a more useful name.

How to reproduce:
---------------------

#### 0. Platform:

This issue **only appears on Windows** even with the same build2 version.
I tried on an Ubuntu server + gcc and on Windowsx 10 (with and without Powershell), with the same Visual Studio than the one build2 was built with.

#### 1. Project setup:

```
bdep new test-wildcard -t bare
cd ./test-wildcard/
bdep new --subdirectory -t lib aaa
bdep new --subdirectory -t lib bbb
```

This builds fine, whatever the way.

#### 2. Modify `./aaa/buildfile` to make `lib{aaa}` implementation depends on `lib{bbb}`:

From:

```
int_libs = # Interface dependencies.
imp_libs = # Implementation dependencies.
```

To:

```
int_libs = # Interface dependencies.
imp_libs = ../bbb/lib{bbb} # Implementation dependencies.
```

Observed
----------

At this point, building  will result in an error (here with a configuration dir but same issue without):

```
PS G:\test\test-wildcard> b
error: no rule to update ..\build-test-msvc\test-wildcard\bbb\liba{bbb}
  info: re-run with --verbose 4 for more information
  info: while applying rule cxx.link to update ..\build-test-msvc\test-wildcard\aaa\liba{aaa}
  info: while applying rule bin.lib to update ..\build-test-msvc\test-wildcard\aaa\lib{aaa}
  info: while applying rule alias to update ..\build-test-msvc\test-wildcard\dir{aaa\}
  info: while applying rule alias to update ..\build-test-msvc\dir{test-wildcard\}
error: no rule to update ..\build-test-msvc\test-wildcard\bbb\libs{bbb}
  info: re-run with --verbose 4 for more information
  info: while applying rule cxx.link to update ..\build-test-msvc\test-wildcard\aaa\libs{aaa}
  info: while applying rule bin.lib to update ..\build-test-msvc\test-wildcard\aaa\lib{aaa}
  info: while applying rule alias to update ..\build-test-msvc\test-wildcard\dir{aaa\}
  info: while applying rule alias to update ..\build-test-msvc\dir{test-wildcard\}
info: failed to update ..\build-test-msvc\dir{test-wildcard\}
```

This looks like `lib{bbb}` does not "exist" when `lib{aaa}` requirements are processed.
Looking at the content of `test-wildcard/buildfile`:

    ./: {*/ -build/} manifest

We can replace this line by it's more explicit (but less adaptive) equivalent:

    ./: aaa/ bbb/ manifest

Both result in the same error. However if we change the order:

    ./: bbb/ aaa/ manifest

This result in no error and a successful build.

As specified before, I only see this issue on Windows, not on Linux, with and without Powershell.
On linux no such issue appear whatever the order specified in the root buildfile.

**Comment by boris-kolpackov** [comment]
I am not sure why this is order-dependent and only appears on Windows (will let my mind ruminate on this), the problem is really in you `aaa/buildfile`: it has to `include` the `buildfile` of a target it is using. In other words, you need to add something like this:

```
include ../bbb/
```

This, BTW, is discussed in the build system manual.

**Comment by Klaim** [comment]
Yes, that issue was weird enough to lead me several times to misunderstanding (because I'm mostly on windows). I don't understand how that can appen either (assuming build2 tries to know the targets of all subdirectories as a first pass or something similar?), and maybe it's specific to how I setup things, but this report gather what I know right now.

Yes, I discovered this by exploring other ways to refer to targets (see the side effects) when in complex end-user cases. I don't consider this setup a good way to do it. I'll report later about my exploration.

**Comment by boris-kolpackov** [comment]
I wonder if this is still an issue in 0.13.0? Do you think you can re-test?

**Comment by Klaim** [comment]
Good question, I'll check asap but I suspect it disappeared.

**Comment by Klaim** [comment]
After replacing `--subdirectory` by `--source`:

- No error with the original test repro (without `include ../bbb`);
- I tried to force a specific order in the root buildfile: `./: aaa/ bbb/ manifest` and it still work as expected (dependencies are built in the right order) - still no error;

I didn't remark before that the library cxx files are compiled twice (once for shared, once for static by default if I understand correctly), it looks weird in the log because they are the exact same logs.

Other than that it looks like the issue is "fixed".
