### ISSUE TITLE
MSVC toolchain deduction from cl.exe path not working as expected

### ISSUE THREAD

**Issue by kamrann** [build2/build2#205]
MSVC can have multiple side-by-side installations on a machine; further, any given installation can have multiple toolchain versions installed within it. When specifying `config.cxx=path/to/cl.exe`, `build2` will always pick the latest toolchain in the installation containing that `cl.exe`, rather than picking the immediate containing toolchain version. This results in build errors due to incompatibilities between compiler version and STL/runtime versions.

The issue stems from the following line, which is accessing the default (latest) version at a place in the folder structure above the specific toolchains.
https://github.com/build2/build2/blob/33256470a38504a5fcfdf050784efbf0dc93144c/libbuild2/cc/guess.cxx#L643-L645
It seems like in the case where `cl.exe` path has been specified, we can just skip the VS product enumeration entirely and deduce `r.msvc_dir` by dropping `/bin/[host]/[target]/cl.exe` from the full path (`.../VC/Tools/MSVC/14.31.31103/bin/HostX64/x64/cl.exe`)?

If this seems reasonable, let me know and I can create a PR.

**Comment by boris-kolpackov** [comment]
> If this seems reasonable, let me know and I can create a PR.

Thanks for the analysis and the PR offer. I think this makes sense but we will need to look closer, at which point it will probably be easier to just fix it than go through the PR dance.

**Comment by boris-kolpackov** [comment]
The fix is in the latest staged toolchain. It would be great if you can confirm this now works as expected for your case.

**Comment by kamrann** [comment]
Yep, all seems consistent on latest staged.

**Comment by boris-kolpackov** [comment]
Perfect, thanks for the confirmation.
