### ISSUE TITLE
b crash relating to out-of-bounds ad hoc prerequisite access

### ISSUE THREAD

**Issue by kamrann** [build2/build2#207]
This is a bit of an obscure one, but the following (obviously incorrectly formed) ad hoc target causes an access violation in `b`:
```
file{something}: liba{mylib}
{{
  # note incorrect prerequisite index
  x = $cxx.lib_poptions($<[1], exe)
  y = $cxx.lib_libs($<[1], exe, absolute)
  depdb hash $x $y
  diag gen $>
  p = $path($>)
  echo "hello" >$p
}}
```

The function calls themselves don't directly cause a problem, the crash seems to only occur as a result of combining both resulting variables in the `depdb hash`.

**Comment by boris-kolpackov** [comment]
Thanks for the report. This should be fixed in the latest staged toolchain. I was able to reproduce it and confirm the fix so I am closing this issue (but feel free to reopen if there are still problems).
