### ISSUE TITLE
msvc: build2 fail with '__cpp_modules' is reserved 

### ISSUE THREAD

**Issue by wroyca** [build2/build2#210]
I have been using CMake for a long time and I am looking for an alternative for CXX modules. Build2 seems to meet almost all my requirements. It's brilliant. 

Unfortunately, it currently fails with MSVC. This is probably a known issue but I could not see it reflected in the issues board: 

```bash
# Suppress warnings coming from external libraries.
#
cxx.internal.scope = current

# Some compilers (e.g. gcc) require that experimental features be enabled.
#
cxx.std = experimental
cxx.features.modules = true

assert $cxx.features.modules "no modules support for $cxx.signature"

using cxx

mxx{*}: extension = cero

# Assume headers are not importable unless stated otherwise.
#
hxx{*}: cxx.importable = false

# The test target for cross-testing (running tests under Wine, etc).
#
test.target = $cxx.target
```

```bash
C:\Users\wroy\Desktop\cero\cero-std\main.cero: error C2220: the following warning is treated as an error
C:\Users\wroy\Desktop\cero\cero-std\main.cero: error C2220: the following warning is treated as an error
C:\Users\wroy\Desktop\cero\cero-std\main.cero: warning C4117: macro name '__cpp_modules' is reserved, '#define' ignored
C:\Users\wroy\Desktop\cero\cero-std\main.cero: warning C4117: macro name '__cpp_modules' is reserved, '#define' ignored
```

**Comment by Klaim** [comment]
For info, `build2`'s support for MSVC's implementation of C++ modules have been halted some versions ago (because msvc changed their interface) and will be resumed at some point but is not working right now. (see also other issues with the `modules` tag)

That doesn't meant this is not a bug of course, just wanted to clarify that probably the rest of the functionalities will not work until support is resumed.

**Comment by wroyca** [comment]
> For info, `build2`'s support for MSVC's implementation of C++ modules have been halted some versions ago (because msvc changed their interface) and will be resumed at some point but is not working right now. (see also other issues with the `modules` tag)
> 
> That doesn't meant this is not a bug of course, just wanted to clarify that probably the rest of the functionalities will not work until support is resumed.

That's a bummer. Any clue as to what needs to be taken care of, i.e.: can we help?

**Comment by boris-kolpackov** [comment]
> Any clue as to what needs to be taken care of, i.e.: can we help?

We are currently blocked by this bug in MSVC: https://developercommunity.visualstudio.com/t/scanDependencies-does-not-take-into-acc/10029154

But I have an idea of how we can work around that at the expense of not supporting conditional header unit importation.

Other than that, it's a matter of me digging myself out of the current rabbit hole (which is `aarch64` CI support) and getting on with it. Regarding help (thanks for the offer, BTW), it would be good to test things once there is something working. The implementation itself is quite hairy so I am not sure if you want that in your life (but let me know if you are feeling adventurous and has some time on your hands).

**Comment by wroyca** [comment]
> > Any clue as to what needs to be taken care of, i.e.: can we help?
> 
> We are currently blocked by this bug in MSVC: https://developercommunity.visualstudio.com/t/scanDependencies-does-not-take-into-acc/10029154
> 
> But I have an idea of how we can work around that at the expense of not supporting conditional header unit importation.
> 
> Other than that, it's a matter of me digging myself out of the current rabbit hole (which is `aarch64` CI support) and getting on with it. Regarding help (thanks for the offer, BTW), it would be good to test things once there is something working. The implementation itself is quite hairy so I am not sure if you want that in your life (but let me know if you are feeling adventurous and has some time on your hands).

> The implementation itself is quite hairy so I am not sure if you want that in your life (but let me know if you are feeling adventurous and has some time on your hands). 

I do, ping me when time comes! In fact, I'm looking to go all the way with the modules, even if they are more or less experimental at the moment. In my experience, they are quite stable with MSBuild. So much so that I haven't encountered any major problems for a while with them. — But then again, I tend to avoid including headers and prefer to use my own local implementation of the std when I need it, which I think is the way modules were always meant to be used, but alas things are not that simple

**Comment by Klaim** [comment]
> I do, ping me when time comes! In fact, I'm looking to go all the way with modules, even if they are more or less experimental at the moment. In my experience, they are quite stable with MSBuild. So much so that I haven't encountered any major problems for a while with them.

Exactly same here 👍🏽

**Comment by wroyca** [comment]
@boris-kolpackov @Klaim Could you do a quick commit to enable MSVC latest version by removing the definitions and adding /interface? That *should* be enough to enable MSVC modules I believe, something like:

https://github.com/build2/build2/blob/505021d9297fcbc9232f7d5c2de432d5316dad08/libbuild2/cxx/init.cxx#L367-L392

```diff
          case compiler_type::msvc:
            {
-              // While modules are supported in VC 15.0 (19.10), there is a
-              // bug in the separate interface/implementation unit support
-              // which makes them pretty much unusable. This has been fixed in
-              // 15.3 (19.11). And 15.5 (19.12) supports the `export module
-              // M;` syntax. And 16.4 (19.24) supports the global module
-              // fragment. And in 16.8 all the modules-related options have
-              // been changed. Seeing that the whole thing is unusable anyway,
-              // we disable it for 16.8 or later for now.
-              //
-              if ((mj > 19 || (mj == 19 && mi >= (modules.value ? 10 : 12))) &&
-                  (mj < 19 || (mj == 19 && mi < 28) || modules.value))
+            if (mj == 19 && mi >= 34 && o == "/std:c++latest")
             {
-                prepend (
-                  mj > 19  || mi >= 24     ?
-                  "/D__cpp_modules=201810" : // p1103 (merged modules)
-                  mj == 19 || mi >= 12     ?
-                  "/D__cpp_modules=201704" : // p0629r0 (export module M;)
-                  "/D__cpp_modules=201703"); // n4647   (       module M;)
-
-
-                prepend ("/experimental:module");
+               prepend ("/interface");
                modules = true;
              }
              break;
            }

**Comment by Klaim** [comment]
>  That should be enough to enable MSVC modules I believe

I don't think that's true if I follow [the notes I took when I tried to check what's needed and how msbuild does it.](https://github.com/Klaim/cxx20-modules-examples/blob/visualstudio/visualstudio-projects/build2-modules-msvc-notes.md)

For example, `/interface` should only be used on module interface units, not on the other kinds of units, and there are different flags to set. Also the flags to specify where the output of each step should go is different from the previous experimental interface. There is also the special case header units to handle. etc.

(note: I'm not a maintainer of `build2` , so I might be wrong `^^;` AND I cannot push that commit, to be clear - but I could try it locally if I find the time and it's worth it)

Did you try that patch locally already, in your install build dir of `build2` (if you still have it)? See if it does anything right?

**Comment by wroyca** [comment]
> 

I *wanted* to try it out but unfortunately the build steps for Windows are non-existent and given the complexity of [building](https://github.com/build2/HOWTO/blob/master/entries/setup-build2-for-development.md) even on Linux, I was dreading having to convert the equivalent to Windows. That said, I'd be happy to try and experiment with the modules if guidance could be provided for compilation!

**Comment by wroyca** [comment]
> For example, `/interface` should only be used on module interface units, not on the other kinds of units.

That's true, but the interface unit exports either a module or a module partition, which is really all that's needed. I personally find module implementation unit redundant and consider it fine to ignore for now. 😅 

> and there are different flags to set.

This should not be the case **if** build2 correctly detects file extensions as C++ files. The /interface flag will overwrite the compileas flag, so this should be fine.

>  could try it locally if I find the time and it's worth it

If you do ping me! :)

**Comment by wroyca** [comment]
@boris-kolpackov Anything new on this front? I ended up using build2 as my daily driver after all, but I need to cross-compile for MSVC and GCC with modules. I mix build2 with meson to support both sides, but it complicates things a bit. Speaking of, if you were to enable GitHub sponsors, I wouldn't hesitate to fund it — even though I don't have much to offer — should it help speed things up a bit. :)

**Comment by boris-kolpackov** [comment]
> Anything new on this front?

This is planned for the next release and I hope to start looking into this in a few weeks. I will ping this issue with anything to test.

> Speaking of, if you were to enable GitHub sponsors, I wouldn't hesitate to fund it — even though I don't have much to offer — should it help speed things up a bit. :)

Thanks for the offer, but at this stage I suspect setting this up will take more time than it will gain. But we will definitely consider this if/when `build2` becomes more widely used.

**Comment by wroyca** [comment]
> > That should be enough to enable MSVC modules I believe
> 
> I don't think that's true if I follow [the notes I took when I tried to check what's needed and how msbuild does it.](https://github.com/Klaim/cxx20-modules-examples/blob/visualstudio/visualstudio-projects/build2-modules-msvc-notes.md)
> 
> For example, `/interface` should only be used on module interface units, not on the other kinds of units, and there are different flags to set. Also the flags to specify where the output of each step should go is different from the previous experimental interface. There is also the special case header units to handle. etc.
> 
> (note: I'm not a maintainer of `build2` , so I might be wrong `^^;` AND I cannot push that commit, to be clear - but I could try it locally if I find the time and it's worth it)
> 
> Did you try that patch locally already, in your install build dir of `build2` (if you still have it)? See if it does anything right?
>
>> I wanted to try it out but unfortunately the build steps for Windows are non-existent and given the complexity of [building](https://github.com/build2/HOWTO/blob/master/entries/setup-build2-for-development.md) even on Linux, I was dreading having to convert the equivalent to Windows. That said, I'd be happy to try and experiment with modules if guidance could be provided for compilation!

@Klaim  I took the time to figure out how to put together a build2 build by scrambling obscure documents here and there — long story short: Build2 was able to build a small exe with module by passing /interfaces to cxx. That said, it failed to recognize mxx as modules and there were a few false positives during sanity checks. It also failed to locate the ifcs correctly. Potentially because the ifcs were generated in the root directory instead of the build directory. This also caused a linking problem with the entry point but I ran a hacky /ENTRY:main to sweep that out. Partitions, e.g. `import a:b` are not necessary, as one can simply pass `import a.b` to get more or less the same result.  But yes, overall, it was more blocked by build2 sanity check than by the compiler itself. Not too bad so far. :slightly_smiling_face:

**Comment by Klaim** [comment]
> Partitions, e.g. `import a:b` are not necessary

In my opinion, they are very important, necessary and I definitely intend to use them haha! XD (based on my experience with various experiments with modules in msvc)

>  as one can simply pass `import a.b` to get more or less the same result.

That is not at all the same result  `^^;`  : one is a partition of `a`, so only `a`'s primary module interface can have this import line, and code in that partition is only for implementing definitions of module `a` and owned by it, it's quite important distinction. The other is importing a totally separate module (not `a` and not part of `a` either) so any source file can use that import line and `a.b` have no relationship with `a`, they are completely separated modules (dot is not introducing a hierarchy, it's just part of the name). They are not even used the same way nor lead to the same consequences.

But if that hack and only-primary-interface support is enough for you to start, kudos! Personally I need most of the features of modules to work to start anything other than small projects I already experimented modules with. Ideally just supporting what works with msvc (so not everything -there are bugs- but most of the standard features) should be enough for me to start real projects.

**Comment by wroyca** [comment]
> > Partitions, e.g. `import a:b` are not necessary
> 
> In my opinion, they are very important, necessary and I definitely intend to use them haha! XD (based on my experience with various experiments with modules in msvc)
> 
> > as one can simply pass `import a.b` to get more or less the same result.
> 
> That is not at all the same result `^^;` : one is a partition of `a`, so only `a`'s primary module interface can have this import line, and code in that partition is only for implementing definitions of module `a` and owned by it, it's quite important distinction. The other is importing a totally separate module (not `a` and not part of `a` either) so any source file can use that import line and `a.b` have no relationship with `a`, they are completely separated modules (dot is not introducing a hierarchy, it's just part of the name). They are not even used the same way nor lead to the same consequences.
> 
> But if that hack and only-primary-interface support is enough for you to start, kudos! Personally I need most of the features of modules to work to start anything other than small projects I already experimented modules with. Ideally just supporting what works with msvc (so not everything -there are bugs- but most of the standard features) should be enough for me to start real projects.

> But if that hack and only-primary-interface support is enough for you to start, kudos! 
Indeed :


> > Partitions, e.g. `import a:b` are not necessary
> 
> In my opinion, they are very important, necessary and I definitely intend to use them haha! XD (based on my experience with various experiments with modules in msvc)
> 
> > as one can simply pass `import a.b` to get more or less the same result.
> 
> That is not at all the same result `^^;` : one is a partition of `a`, so only `a`'s primary module interface can have this import line, and code in that partition is only for implementing definitions of module `a` and owned by it, it's quite important distinction. The other is importing a totally separate module (not `a` and not part of `a` either) so any source file can use that import line and `a.b` have no relationship with `a`, they are completely separated modules (dot is not introducing a hierarchy, it's just part of the name). They are not even used the same way nor lead to the same consequences.
> 
> But if that hack and only-primary-interface support is enough for you to start, kudos! Personally I need most of the features of modules to work to start anything other than small projects I already experimented modules with. Ideally just supporting what works with msvc (so not everything -there are bugs- but most of the standard features) should be enough for me to start real projects.

Interestingly, this has cleared up some confusion about partitions. From what you've said, they seem to be essentially the equivalent of private/public headers and are generally useful if you're writing modules to be consumed by other projects.

Speaking of MSVC, resharper eap -- and clion now have proper support for module diagnostics (*.ixx), which was the last missing piece for me personally to use them in anything other than small toy projects. I look forward to seeing the same improvement on GCC and CLANG!

> But if that hack and only-primary-interface support is enough for you to start, kudos!

Unfortunately, for those who want to follow the same path, it's not really usable as build2 can't resolve the ifcs by itself for the moment, better to wait for a proper support in what seems to be planned for the 16.0 roadmap ( seeing the milestone )

**Comment by Klaim** [comment]
> Interestingly, this has cleared up some confusion about partitions. From what you've said, they seem to be essentially the equivalent of private/public headers and are generally useful if you're writing modules to be consumed by other projects.

Kind of, if we are talking about interface partition that's kind of the idea but more "hermetic". If we are talking private/implementation partitions, then it's closer to pairing cpp files with definitions/implementations and a header exposing the interface.
You might want to check a complete explanation, though clear ones are not easy to find. Unfortunately the subject is not that as easy as it could have been. `^^;`

**Comment by boris-kolpackov** [comment]
FYI, I am planning to start looking into this next week.

**Comment by wroyca** [comment]
Follow up: https://github.com/build2/build2/issues/333
