### ISSUE TITLE
Wildcard is not expanded if prefixed with "$src_base/"

### ISSUE THREAD

**Issue by helmesjo** [build2/build2#217]
When running `echo $files` in the `testscript` the following will expand the `$src_dir` but the wildcard will remain (so it becomes one string instead of a list of files):
```
./: testscript
{
  files = $src_base/subfolder1/files-*.cpp
}
```
While this creates a list with all the files (but obviously not absolute path):
```
./: testscript
{
  files = subfolder1/files-*.cpp
}
```

```sh
$ b --version
build2 0.16.0-a.0.66e7100be28e
libbutl 0.16.0-a.0.81ec829b96a0
host x86_64-microsoft-win32-msvc14.3
Copyright (c) 2014-2022 the build2 authors.
This is free software released under the MIT license
```

**Comment by Klaim** [comment]
I might be wrong, but I suspect you have to make a group to make the globbing expressions work?
For example:
```
files = $src_base/subfolder1/{files-*.cpp}
```

**Comment by helmesjo** [comment]
> I might be wrong, but I suspect you have to make a group to make the globbing expressions work? For example:
> 
> ```
> files = $src_base/subfolder1/{files-*.cpp}
> ```

Unfortunately that didn't work either:
```
cppfront\testscript:4:25: error: invalid string value 'somename\subfolder\'files-1.cpp
```

**Comment by boris-kolpackov** [comment]
Thanks for the report! Both cases are fixed in the latest staged version.
