### ISSUE TITLE
Git command required by build2 has been removed ('submodule--helper list')

### ISSUE THREAD

**Issue by helmesjo** [build2/build2#221]
After updating to latest git version (2.38.1 / 18 October 2022) I was met by the following error while running `bdep update`:

```
.bpkg/tmp/0aae01e7c52a submodule--helper list
fatal: 'list' is not a valid submodule--helper subcommand
error: unable to list submodules
```

[Some quick googling suggests](https://patchwork.kernel.org/project/git/patch/patch-v3-04.32-10189ba3da7-20220821T130231Z-avarab@gmail.com/) that this subcommand has been removed (commit from a couple of months ago).

**Comment by boris-kolpackov** [comment]
Thanks for the report! This should be fixed in the latest staged version. But let's keep this bug open until the release, in case we need to refer others to it.
