### ISSUE TITLE
Segfault on install with ad hoc install recipe

### ISSUE THREAD

**Issue by helmesjo** [build2/build2#227]
## Reproduce (windows)
1. Extract [zip](https://github.com/build2/build2/files/10066418/build2-install-segfault.zip) and `cd` into folder.
2. Run `b install: ./ config.install.root=./out`
3. Segfault.
    a. See comment in tests buildfile  for another way to make it segfault.

**Comment by boris-kolpackov** [comment]
Fixed in the latest staged toolchain. Thanks for the report and the reproducer!
