### ISSUE TITLE
"Assertion failed: !shared_ || ctx->phase == run_phase::load"

### ISSUE THREAD

**Issue by helmesjo** [build2/build2#229]
Just a little corner case I clipped while playing around, and managed to setup a reproducer so might as well share it.

1. Unpack [this zip](https://github.com/build2/build2/files/10086162/build2-install-bug.zip)
2. `bdep init -C @msvc cc config.cxx=cl` (I only tried with msvc)
3. `b install: ./ !config.install.root=./out`

Might hit a snag or two while installing (if so just run install again), but it should end with this error:
`Assertion failed: !shared_ || ctx->phase == run_phase::load, file C:\build2-build\build2-toolchain-0.16.0-a.0.20221123120638.9412a275a5e4\build2\libbuild2\varia
ble.cxx, line 2076`

```
$ bdep --version
bdep 0.16.0-a.0.59cd10b43f9b
libbpkg 0.16.0-a.0.b67a3e4eaa09
libbutl 0.16.0-a.0.4b3718646a2
```

**Comment by boris-kolpackov** [comment]
Should be fixed in the next staged version. Thanks for the report and the reproducer!
