### ISSUE TITLE
[MSVC] Enable "Standard Conformance" flag by default.

### ISSUE THREAD

**Issue by Klaim** [build2/build2#23]
When compiling C++ by default with `Visual Studio 2017 version 15.5` and higher versions, make build2 use the flag `/permissive-` .

> By default, the /permissive- option is set in new projects created by Visual Studio 2017 version 15.5 and later versions. It is not set by default in earlier versions. 

Source: https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=vs-2019

The minimum version in question is named in Wikipedia:
`MSVC++ 14.12 _MSC_VER == 1912 (Visual Studio 2017 version 15.5)`

That flag looks like a good default for new C++ code and it seems it would be good to match what recent VS versions recommend as default.

Side Note: CMake (v3.14.1) still doesn't use this flag unfortunately, but that might come at some point, see https://gitlab.kitware.com/cmake/cmake/issues/17068

There is also a potential relationship with new experimental features which does not work unless this flag is set, notably `/experimental:concepts` which is not documented at this moment.

(This cause the question: what would one do if they want to remove default flags used by build2?)

**Comment by boris-kolpackov** [comment]
Thanks, I've implemented this and it's available on stage.

> This cause the question: what would one do if they want to remove default flags used by build2?

The standard way to do this is to override it by passing, say, `/permissive` as a custom option (we take care to put default options early in the command line). This, however, doesn't work in all cases (some compilers don't "merge" such multiple options). For such cases we can do manual merging in `build2`.

**Comment by boris-kolpackov** [comment]
Ok, this didn't work out as expected. Currently this flag tends to trigger too many compiler bugs so we can't even build  the `build2` toolchain with it. Here is one example with MSVC 16.0:

```
/home/karen/work/build2/bpkg/bpkg/package-odb.hxx(2031): fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'msc1.cpp', line 1527)
```

So for now let's only enable it if `cxx.std` is `experimental`.

**Comment by Klaim** [comment]
Agreed.

If you didn't already, I'll try to reproduce and report that error to MS.

**Comment by Klaim** [comment]
I confirm that the flag is there in `cxx.std = experiment`.

Still working on the repro case.

**Comment by boris-kolpackov** [comment]
Thanks. I gave up reporting (most) issues to MS due to lack of time. So if you can do it, that would be great. There is another one here: https://github.com/build2/libbutl/commit/d57f8bd933ae6a2ddb2d40994d76edca13fe0314
