### ISSUE TITLE
Windows: deadlock occur when attempting to resolve an empty pkg-config dependency

### ISSUE THREAD

**Issue by wroyca** [build2/build2#236]
The issue at hand is related to https://github.com/build2/build2/issues/235, but differs in that it pertains to a potential deadlock that may occur if build2 attempts to resolve a pkg-config dependency (file) that is empty:

```
"C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32019\bin\Hostx64\x64\link.exe" /LIB /NOLOGO /LIST C:/gnome/lib\cairo.lib
<blinking cursor here>
```

![image](https://user-images.githubusercontent.com/91024200/205971017-00889a4d-34ff-4a5d-988f-a08328684724.png)

build2: 2239b3f57ae4779acd403cb0d0222d3adde1a1ad

**Comment by boris-kolpackov** [comment]
I believe this is now also fixed?

**Comment by wroyca** [comment]
> I believe this is now also fixed?

I haven't had a chance to check, but it should be fine. I'll reopen otherwise
