### ISSUE TITLE
pkg_config: resolution causes thousands of duplicated include entries

### ISSUE THREAD

**Issue by wroyca** [build2/build2#237]
The resolution of pkg_config result in the duplication of include entries, leading to a large number of repeated lines in the output. This can cause unnecessary workloads and make the output difficult to read.

e.g.:

![image](https://user-images.githubusercontent.com/91024200/206870824-07f7f5c1-2322-49b3-8fa4-f75970680cec.png)

![Screenshot from 2022-12-10 13-53-16](https://user-images.githubusercontent.com/91024200/206870888-f8eaac8e-466c-451d-b3ed-4242f211e4ee.png)

![image](https://user-images.githubusercontent.com/91024200/206870880-8734f588-36fd-45f4-aeff-31a21bf98651.png)

[compile_commands.zip](https://github.com/build2/build2/files/10200721/compile_commands.zip)

**Comment by boris-kolpackov** [comment]
I am going to close this in favor of #265 where we have more information.
