### ISSUE TITLE
Linker script option to c and cxx target types

### ISSUE THREAD

**Issue by hazelnusse** [build2/build2#25]
In embedded software development it is essential to write linker scripts that define the memory map of the ram and flash of the target MCU, and where the sections of code and data will be placed in that map. Such a script is typically passed during the final link step using `-Wl,-T=scriptfile` or `-Wl,--script=scriptfile`. For more detail, see:
https://sourceware.org/binutils/docs/ld/Options.html#Options

lld is intended as a drop in replacement for GNU ld / gold and should accept the same command line input as well as the same script file format. Details may be found here:
https://lld.llvm.org/

If unspecified, an implicit linker script is used, typically defined at the time the compiler was built. 

If specified, changes to the linker script should trigger a rebuild of the target library/executable.

I'm not sure this is something that exists in Visual Studio; I couldn't tell from this whether there is such a thing in MSVS:
https://docs.microsoft.com/en-us/cpp/build/reference/link-input-files?view=vs-2019

**Comment by boris-kolpackov** [comment]
While we may want to provide better support for linker scripts at some stage, there is already a generic mechanism for this:

```
  // Prerequisite inclusion/exclusion. Valid values are:
  //
  // false  - exclude.
  // true   - include.
  // adhoc  - include but treat as an ad hoc input.
  //
  // If a rule uses prerequisites as inputs (as opposed to just matching them
  // with the "pass-through" semantics), then the adhoc value signals that a
  // prerequisite is an ad hoc input. A rule should match and execute such a
  // prerequisite (whether its target type is recognized as suitable input or
  // not) and assume that the rest will be handled by the user (e.g., it will
  // be passed via a command line argument or some such). Note that this
  // mechanism can be used to both treat unknown prerequisite types as inputs
  // (for example, linker scripts) as well as prevent treatment of known
  // prerequisite types as such while still matching and executing them (for
  // example, plugin libraries).
```

So, in this specific case, I believe something along these lines should do the trick:

```
exe{foo}: file{script.ld}: include = adhoc
exe{foo}: cc.loptions += -Wl,--script=$src_base/script.ld
```

This should work even if the script is automatically generated as part of the build, say from an `.in` file. For example (notice the change to `out_base`):

```
exe{foo}: file{script.ld}: include = adhoc
exe{foo}: cc.loptions += -Wl,--script=$out_base/script.ld
file{script.ld}: in{script.ld.in}
```

**Comment by hazelnusse** [comment]
Thanks @boris-kolpackov. I see this mentioned in the NEWS file but didn't see anything like this in the manual, though there are hints of it in the end of the Conditions chapter (1.8.2). This does look like it will do what I'm requesting, let me play with it and I'll report any feedback I have here. As long as it works, I think the only to do might be to make such an example more discoverable in the build system manual.

**Comment by hazelnusse** [comment]
Unless I've made some mistake, it seems that modifying the file mentioned in `file{}` and then re-running the `b` does not result in a re-run of the link step, which would be the desired behavior. See:
https://github.com/hazelnusse/blinky/blob/master/blinky/build2file

Maybe I messed something up... it is late :)

**Comment by boris-kolpackov** [comment]
Yes, we have a bit of a bug there: we do make sure ad hoc prerequisites are up to date but we don't take their timestamps into account when deciding whether the target is up to date. Will look into this on the fresh head tomorrow.

**Comment by hazelnusse** [comment]
Awesome, thanks @boris-kolpackov. Where does this logic live in the build2 sources? I'd like to start familiarizing myself.

**Comment by boris-kolpackov** [comment]
This particular logic is a bit spread but you can use the commit (ca0f9c71be279aee845bf5328ac0af8c02c8849e) that fixes the issue to get a sense of the relevant places.

I am going to stage the fixed version in a few hours and will ping this issue when done.

**Comment by boris-kolpackov** [comment]
Staged.

**Comment by hazelnusse** [comment]
I confirm that with build2 0.11.0-a.0.ca0f9c71be27, the issue is resolved. Thanks!

**Comment by boris-kolpackov** [comment]
Thanks for the confirmation. I will look into #24 in the coming days.
