### ISSUE TITLE
Unable to use <algorithm> standard header with g++-13

### ISSUE THREAD

**Issue by gwhitney** [build2/build2#250]
I had a project compiling with g++-12 and tried to switch to g++-13 and obtained a report:
```
error: inconsistent C++ compiler behavior
  info: run the following two commands to investigate
  info: g++-13 -I/home/glen/code/hello-gcc/cplusminus -I/home/glen/code/cplusminus -std=c++23 -finput-charset=UTF-8 -x c++ -MQ ^ -MD -E -fdirectives-only -MF /home/glen/code/hello-gcc/cplusminus/cpm/cxx/cpm.o.t -o /home/glen/code/hello-gcc/cplusminus/cpm/cxx/cpm.o.ii /home/glen/code/cplusminus/cpm/cxx/cpm.cxx
```
With this advice, I was able to recreate a minimal problematic example: a single source file `algoproblem.cxx`
```
#include <algorithm>
int main() { return 0; }
```
When I try to build this program, build2 (in essence) executes `g++-13 -E -fdirectives-only algoproblem.cxx` as one step of the process. However, in g++-13 this fails with error
```
In file included from /usr/include/c++/13/bits/stl_pair.h:60,
                 from /usr/include/c++/13/bits/stl_algobase.h:64,
                 from /usr/include/c++/13/algorithm:60,
                 from algoproblem.cxx:1:
/usr/include/c++/13/type_traits:2948:25: error: missing binary operator before token "("
 2948 |                bool _Nothrow = noexcept(_S_conv<_Tp>(_S_get())),
      |                         ^

```
(This is on an OpenSUSE Tumbleweed system, up to date as of a week ago.)
I have filed https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108244 upstream, but I mention it here as well in case anyone else is having trouble switching to g++-13 or there is a workaround or configuration option to avoid the separate preprocessing step that I could use in the meantime. (Without the `-E -fdirectives-only` option the program compiles fine to an executable that runs correctly.) Thanks for any suggestions.

**Comment by boris-kolpackov** [comment]
Thanks for investigating this and filing a bug with GCC. I can't think of any workaround for this on the `build2` side, unfortunately. If the issue were triggered when compiling the partially preprocessed source, then there is a way to force `build2` to compile from the original source. But this happens when producing the partially preprocessed source itself (and extracting header dependencies while at it). Hopefully the GCC folks will fix this soon.

**Comment by boris-kolpackov** [comment]
Looks like this has been fixed in GCC and so I am going to close this issue. But feel free to reopen if there are still any problems.
