### ISSUE TITLE
[BUG?] Installing with bin.lib=static & linking libs{hello} generates no libhello.shared.pc

### ISSUE THREAD

**Issue by helmesjo** [build2/build2#254]
1. Unzip [build2-install-static-bug.zip](https://github.com/build2/build2/files/10354603/build2-install-bug.2.zip)
2. `bdep init -C @clang cc config.cxx=clang++`
3. `b install: hello/ !config.install.root=./out !config.install.scope=project !config.bin.lib=static`
>install: ../build2-install-bug-clang/libhello/libhello/libhello.shared.pc: No such file or directory
error: process install exited with code 71
  info: command line: install -m 644 ../build2-install-bug-clang/libhello/libhello/libhello.shared.pc out/lib/pkgconfig

Reproduced on MacOS. Haven't tested Windows or Linux.
Make sure to `bdep clean` between runs, otherwise you might get false-positives.
```bash
bdep 0.16.0-a.0.34e232023e8f
libbpkg 0.16.0-a.0.424fcd390192
libbutl 0.16.0-a.0.c6c224a78715
```

**Comment by helmesjo** [comment]
Actually, by dropping the last commit, the same thing happens when linking `lib{hello}` (static):
> install: ../build2-install-bug-clang/libhello/libhello/libhello.pc: No such file or directory

**Comment by helmesjo** [comment]
Note that it is the ad hoc install recipe causing it (so uncommenting that part will make it work), but obviously it doesn't really make sense that it fails to produce the pkgconfig file.

**Comment by boris-kolpackov** [comment]
I believe this is the same underlying issue as described in #253 (and with the same workaround). Here your custom install recipe does not signal to the update rule that things are being built for install, which in turn causes the update rule to omit generating `.pc` files (since they are only needed for install).
