### ISSUE TITLE
Implementation libraries headers are installed

### ISSUE THREAD

**Issue by EmilRosenquist** [build2/build2#258]
## Implementation libraries headers are installed
When installing a library its implementation libraries headers are also installed. I spoke with @boris-kolpackov and he mentioned this is how it works in the current model. But it should probably only install interface libraries headers.

**Comment by Klaim** [comment]
Do you think this a duplicate of https://github.com/build2/build2/issues/147 ?

**Comment by EmilRosenquist** [comment]
@Klaim this is probably a subset of that one yes. Thanks for bringing this to my attention!
I will close this one and refer to #147.

**Comment by Klaim** [comment]
Also feel free to comment there on your interest and give feedback on the potential solutions proposed, and the scope (like if there are other kinds of files that need some ways to not be installed). 👍🏽
