### ISSUE TITLE
Project and variable naming mismatch/confusing error

### ISSUE THREAD

**Issue by kamrann** [build2/build2#273]
According to the docs, project names are allowed to contain '-'. However if I have a package named `my-project`, and add a config variable to `root.build` as follows:
```
config [bool]   config.my-project.variable_name ?= true
```
I'm presented with the confusing error message:
```
error: configuration variable 'config.my-project.variable_name' does not include project name
```

If I rename the variable to use an underscore it seems `build2` is happy even with the project name maintaining the hyphen. So I guess that the behaviour is probably as intended and the issue is just that the error message could stand some improvement in this case.

**Comment by boris-kolpackov** [comment]
Canonical variable names should not include `-` (though you can still assign/expand such variables) so when project name is used in a variable name (`config.<project>.*`, `config.import.<project>`) we replace `-` with `_` in the variable name.

Regarding diagnostics, when I try something like this with a staged toolchain, I get this diagnostics:

```
build/root.build:1:15: error: configuration variable 'config.hello-foo.test' does not include project name
  info: expected variable name in the 'config[.**].hello_foo.**' form
```

And think from the `info` line it should be clear what needs to be fixed. Did you not get this `info` line in your case?

**Comment by kamrann** [comment]
> Did you not get this info line in your case for some reason?
I didn't, however I'm a few months behind latest staged. I'll update the toolchain and verify.

**Comment by kamrann** [comment]
Confirmed, after updating toolchain the error message has the additional info. 👍
