### ISSUE TITLE
Missing tag error for some hyperlinks in build2's man pages

### ISSUE THREAD

**Issue by wroyca** [build2/build2#274]
Previously having to use build2's documentation offline due to a power outage, I found that several hyperlinks in its man pages resulted in an error message indicating a missing tag. One example of this was when I tried to access the config.guess(1) hyperlink within the b - build system driver manual:

![image](https://user-images.githubusercontent.com/91024200/233516415-91ff991a-cf9a-44ce-b33e-425abf810086.png)

**Comment by boris-kolpackov** [comment]
Filling in the blanks: you are using the `b.1` man page and not `b.xhtml`.

Unlike in HTML, we can't know ahead of time if the references to man pages will be resolvable. We just make a references and if you have the man page installed on your system, then I presume it will get resolved. And if not, I guess not. Not much we can do about it.

**Comment by wroyca** [comment]
Fair enough - I presumed that upon installation, all build2 manuals would be included and therefore accessible
