### ISSUE TITLE
bpkg crash when specifying invalid config override

### ISSUE THREAD

**Issue by kamrann** [build2/build2#276]
Just ran into this when messing around with things that I don't understand. No doubt I'm not allowed to do this, but of course it shouldn't crash.
The following will trigger an assertion failure in `bpkg`:
`bdep update --build-option config.foo=true`
```
Assertion failed: configure_ctx->var_overrides.empty (), file C:\build2\build\build2-toolchain-0.16-a.0\bpkg-0.16.0-a.0.20230419112523.abde2515c648\bpkg\pkg-build.cxx, line 5667
error: process bpkg terminated abnormally: aborted
```
`bpkg 0.16.0-a.0.abde2515c648`
`bdep 0.16.0-a.0.87690881f2e0`

**Comment by boris-kolpackov** [comment]
Fixed in https://github.com/build2/bpkg/commit/6a8953c64aaf7cfcd081f0750dcfb9c89aea49e7. Thanks for the report!
