### ISSUE TITLE
bpkg fails to name a fetched package correctly (in some unclear case)

### ISSUE THREAD

**Issue by Klaim** [build2/build2#28]
How to reproduce:
---------------------

(quick version)
1. create an empty configuration using `bpk create`
2. `bpkg build https://github.com/Klaim/klaim-proto-libzmq.git`

Observed:
```
╰─$ bpkg build https://github.com/Klaim/klaim-proto-libzmq.git
added git:github.com/Klaim/klaim-proto-libzmq
fetching git:github.com/Klaim/klaim-proto-libzmq
querying https://github.com/Klaim/klaim-proto-libzmq.git
fetching from https://github.com/Klaim/klaim-proto-libzmq.git
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 27 (delta 1), reused 25 (delta 1), pack-reused 0
Unpacking objects: 100% (27/27), done.
checking out klaim-proto-libzmq/4.3.1-a.0.20190515175606.21e3ebb28e22
querying https://github.com/zeromq/libzmq.git
fetching submodule 'libzmq/origin' from https://github.com/zeromq/libzmq.git
remote: Enumerating objects: 934, done.
remote: Counting objects: 100% (934/934), done.
remote: Compressing objects: 100% (686/686), done.
remote: Total 934 (delta 450), reused 351 (delta 225), pack-reused 0
Receiving objects: 100% (934/934), 1.03 MiB | 2.97 MiB/s, done.
Resolving deltas: 100% (450/450), done.
submodule path 'libzmq/origin': checked out '6b51f033776c821c41dc98150ab92b247f32fa18'
distributing klaim-proto-libzmq/4.3.1-a.0.20190515175606.21e3ebb28e22
error: file ./klaim-proto-libzmq-4.3.1-a.0.20190515175606.21e3ebb28e22/manifest does not exist
```

The error is correct, the file path doesn't exist, so we look in the directory:
```
╰─$ ls                                                                                                           1 ↵
build      libzmq-4.3.1-a.0.20190515175606.21e3ebb28e22
````

We can see that the name of the directory created for the package is `libzmq` instead of `klaim-proto-libzmq` which is the package name, as specified in the package manifest.

Notes:
------- 

 - Cloning locally and using `bdep init -C ` to build the package will succeed.
 - This isssue also appears if one put this repository in the repositories.manifest file of  a project and depends on the package. It might be related only to the dependency-fetching case.
 - I assumed that the name of the package the a problem, but it does seem to be correct relative to https://build2.org/bpkg/doc/build2-package-manager-manual.xhtml#package-name ;
 - I tried to reproduce this issue with a smaller empty prject (made with `bdep new`) but failed so far. For example the same operation with https://github.com/Klaim/build2-package-name succeeds. (it's in an online repo because I first assumed it was a fetching issue in the case of git)
 - Reproduced on Ubuntu and Windows10 with staged versions:

Ubuntu (Ubuntu 18.04.2 LTS):
```
╰─$ b --version
build2 0.11.0-a.0.ca0f9c71be27
libbutl 0.11.0-a.0.422f8cb7e03e
host x86_64-linux-gnu
Copyright (c) 2014-2019 Code Synthesis Ltd
This is free software released under the MIT license.
```

Windows 10:
```
PS G:\work\next\prototypes\build2-examples\build-test> b --version
build2 0.11.0-a.0.c17323cb691a
libbutl 0.11.0-a.0.d57f8bd933ae
host x86_64-microsoft-win32-msvc14.2
Copyright (c) 2014-2019 Code Synthesis Ltd
This is free software released under the MIT license.
```

**Comment by Klaim** [comment]
I've found what triggers the issue: **it's when the package name have been changed in git history**.
For some reason **`b dist` will create a directory with the first package name appearing in the git history**, even if it was changed later and we are at the latest commit which have the new package name. Note that the other operations use the right package name.

To create a repo that reproduce the error:
----------------------------------------------

1. `bdep new libname-is-wrong` then `cd libname-is-wrong`
2. `git add .` then `git commit -m "initial state"`
3. Change the package name in manifest to `libname-is-right`
4. `git add .` then `git commit -m "fixed package name"`

At this point, using `b dist` will result in a distribution with the package name `libname-is-wrong`, while `bdep init` will create a directory `libname-is-right` in the configuration. Example (Windows10/MSVC):

```
PS G:\work\next\prototypes\build2-packages\libname-is-wrong> bdep init -C ../build-test-msvc
initializing in project G:\work\next\prototypes\build2-packages\libname-is-wrong\
created configuration G:\work\next\prototypes\build2-packages\build-test-msvc\ 1 default,forwarded,auto-synchronized
synchronizing:
  new libname-is-right/0.1.0-a.0.20190516150148.9e284cbb6529
PS G:\work\next\prototypes\build2-packages\libname-is-wrong> b dist ..\distribution\
error: unknown root distribution directory
  info: did you forget to specify config.dist.root?
PS G:\work\next\prototypes\build2-packages\libname-is-wrong> b dist config.dist.root=..\distribution\
dist libname-is-wrong-0.1.0-a.0.20190516150148.9e284cbb6529
version.in libname-is-wrong\version.hxx.in
```

**Comment by karen-arutyunov** [comment]
The build2 dist meta-operation doesn't use manifest values for producing distribution directory name. It uses project and version (provided by the version module) variable values. The former is still set to libzmq in build2/bootstrap.build2 file of your project. Setting it to klaim-proto-libzmq fixes the issue.

**Comment by Klaim** [comment]
Thanks, I totally forgot about the project name (and that `import` will look for the project name, not the package name).

**Comment by boris-kolpackov** [comment]
I can't think of any good reason why someone would ever need to have different package and (build system) project names. Plus, we don't really support this anyway. So I've added the check to the `version` module:
 
```
manifest:2:7: error: package name libfoo1 does not match build system project name libfoo
  build/bootstrap.build: info: build system project name specified here
```

**Comment by Klaim** [comment]
Thanks, that will help with this mistake.

I agree it doesn't make much sense, though in doubt I was searching since yesterday night see if there is a situation where it does. The only case I was thinking where maybe it would be useful would be with subprojects but even then allowing them to have a project name would open the door to maybe a quite complex usage.
I think `bdep init` and `b dist` not using the same source for the directory name in the configuration might have triggered other issues and/or confusions but that error report fixes that.
