### ISSUE TITLE
Cyclic dependency detected with ImageMagick

### ISSUE THREAD

**Issue by Plaristote** [build2/build2#283]
Hi !

There seem to be an issue with the cyclic dependency check, when trying to import ImageMagick. Using docker machines, I've tested the issue on several environments:
- build2 0.15 and the latest staging release
- Ubuntu 22.04, Fedora 37, Fedora 38 and ArchLinux
- ImageMagick 6 and 7

The issue only shows up on Ubuntu, with both build2 0.15 and staging, and with either the packager's version (ImageMagick 6), or a custom made build (ImageMagick 7).

The error output looks like this:

```
error: dependency cycle detected involving target /usr/lib/x86_64-linux-gnu/lib{MagickCore-6.Q16}@/usr/bin/g++/
  /usr/lib/x86_64-linux-gnu/pkgconfig/MagickCore-6.Q16.pc: info: while resolving pkg-config dependency -lMagickCore-6.Q16
  /usr/lib/x86_64-linux-gnu/pkgconfig/MagickWand-6.Q16.pc: info: while resolving pkg-config dependency -lMagickCore-6.Q16
  /usr/lib/x86_64-linux-gnu/pkgconfig/Magick++-6.Q16.pc: info: while resolving pkg-config dependency -lMagickWand-6.Q16
  /usr/lib/x86_64-linux-gnu/pkgconfig/Magick++.pc: info: while resolving pkg-config dependency -lMagick++-6.Q16
info: while configuring libcrails-image
```

How to reproduce
--

Here's a Dockerfile that will let you setup an environment where you can safely reproduce the issue:
```Dockerfile
FROM ubuntu:22.04

WORKDIR /tmp
ENV LD_LIBRARY_PATH /usr/local/lib
ENV DEBIAN_FRONTEND "noninteractive"
ENV TZ "Europe/London"

RUN apt-get -y --allow-unauthenticated update && \
    apt-get -y --allow-unauthenticated upgrade && \
    apt-get -y install curl \
  pkg-config \
  build-essential \
  libbz2-dev \
  libssl-dev \
  git

# The package we're going to build needs gcc >= 12
RUN apt-get -y install gcc-12 g++-12
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 90
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 90

COPY build-build2.sh build-build2.sh
RUN bash build-build2.sh

RUN apt-get -y install libboost-all-dev
RUN apt-get -y install libmagick++-dev
```

Here's the build-build2.sh script reference in the dockerfile:
```sh
#!/bin/sh -ex

export BUILD2_VERSION="0.16.0-a.0"
export BUILD2_FINGERPRINT="EC:50:13:E2:3D:F7:92:B4:50:0B:BF:2A:1F:7D:31:04:C6:57:6F:BC:BE:04:2E:E0:58:14:FA:66:66:21:1F:14"

curl -sSfO https://stage.build2.org/0/$BUILD2_VERSION/build2-install-$BUILD2_VERSION-stage.sh
chmod +x build2-install-$BUILD2_VERSION-stage.sh
sh build2-install-$BUILD2_VERSION-stage.sh --yes --trust "$BUILD2_FINGERPRINT"
```

Build the docker machine and start a shell with the following commands:
```sh
docker build -t "issue-reproducer" -f Dockerfile .
docker run --net=host -it --rm "issue-reproducer" bash
```

Lastly, the following commands will reproduce the issue by attempting to build a package that requires ImageMagick:
```sh
bpkg create -d libcrails-image-build cc config.cxx=g++
cd libcrails-image-build
bpkg add "https://github.com/crails-framework/libcrails-image.git#master"
bpkg fetch
bpkg build libcrails-image '?sys:ImageMagick++/*'
```

Workaround
--
To whom it may concern, I've been able to workaround the issue by clearing all the ImageMagick related pkgconfig files, and creating the following Magick++.pc file instead:

```pc
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib64
includedir=/usr/include/ImageMagick-6
includearchdir=/usr/include/x86_64-linux-gnu/ImageMagick-6
libname=Magick++
 
Name: Magick++
Description: Magick++ - C++ API for ImageMagick (ABI Q16HDRI)
Version: 6.0.0
Libs: -L${libdir} -lMagick++-6.Q16 -lMagickWand-6.Q16 -lMagickCore-6.Q16
Libs.private: -L${libdir} -lMagick++-6.Q16 -lMagickWand-6.Q16 -lMagickCore-6.Q16 -lm
Cflags: -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu/ImageMagick-6 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16
```

It's a bit heretical to remove pkgconfig files that were installed by your package manager, and I wouldn't recommend doing that on your own setup: that's why it might be a good idea to perform and package your builds from docker machines when possible.

**Comment by boris-kolpackov** [comment]
I took a look at the `*.pc` files involved from Ubuntu 22.04 and I am pretty sure the culprit is this fragment from `MagickCore-6.Q16.pc`:

```
libname=MagickCore-6.Q16
 
Libs: -L${libdir} -l${libname}
Libs.private: -L${libdir} -l${libname} [...]
```

For some (misguided) reason it lists `-lMagickCore-6.Q16` both in `Libs` and `Libs.private`, even though `Libs.private` is used in combination with `Libs`. We can try to detect and deal with this (I am sure ImageMagic won't be the only one doing this).

**Comment by boris-kolpackov** [comment]
I managed to reproduce this with a small test-case and have implemented a fix, which is now available in the latest staged version of the toolchain. I haven't had a chance to verify it on the `Magic++` library itself, sorry. But if you could give it a try and report back whether there are still any issued, that would be great. Thanks!

**Comment by Plaristote** [comment]
Alright ! I ran a fresh new build with the latest staged version, and I can confirm that there are no more issues when trying to import Magick++ !

Thanks for the help !
