### ISSUE TITLE
FreeBSD C++ Experimental Modules support?

### ISSUE THREAD

**Issue by Norman-Normandy** [build2/build2#284]
New to Build2.

Currently trying to learn it using the examples online. I'm trying to userstand how to get the experimental support for modules working on FreeBSD. I've gotten them to work on Linux following the "Named Modules" [tutorial ](https://build2.org/blog/build2-cxx20-modules-gcc.xhtml#named-modules)fine, but can't say the same on FreeBSD. It only mentions GCC support and not clang so I used GCC12 with G++ the same as my Linux Machine but no luck. I'm using the "hello-module" example "AS IS". and running the command `b config.cxx="g++ -std=c++23"`. many times with `b clean`. 

Normal Output with: `b config.cxx="g++ -std=c++23"`
[log.txt](https://github.com/build2/build2/files/11826372/log.txt)

Verbose Output with: `b config.cxx="g++ -std=c++23" -V`
[logV.txt](https://github.com/build2/build2/files/11826387/logV.txt)

Looking at the logs I assume it's a bug with GCC on FreeBSD. 

This build2-build is built from the Ports Collection. I did build using the normal install method first through the curl shell script and decided to change to the ports version to maybe see a different result. *Different issue but it did take longer to install through the shell script on FreeBSD compared to Linux. Guessing it's single threaded?

**Comment by boris-kolpackov** [comment]
> Looking at the logs I assume it's a bug with GCC on FreeBSD.

Yes, does look like it. Are you able to try GCC 13?

> Different issue but it did take longer to install through the shell script on FreeBSD compared to Linux. Guessing it's single threaded?

Hm, shouldn't be if you have `gmake` and either `nproc` or `sysctl -n hw.ncpu` give the correct result. If that's the case, I would expect the install script with the `--local` option (don't rebuild from packages) to take roughly the same time as from ports. If it's not and you have the log, I would be keen to investigate.

P.S. You don't need to specify `-std=c++23` in `config.cxx` (as can be seen from the logs, `build2` does this automatically based on your project's `cxx.std` value).

**Comment by Norman-Normandy** [comment]
> Are you able to try GCC 13?

I tried G++13 with no luck. Although it does also work on Linux.

> shouldn't be if you have `gmake`

Yeah that's what it was. I installed `gmake` and it built in around 10 minutes. Similar to Linux. Both systems show 6 with nproc in VMs on the same machine.
The normal FreeBSD posix make takes 25 minutes.

These are the simplified logs with timestamps:

For gmake using the command `sudo sh build2-install-0.15.0.sh --local | while IFS= read -r line; do printf '%s %s\n' "$(date)" "$line"; done &> build2-build-log-gmake.txt` 
[build2-build-log-gmake.txt](https://github.com/build2/build2/files/11837434/build2-build-log-gmake.txt)

For make using the command `sudo sh build2-install-0.15.0.sh --local | while IFS= read -r line; do printf '%s %s\n' "$(date)" "$line"; done &> build2-build-log-make.txt`
[build2-build-log-make.txt](https://github.com/build2/build2/files/11837444/build2-build-log-make.txt)

For some reason the normal make one didn't output in a similar way.

**Comment by boris-kolpackov** [comment]
> I tried G++13 with no luck.

If you could submit a report to GCC, that would be helpful (I searched for any existing reports like this, but didn't see anything): https://gcc.gnu.org/bugzilla/

> The normal FreeBSD posix make takes 25 minutes.

For the bootstrap stage we only support `gmake` and if it's not available, then the install script falls back to a serial shell script.

**Comment by Norman-Normandy** [comment]
> If you could submit a report to GCC, that would be helpful (I searched for any existing reports like this, but didn't see anything): 

I'll have to get back to you on that. Since GCC bugzilla "User account creation has been restricted" and requires contact through email. Still to get a response. 

I tried using Linuxulator, Linux Binary Compatibility, to reproduce mapping iostream header to module compilation with G++12 under a complete Ubuntu userland. Oddly enough it gave the exact same error. Which leads me to believe it's a deeper kernel/driver related issue with FreeBSD or GCC and not to do with userspace.

**Comment by boris-kolpackov** [comment]
> I'll have to get back to you on that. Since GCC bugzilla "User account creation has been restricted" and requires contact through email. Still to get a response.

If you don't get a response (or give up on waiting), feel free to paste your bug report here and I will submit it on your behalf (and will add you to the CC list if you include the email).

**Comment by Norman-Normandy** [comment]
> feel free to paste your bug report here and I will submit it on your behalf

[GCC Error.txt](https://github.com/build2/build2/files/11871095/GCC.Error.txt)

GCC 12,13,14 all have compilation errors on FreeBSD when trying to
compile C++ modules on FreeBSD.

When trying to compile iostream using the command: "g++ -std=c++20 -fmodules-ts -xc++-system-header iostream"

GCC throws internal compiler error in exact form:
`
/usr/local/lib/gcc12/include/c++/iostream:77:1: internal compiler error: Segmentation fault
   77 | } // namespace
      | ^
0x825772ff3 ???
        /usr/src/lib/libc/amd64/string/memmove.S:306
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
`

steps to reproduce:
1. Use Freebsd 13.2 or 14.0
2. pkg install gcc-12_5
3. mkdir example && cd example && g++ -std=c++20 -fmodules-ts -xc++-system-header iostream

You should now see a similar segmentation fault error.

the exact version of GCC, as shown by "gcc -v";
`
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc12/gcc/x86_64-portbld-freebsd13.1/12.2.0/lto-wrapper
Target: x86_64-portbld-freebsd13.1
Configured with: /wrkdirs/usr/ports/lang/gcc12/work/gcc-12.2.0/configure --enable-multilib --with-build-config=bootstrap-lto-noplugin --disable-nls --enable-gnu-indirect-function --enable-host-shared --enable-plugin --libdir=/usr/local/lib/gcc12 --libexecdir=/usr/local/libexec/gcc12 --program-suffix=12 --with-as=/usr/local/bin/as --with-gmp=/usr/local --with-gxx-include-dir=/usr/local/lib/gcc12/include/c++/ --with-gxx-libcxx-include-dir=/usr/include/c++/v1 --with-ld=/usr/local/bin/ld --with-pkgversion='FreeBSD Ports Collection' --with-system-zlib --without-zstd --enable-languages=c,c++,objc,fortran,jit --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/man --infodir=/usr/local/share/info/gcc12 --build=x86_64-portbld-freebsd13.1
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 12.2.0 (FreeBSD Ports Collection)
`

**Comment by boris-kolpackov** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110417

You should be able to add yourself to the CC list if you wish. Thanks!

**Comment by boris-kolpackov** [comment]
Ok, I am going to close this as done (bug is in GCC and it has been reported) but feel free to reopen/comment if there is anything we should be doing on our side.
