### ISSUE TITLE
bdep new creation directory differs from documentation

### ISSUE THREAD

**Issue by kamrann** [build2/build2#286]
According to `bdep` docs:

> All the forms except --source first create according to spec a new build2 project/package called name in the name subdirectory of the current working directory (unless overridden with --output-dir|-o).

However, running something along the lines of `bdep new --package -d ../../ -l c++ -t lib libwhatever` results in a package being added at `../../libwhatever` - ie. relative to project root rather than CWD. It appears that I can get the expected behaviour (`./libwhatever`) by simply dropping the `-d` argument; the reason I added it initially was because the following wording gave the impression to me that I needed to specify it if CWD was not the root of the project:
> The --package form adds the new package to the packages.manifest file creating it if necessary. If no project directory is explicitly specified with --directory|-d, then the current working directory is assumed.

Perhaps a clearer wording there would be "then it will be deduced from the current working directory".

**Comment by boris-kolpackov** [comment]
Thanks for pointing this out, I agree it's a bit confusing. I've changed the two paragraphs you quoted to read:

>  All the forms except --source first create according to spec a new build2 project/package called name in the name subdirectory of the current working directory (unless overridden with --output-dir|-o or, in case of --package, with --directory|-d).

> If no project directory is explicitly specified with --directory|-d, then it will be deduced from the current working directory (see bdep-projects-configs(1) for details on specifying projects).

**Comment by kamrann** [comment]
Seems I didn't get around to responding on this, but I think that change addresses the confusion so closing the issue.
