### ISSUE TITLE
Unable to match suffix of explicitly specified header file provided as dependency for binless library in out-of-source build

### ISSUE THREAD

**Issue by lyrahgames** [build2/build2#289]
## Context
Operating System: Arch Linux
```
$ b --version
build2 0.16.0-a.0.2a5eb277bebc
libbutl 0.16.0-a.0.c53d9cfa8872
host x86_64-linux-gnu
Copyright (c) 2014-2023 the build2 authors.
This is free software released under the MIT license.
```

## How to reproduce?
To simplify, I provide [this repo](https://github.com/lyrahgames/build2-binless-lib-test).
Otherwise, please refer to the notes below.
```
$ git clone git@github.com:lyrahgames/build2-binless-lib-test.git build2-test
$ cd build2-test
$ bdep init -C @gcc cc config.cxx=g++
$ b
```

## Observed
```
error: no rule to update ../build2-test-gcc/build2-test/util/hxx{util}
  info: target ../build2-test-gcc/build2-test/util/hxx{util} is implicitly declared in a buildfile
  info: perhaps it should be declared as being in the source tree: hxx{util.hxx}@./ ?
  info: re-run with --verbose=4 for more information
  info: while applying rule cxx.link to update ../build2-test-gcc/build2-test/util/liba{util}
  info: while applying rule bin.lib to update ../build2-test-gcc/build2-test/util/lib{util}
  info: while applying rule build.alias to update ../build2-test-gcc/build2-test/dir{util/}
  info: while applying rule build.alias to update ../build2-test-gcc/dir{build2-test/}
info: failed to update ../build2-test-gcc/dir{build2-test/}
```

## Expected
```
c++ tests/cxx{main} -> tests/obje{main}
ld tests/exe{main}
```

## Notes
Directory Structure:
```
build2-test
├── build
│   ├── bootstrap.build
│   ├── export.build
│   └── root.build
├── buildfile
├── manifest
├── tests
│   ├── build
│   │   ├── bootstrap.build
│   │   └── root.build
│   ├── buildfile
│   └── main.cxx
└── util
    ├── buildfile
    └── util.hxx
```
Here, nearly all the files do not contain any special code and only create a package for a single header-only C++ library.
Only the `util/buildfile` explicitly specifies the header file dependency without its suffix.
```
# util/buildfile
lib{util}: hxx{util}
```
Providing the full name of the file as in the following, lets `build2` run with the expected output.
```
# util/buildfile
lib{util}: hxx{util.hxx.}
```
Maybe this is on purpose, but I assume it to be a bug.
It also might be that I am doing something terribly wrong.
For that, I can also post the full source code in this issue if desired.

**Comment by boris-kolpackov** [comment]
The entire `util/buildfile` from your repository is actually this:

```
lib{util}: hxx{util}
{
  cxx.export.poptions = "-I$src_base"
}

hxx{util}: install = include/
```

And that last line is where the problem lies: you've declared `hxx{util}` as being an output target (all unqualified targets declared in the `buildfile` are by default output, since that's what you normally want, e.g., `lib{util}`). To fix this you need to qualify it as being in the source:

```
hxx{util}@./: install = include/
```

Funny enough, the diagnostics actually suggested this might be the issue and even provided the fix:

```
info: perhaps it should be declared as being in the source tree: hxx{util.hxx}@./ ?
```

**Comment by lyrahgames** [comment]
Thank you for the fast reply!

> And that last line is where the problem lies: you've declared `hxx{util}` as being an output target (all unqualified targets declared in the `buildfile` are by default output, since that's what you normally want, e.g., `lib{util}`). To fix this you need to qualify it as being in the source:
> 
> ```
> hxx{util}@./: install = include/
> ```

Yes, indeed, this solved my issue! Thanks ^^
Sometimes I get confused when switching from patterns to explicitly stated files in unqualified targets.

> Funny enough, the diagnostics actually suggested this might be the issue and even provided the fix:
> 
> ```
> info: perhaps it should be declared as being in the source tree: hxx{util.hxx}@./ ?
> ```

Based on your explanation, I can totally see now that the suggestion was meant for the last line.
However, before I was convinced that it would be the former line causing trouble as changing it resulted in valid code.

I will change my code accordingly and close this issue.
