### ISSUE TITLE
How to handle varying custom build configurations for libraries and their tests?

### ISSUE THREAD

**Issue by lyrahgames** [build2/build2#297]
For many projects, the compilation and execution of tests typically requires additional dependencies, such as unit testing frameworks. According to the [`build2` HOWTOs](https://github.com/build2/HOWTO/blob/master/entries/handle-tests-with-extra-dependencies.md), in such a case, we add another `build2` package to the repository that includes all these tests. So, the repository consists of at least two packages that need to be compiled and run together.

With `build2` version 0.16.0, we are now able to provide multiple named and custom build configurations for each package. This feature is fantastic, but how do I handle different build configurations for libraries and their tests?

For example:
Due to the extra dependencies of the tests, the actual library of the project might be compilable and usable on a lot more platforms than the tests itself. For such a case, I tried to only add a build configuration to the tests itself to constrain their compilation and execution on certain platforms. The platforms incompatible with the tests were completely removed. For those platforms, however, I would at least like to compile and run the basic package. Furthermore, adding custom build configurations to the library, resulted in an override of the configuration of the tests package completely ignoring their constraints.

Can you give any advice how to handle this situation? Maybe the idea of my approach isn't even correct.
Is it allowed for libraries and tests to provide different build configurations?

**Comment by boris-kolpackov** [comment]
The idea behind external tests (i.e., tests factored into a separate package and specified with `tests:` in the main package) is meant to be a very limited extension of having a ` tests/` subproject in the main package itself. So to answer your question you could try to see how you would achieve the same if your tests were in the `tests/ subproject`. In other words, "How do I handle different build configurations for libraries and their tests in the same package"? It should be pretty clear that the answer is "You cannot". But what you could do is omit running tests for some configuration at the build system level (you could even communicate this decision from `manifest` with a configuration variable). And so you could do the same for external tests.

There is also another alternative: turn your external tests package into a complete independent package, that is, without `tests:` in the main package and instead with `depends:` in the tests package. This way you get two completely independent sets of build configurations for the two packages.

**Comment by lyrahgames** [comment]
> The idea behind external tests (i.e., tests factored into a separate package and specified with `tests:` in the main package) is meant to be a very limited extension of having a ` tests/` subproject in the main package itself. So to answer your question you could try to see how you would achieve the same if your tests were in the `tests/` subproject. In other words, "How do I handle different build configurations for libraries and their tests in the same package"? It should be pretty clear that the answer is "You cannot". But what you could do is omit running tests for some configurations at the build system level (you could even communicate this decision from `manifest` with a configuration variable). And so you could do the same for external tests.

Thank you very much for the clarification and advice. This helps a lot.

> There is also another alternative: turn your external tests package into a complete independent package, that is, without `tests:` in the main package and instead with `depends:` in the tests package. This way you get two completely independent sets of build configurations for the two packages.

- There is the problem that when I don't load the `install` module in the tests package then all CI build configs will fail for that package as soon as I declare as a standalone package. That would be one reason for me to not do that.
- From my current perspective, deep testing is only supported for internal tests. Would it be possible to also add external tests packages to deep testing? As external packages are only a limited extension to handle additional dependencies, I can't see any major issues originating from this. What do you think?

**Comment by boris-kolpackov** [comment]
> There is the problem that when I don't load the install module in the tests package then all CI build configs will fail for that package as soon as I declare as a standalone package. That would be one reason for me to not do that.

That would be a bug that we should fix: https://github.com/build2/build2/issues/334

> From my current perspective, deep testing is only supported for internal tests. Would it be possible to also add external tests packages to deep testing? As external packages are only a limited extension to handle additional dependencies, I can't see any major issues originating from this.

Hm, I am not sure I follow. Are you referring to testing dependencies recursively (e.g., `bdep test -i|-r`)? If so do you mean that in this case it would be useful to also run tests in external tests packages of such dependencies?

**Comment by lyrahgames** [comment]
> Hm, I am not sure I follow. Are you referring to testing dependencies recursively (e.g., `bdep test -i|-r`)? If so do you mean that in this case it would be useful to also run tests in external tests packages of such dependencies?

Yes, exactly. This is what I mean.
I referred to the definition of `deep testing` in [the `build2` toolchain introduction](https://build2.org/stage/build2-toolchain/doc/build2-toolchain-intro.xhtml).

**Comment by boris-kolpackov** [comment]
I've created a separate issue for the deep testing aspect: https://github.com/build2/build2/issues/398

Also, if you want to see some advanced examples of various configurations involving external tests, see https://git.codesynthesis.com/cgit/odb/odb/ (make sure you study `manifests` in both `odb-tests` and various `libodb*`).

Other than that, I believe there is nothing else in this issue, so I am going to close it.
