### ISSUE TITLE
build2-install-0.16.0.sh fails on x86_64 Fedora 38

### ISSUE THREAD

**Issue by amurashkin17** [build2/build2#300]
On x86_64 Fedora 38, running

`sh build2-install-0.16.0.sh --yes --trust yes --jobs 1 /opt/build2`

for unknown reason uses `-std=c++23`  and produces produces a bazillion of error messages, starting with [/usr/include/pthread.h](https://github.com/build2/build2/files/12131203/pthread.h.txt) line 480

```
/usr/include/pthread.h:480:33: error: missing terminating " character
  480 |   __attribute_deprecated_msg__ ("\
      |                                 ^~                                                       ^~
```

See few more lines below (full  build log attached - [build2-0.16.0-install-log.zip](https://github.com/build2/build2/files/12134163/build2-0.16.0-install-log.zip))

    218 + build2/b-boot -j 1 config.cxx=g++ config.bin.lib=static build2/exe{b}
    219 warning: g++@/usr/lib64/ccache/g++ looks like a ccache wrapper
    220   info: ccache cannot be used as a C++ compiler
    221   info: use config.cxx to override
    222 warning: gcc@/usr/lib64/ccache/gcc looks like a ccache wrapper
    223   info: ccache cannot be used as a C compiler
    224   info: use config.c to override
    225 version ../libbutl/libbutl/in{version} -> ../libbutl/libbutl/hxx{version}
    226 in libbuild2/in{config} -> libbuild2/hxx{config}
    227 version libbuild2/in{version} -> libbuild2/hxx{version}
    228 in libbuild2/config/in{host-config} -> libbuild2/config/cxx{host-config}
    229 in ../libpkg-config/libpkg-config/in{config} -> ../libpkg-config/libpkg-config/h{config}
    230 version ../libpkg-config/libpkg-config/in{version} -> ../libpkg-config/libpkg-config/h{version}
    231 c++ build2/cxx{b} -> build2/obje{b}
    232 In file included from /usr/include/c++/13/x86_64-redhat-linux/bits/gthr-default.h:35,
    233                  from /usr/include/c++/13/x86_64-redhat-linux/bits/gthr.h:148,
    234                  from /usr/include/c++/13/ext/atomicity.h:35,
    235                  from /usr/include/c++/13/bits/ios_base.h:39,
    236                  from /usr/include/c++/13/ios:44,
    237                  from /usr/include/c++/13/istream:40,
    238                  from /usr/include/c++/13/sstream:40,
    239                  from /home/mur/build2-build/build2-toolchain-0.16.0/build2/build2/b.cxx:4:
    240 /usr/include/pthread.h:480:33: error: missing terminating " character
    241   480 |   __attribute_deprecated_msg__ ("\
    242       |                                 ^~
    243 /usr/include/pthread.h:481:53: error: missing terminating " character
    244   481 | pthread_yield is deprecated, use sched_yield instead");
    245       |                                                     ^~~

Here is relevant [/usr/include/pthread.h](https://github.com/build2/build2/files/12131203/pthread.h.txt) fragment

```c
 #ifdef __USE_GNU
 extern int pthread_yield (void) __THROW;
 # ifdef __REDIRECT_NTH
 extern int __REDIRECT_NTH (pthread_yield, (void), sched_yield)
   __attribute_deprecated_msg__ ("\
 pthread_yield is deprecated, use sched_yield instead");
 # else
 #  define pthread_yield sched_yield
 # endif
```

The first output lines after g++ error messages

```
90632 error: process g++ exited with code 1
90633   info: command line: 
g++ 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 
-DBUILD2_HOST_TRIPLET="x86_64-redhat-linux-gnu" "
-DBUILD2_COPYRIGHT="2014-2023 the build2 authors"" 
-I/home/user/build2-build/build2-toolchain-0.16.0/libbutl 
-I/home/user/build2-build/build2-toolchain-0.16.0/libbutl -DLIBBUTL_STATIC 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 -DLIBBUILD2_STATIC 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 -DLIBBUILD2_BASH_STATIC 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 -DLIBBUILD2_IN_STATIC 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 -DLIBBUILD2_BIN_STATIC 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 -DLIBBUILD2_C_STATIC 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 -DLIBBUILD2_CC_STATIC 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 -DLIBBUILD2_CLI_STATIC 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 -DLIBBUILD2_CXX_STATIC 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 
-I/home/user/build2-build/build2-toolchain-0.16.0/build2 -DLIBBUILD2_VERSION_STATIC 
-Wno-maybe-uninitialized 
-Wno-free-nonheap-object
 -Wno-stringop-overread 
-Wno-dangling-reference 
-std=c++23 
-finput-charset=UTF-8 
-o build2/b.o 
-c 
-x c++ 
/home/user/build2-build/build2-toolchain-0.16.0/build2/build2/b.cxx
```

| Include File/Executable   | Package | Version details
| -                                           | -               | -
| /usr/bin/g++                     | gcc-c++-13.1.1-2.fc38.x86_64 | g++ (GCC) 13.1.1 20230511 (Red Hat 13.1.1-2)
| /usr/include/pthread.h   |  glibc-headers-x86-2.37-4.fc38.noarch

When running with ccache cleared, the build2-install output is the same.

```
ccache --clear
sh build2-install-0.16.0.sh --yes --trust yes --jobs 1 /opt/build2
```

When running without ccache,

```
rpm -e ccache
sh build2-install-0.16.0.sh --yes --trust yes --jobs 1 /opt/build2
```

the build2-install output is the same except few missing warnings

```
warning: g++@/usr/lib64/ccache/g++ looks like a ccache wrapper
   info: ccache cannot be used as a C++ compiler
   info: use config.cxx to override
warning: gcc@/usr/lib64/ccache/gcc looks like a ccache wrapper
   info: ccache cannot be used as a C compiler
   info: use config.c to override
```

**Comment by amurashkin17** [comment]
build2-install-0.15.0.sh also fails. The output does not contain g++ command lines so it is not clear what -std option is used.

BTW When building b-boot it is using `-std=c++1y` but after it switches to` -std=c++23`. Why?

```
37 + gmake -j 1 -f ./bootstrap.gmake CXX=g++ CXXFLAGS=-w
38 g++ -I./../libbutl -I. -DBUILD2_BOOTSTRAP -DBUILD2_HOST_TRIPLET=\"x86_64-pc-linux-gnu\"  -finput-charset=UTF-8 -std=c++1y -w -o build2/b.b.o -c build2/b.cxx
```

**Comment by amurashkin17** [comment]
Hi @wroyca,

Thank you for the advice. In my case, it seems that there are following cache directories related to ccache

- /usr/lib64/ccache
- /var/cache/ccache
- ~/.cache/ccache
- ~/.ccache

Directories /usr/lib64/ccache and /var/cache/ccache were empty. So I deleted ~/.cache/ccache and ~/.ccache.

After it, build2-install-0.16.0.sh completed successfully.

**Comment by amurashkin17** [comment]
It would be nice to have it mentioned in the Installation FAQ.

And maybe build2-install clear cache option or warning if ~/.cache/ccache or ~/.ccache not empty?

**Comment by boris-kolpackov** [comment]
Thanks for the detailed explanation of the problem and the logs. I see `ccache` strikes again, previously: #86.

> Directories /usr/lib64/ccache and /var/cache/ccache were empty. So I deleted ~/.cache/ccache and ~/.ccache.

Hm, this doesn't make sense to me: if `/usr/lib64/ccache/` is empty then it means `/usr/lib64/ccache/g++` is gone and `g++` should presumably resolve to `/usr/bin/g++` which is the real GCC compiler. At which point the presence/contents of `~/.ccache/` should  be irrelevant. In fact, I just tried that on Fedora 38 and it works as expected:

```
$ which g++
/usr/lib64/ccache/g++

$ sh build2-install-0.16.0.sh /tmp/install
# fails with pthread errors

$ sudo dnf remove ccache

$ which g++
/usr/bin/g++

$ sh build2-install-0.16.0.sh /tmp/install
# succeeds without any errors
```

> It would be nice to have it mentioned in the Installation FAQ.

I went ahead and added detection of ccache to the install script (similar to what we already have in `build2` itself). So now the script will fail suggesting either passing `--cxx /usr/bin/g++` or uninstalling ccache. Note that this hasn't been backported to `0.16.0` yet.

**Comment by boris-kolpackov** [comment]
Ok, I've backported the check to the `build2-install-0.16.0.sh` script. The diagnostics looks like this:

```
error: g++@/usr/lib64/ccache/g++ looks like a ccache wrapper
  info: ccache cannot be used as a C++ compiler with build2
  info: specify real C++ compiler path with --cxx
  info: for example, try --cxx /usr/bin/g++
  info: alternatively, you may want to uninstall ccache
```

**Comment by amurashkin17** [comment]
After some testing, I found that it is enough to remove ccache directory from **PATH** environment variable. I have run `build2-install-0.16.0.sh` successfully without --cxx option, with ccache installed.

build2-install can do it automatically. Consider attached patch [build2-install-patch.txt](https://github.com/build2/build2/files/12187433/build2-install-patch.txt).

The modified script removes **cxx_abs** directory from **PATH** and checks for ccache again. If the removal is successful, it prints a warning and continues. 

I have tested the script on my Linux workstation.

For convenience, the patch text is also below.

```patch
--- build2-install-0.16.0.sh	2023-07-27 12:39:36.507928402 -0500
+++ build2-install-0.16.0.sh.new	2023-07-27 14:03:01.865530169 -0500
@@ -588,6 +588,23 @@
   echo "$r"
 }
 
+remove_ccache_from_path ()
+{
+  ccache_dir=${1%/*}
+  new_path=''
+
+  IFS=':'  # split PATH by colon
+  set -- $PATH
+  unset IFS
+
+  for path_dir in "$@"; do
+    case "$path_dir" in
+    "$ccache_dir"|"$ccache_dir"/*) :;;
+    *) new_path=${new_path:+$new_path:}$path_dir;;
+    esac
+  done;
+}
+
 install ()
 {
   if test -z "$idir"; then
@@ -867,14 +884,25 @@
   #
   cxx_abs="$(command -v "$cxx")"
   if test -n "$(echo "$cxx_abs" | sed -n 's#ccache#true#p')"; then
-    diag "error: $cxx@$cxx_abs looks like a ccache wrapper"
+    old_path=$PATH; ccache_cxx_abs=$cxx_abs
+    remove_ccache_from_path "$ccache_cxx_abs"
+    PATH=$new_path
+    new_cxx_abs="$(command -v "$cxx")"
+    if test -n "$(echo "$new_cxx_abs" | sed -n 's#ccache#true#p')"; then
+      PATH=$old_path; cxx_abs_ok=n
+      diag "error: $cxx@$cxx_abs looks like a ccache wrapper"
+    else
+      cxx_abs=$new_cxx_abs; cxx_abs_ok=y
+      diag "warning: using $cxx@$cxx_abs compiler instead of $ccache_cxx_abs"
+    fi
     diag "  info: ccache cannot be used as a C++ compiler with build2"
     diag "  info: specify real C++ compiler path with --cxx"
-    if test "$cxx_abs" != "/usr/bin/g++"; then
+    if test "$ccache_cxx_abs" != "/usr/bin/g++" -a "$new_cxx_abs" != "/usr/bin/g++"; then
       diag "  info: for example, try --cxx /usr/bin/g++"
     fi
-    diag "  info: alternatively, you may want to uninstall ccache"
-    fail
+    diag "  info: alternatively, you may want to remove ccache directories"
+    diag "  info: from PATH or uninstall ccache"
+    if test "$cxx_abs_ok" == "n"; then fail; fi
   fi
 
   # We don't have arrays in POSIX shell but we should be ok as long as none of
```

**Comment by boris-kolpackov** [comment]
Thanks for the suggesting and the patch. Though I feel this is too much "magic" (and also too much code for essentially fixing someone else's bad decision). Another thing to keep in mind is that while removing the `ccache` from `PATH` for the duration of the install script will fix the installation problem, it will still be present when the user tries to use `build2` (because we continue using just `g++` as the compiler). In contrast, both specifying `--cxx /usr/bin/g++` or uninstalling `ccache` will help with the usage, not just installation.

**Comment by boris-kolpackov** [comment]
I think this is as far as we are going to take it for now, so I am going to close this issue.
