### ISSUE TITLE
How to use files with names containing non-ASCII characters?

### ISSUE THREAD

**Issue by lyrahgames** [build2/build2#307]
I try to package the [TinyEXR](https://github.com/syoyo/tinyexr) library. [Here](https://github.com/lyrahgames/build2-tinyexr) you can find the repository and [here](https://ci.cppget.org/@39ba9f94-6343-4d11-baae-ecdb81fa7bef) is an up-to-date CI run. Currently, the library and tests are compiled and run successfully (with a minor warning) on all major platforms except Windows. For Windows, already the configuration step fails with the following error message when trying to access the file `日本語.exr` which is needed for the tests.

```
error: unable to obtain path build\.bpkg\tmp\287c0eba84f6\libtinyexr-tests\data\regression\???.exr permissions: no such file or directory
```
I believe that Windows in contrast to Linux does not use UTF-8 for its file paths and as a result is not able to read the file correctly. But I might be totally mistaken here and would love to get a deeper understanding concerning this issue.

My question is: What is the best way to resolve this issue?

**Comment by boris-kolpackov** [comment]
> My question is: What is the best way to resolve this issue?

Drop or rename this file. Trying to portably distribute files with non ASCII characters to platforms such as Windows is futile.

**Comment by lyrahgames** [comment]
Thank you for the fast reply. I dropped the file from execution and distribution.
