### ISSUE TITLE
Documentation of all available target types

### ISSUE THREAD

**Issue by Hawk777** [build2/build2#309]
I might be missing something, but having browsed [the documentation](https://build2.org/doc.xhtml), I can’t seem to find something that seems pretty foundational: a table or list showing all valid target type strings, what each one means, and what module (if any) it’s defined by.

**Comment by boris-kolpackov** [comment]
Yeah, there is (was) no comprehensive documentation of target types. I took a stab at it and you can view the result in the documentation for the staged version of `build2`:

https://build2.org/stage/build2/doc/build2-build-system-manual.xhtml#targets-types
https://build2.org/stage/build2/doc/build2-build-system-manual.xhtml#module-bin-target-types
https://build2.org/stage/build2/doc/build2-build-system-manual.xhtml#cc-target-types
https://build2.org/stage/build2/doc/build2-build-system-manual.xhtml#c-target-types
https://build2.org/stage/build2/doc/build2-build-system-manual.xhtml#cxx-target-types

**Comment by Hawk777** [comment]
Looks great, thank you!
