### ISSUE TITLE
unactionable/confusing error message when trying to add a local repository

### ISSUE THREAD

**Issue by duarm** [build2/build2#321]
I made a simple local package for a header-only library, it's on gitlab if anyone wants to see it https://gitlab.com/kurenaiz/miniaudio-build2

Then, I tried to add that as a dependency of my project

First I added the repo to `repositories.manifest`
```
: 1
summary: project repository

:
role: prerequisite
location: https://pkg.cppget.org/1/stable

:
role: prerequisite
location: file:///path/to/libminiaudio/
```

then the depends on `manifest`

```
depends: * libminiaudio ^0.11.18
```

and got this error

```
/path/to/my/project/repositories.manifest:10:11: error: missing repository version
  info: repository dir+file:///path/to/my/project/project/
```

which is very confusing, what do I do? What is a repository version, you mean the version of the project inside of it? any docs links? reading the 6.6 Repository List Manifest, there's only 2 optional fields,  6.6.1 min-bpkg-version and  6.6.2 compression, they both do nothing.

Giving up trying to specify the file://, I tried a git:// url

```
...
:
role: prerequisite
location: https://gitlab.com/kurenaiz/miniaudio-build2.git
```

which gave me

```
fetching git:gitlab.com/kurenaiz/miniaudio-build2 (prerequisite of dir:/path/to/my/project/)
querying https://gitlab.com/kurenaiz/miniaudio-build2.git
warning: repository https://gitlab.com/kurenaiz/miniaudio-build2.git has no available packages
  info: consider specifying explicit URL fragment (for example, #master)
...
warning: repository https://gitlab.com/kurenaiz/miniaudio-build2.git has no available packages
  info: consider specifying explicit URL fragment (for example, #master)
error: no package available for dependency libminiaudio of package project [/path/to/my/configuration/]
info: while satisfying project/0.1.0#4 [/path/to/my/configuration/]
```

Then I tried to add the #master, as advised

```
fetching git:gitlab.com/kurenaiz/miniaudio-build2#master (prerequisite of dir:/path/to/my/project/)
querying https://gitlab.com/kurenaiz/miniaudio-build2.git
fetching from https://gitlab.com/kurenaiz/miniaudio-build2.git
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 29 (delta 1), reused 0 (delta 0), pack-reused 0
error: unknown subcommand: `list'
usage: git submodule--helper <command>

error: unable to list submodules
  info: re-run with -v for more information
warning: repository state is now broken and will be cleaned up
  info: run 'bpkg rep-fetch' to update
```

It would help a lot if the errors regarding the build system could give a tip on how to solve, and link the relevant documentation.

**Comment by boris-kolpackov** [comment]
> any docs links? 

That would be: https://build2.org/bpkg/doc/bpkg-repository-types.xhtml

> It would help a lot if the errors regarding the build system could give a tip on how to solve, and link the relevant documentation.

Agree, we've started doing more of this lately (especially linking to documentation). Will try to improve the error messages you have shown for the next release.

> error: unknown subcommand: `list'
> usage: git submodule--helper <command>

This error is odd. Which version of `build2` and `git` are you using?

**Comment by duarm** [comment]
build2 0.15.0
libbutl 0.15.0
host x86_64-linux-gnu
git version 2.41.0

and it's like this
```
:
role: prerequisite
location: https://gitlab.com/kurenaiz/miniaudio-build2.git#master
```

**Comment by karen-arutyunov** [comment]
```
error: unknown subcommand: `list'
usage: git submodule--helper 
```

That should be fixed in `bpkg` 0.16.0 by commit `a97b12a02754`.

**Comment by duarm** [comment]
I'm trying to build the newest version, and I'm getting this

```
build2-toolchain-0.16.0/libpkg-config/libpkg-config/bsdstubs.c:29:1: error: static declaration of ‘strlcpy’ follows non-static declaration
   29 | strlcpy (char* dst, const char* src, size_t siz)
      | ^~~~~~~
In file included from /home/USER/.local/src/build2-build/build2-toolchain-0.16.0/libpkg-config/libpkg-config/stdinc.h:35,
                 from /home/USER/.local/src/build2-build/build2-toolchain-0.16.0/libpkg-config/libpkg-config/bsdstubs.c:17:
/usr/include/string.h:506:15: note: previous declaration of ‘strlcpy’ with type ‘size_t(char * restrict,  const char * restrict,  size_t)’ {aka ‘long unsigned int(char * restrict,  const char * restrict,  long unsigned int)’}
  506 | extern size_t strlcpy (char *__restrict __dest,
      |               ^~~~~~~
/home/USER/.local/src/build2-build/build2-toolchain-0.16.0/libpkg-config/libpkg-config/bsdstubs.c:67:1: error: static declaration of ‘strlcat’ follows non-static declaration
   67 | strlcat (char* dst, const char* src, size_t siz)
      | ^~
```

tried both building myself and the build script,  `Linux 6.4.11-zen1-1-zen x86_64 GNU/Linux`, this is a BSD libc func, i'm not on bsd, maybe missing a _DEFAULT_SOURCE?

**Comment by boris-kolpackov** [comment]
> same problem on `Linux 6.4.11-zen1-1-zen x86_64 GNU/Linux`

Which Linux distribution/libc is this?

What is happening here is that `libpkg-config` provides its own implementations of some BSD string functions for platforms that don't provide them (like Linux with glibc). It appears that your libc provides them and `libpkg-config` doesn't handle that.

**Comment by duarm** [comment]
glibc 2.38-3
Artix Linux

**Comment by boris-kolpackov** [comment]
> glibc 2.38-3

Thanks, this is most likely related to [glibc adding `strlcpy()`, etc in version 38] (https://sourceware.org/git/?p=glibc.git;a=commit;h=454a20c8756c9c1d55419153255fc7692b3d2199). Will look into dealing with that and will ping you when there is something to test.

**Comment by boris-kolpackov** [comment]
@duarm Ok, I have a fix in a branch (https://github.com/build2/libpkg-config/commit/063f62f13028a0c1549a5ca8743298e8e477bd10) and if you still have `build2` 0.15.0 around and could confirm it works for you, that would be helpful:

```
git clone -b glibc-strl --depth=1 https://github.com/build2/libpkg-config.git
b test: libpkg-config/
```

**Comment by duarm** [comment]
I do not unfortunately, tried to manually patch libpkg-config/ from the install script, but it's not working, same error, even If I define HAVE_STRLCAT in config.h

**Comment by boris-kolpackov** [comment]
Ok, I believe all the  issues mentioned in this report are now fixed so I am going to close this.
