### ISSUE TITLE
Unable to build build2 with glibc 2.38

### ISSUE THREAD

**Issue by duarm** [build2/build2#324]
Both strlcat and strlcpy are now part of glibc, the problem occurs because [libpkg-config](https://github.com/build2/libpkg-config) defines both on some platforms.

For tracking the issue https://github.com/build2/build2/issues/321#issuecomment-1689557051

**Comment by boris-kolpackov** [comment]
> [...] tried to manually patch `libpkg-config/` from the install script, but it's not working, same error, even If I define `HAVE_STRLCAT` in `config.h`, it's probably a configuration problem tho, it should be working.

The install script by default (unless `--local` is specified) will build `libpkg-config` twice: once from local version (which you have patched) to build the bootstrap binary and another from package (which doesn't have the patch). So I think there is a good chance that that's what you are seeing.

In any case, I've applied this fix to the staged version of the toolchain and you can try that without any patching: https://build2.org/community.xhtml#stage

**Comment by duarm** [comment]
tried to build with the stage script in a clean folder, same problem with both strlcpy and strlcat

```
/home/USER/.local/src/build2-build/build2-toolchain-0.17.0-a.0.20230824062823.a344f8afc00a/libpkg-config/libpkg-config/bsdstubs.c:29:1: error: static declaration of ‘strlcpy’ follows non-static declaration
   29 | strlcpy (char* dst, const char* src, size_t siz)
      | ^~~~~~~
```

**Comment by boris-kolpackov** [comment]
> I've confirmed and the patches are there, don't think it worked

Yeah, I think I know what it is: we need to include a header that defines the `__GLIBC*__` macros (`<features.h>`). I've fixed this some more and restaged, can you give it another try (i.e., re-download the install script, etc).

Thanks for your patience in sticking with this!

**Comment by duarm** [comment]
it works! Thanks for fixing it

**Comment by hrantsp** [comment]
Hello everyone, I'm having the same problem with the same version running on Ubuntu 24.04 (x86_64).

Can anyone, please, help me with this?

Thanks in advance.

```
build2-toolchain-0.16.0/libpkg-config/libpkg-config/bsdstubs.c:29:1: error: static declaration of ‘strlcpy’ follows non-static declaration
   29 | strlcpy (char* dst, const char* src, size_t siz)

      | ^~~~~~~
build2-toolchain-0.16.0/libpkg-config/libpkg-config/bsdstubs.c:67:1: error: static declaration of ‘strlcat’ follows non-static declaration
   67 | strlcat (char* dst, const char* src, size_t siz)
      | ^~~~~~~

```

**Comment by boris-kolpackov** [comment]
The release that will fix this is a few weeks away. In the meantime I suggest that you use the latest staged version: https://build2.org/community.xhtml#stage

**Comment by hrantsp** [comment]
Thank you for the reply, Boris. 

Succeded with the latest staged version. Good luck to your team for the next release.
