### ISSUE TITLE
GCC Module Mapper implementation

### ISSUE THREAD

**Issue by Arthapz** [build2/build2#347]
Hi there, i'm a contributor of XMake build system C++20 module support
we have an implementation of C++20 module mapper with file based API, but i find this API poorly designed and tricky to use
so i want to try the server based API
i see you have implemented this, but i don't understand how it work exactly inside your build process can i have some precision on how it is implemented if possible ? do you use sockets or pipes ? the module mapper server is a thread of build2 ? an external process ? and is it really better than file based API ?
sorry if it isn't the right place to ask this

**Comment by boris-kolpackov** [comment]
> can i have some precision on how it is implemented if possible

I can give you an overview but only if you send your questions to the appropriate place (either the slack channel or the mailing list; see https://build2.org/community.xhtml#help). Issues are for reporting issues, not for asking questions.
