### ISSUE TITLE
Preprocessing error if source has lines beginning with # inside R"( ... )"

### ISSUE THREAD

**Issue by good770326** [build2/build2#348]
```c++
#include <iostream>
int main()
{
	std::cout << R"(
		# Hello!
	)";
	return 0;
}
```
build2 builds the source code like this will treating lines beginning with # as preprocessor instructions and raising an invalid preprocessor instruction error('# Hello' here). But it can be compiled by pure g++ command (I found that 'g++ -E -fdirectives-only'  can also cause this problem). The problem should occurred when build2 does a first pre-processing pass before the compilation. Therefore, it may be difficult to solve in short or require compiler development to solve it.
It does seem that such code is very rare, I just encountered it in the official unit test of toml11 library. I have temporarily bypassed it by manually modifying the source code to splice strings line by line.

**Comment by boris-kolpackov** [comment]
This is a GCC bug that has been fixed since GCC 11.
