### ISSUE TITLE
Unexpected warning about unused config variable on bdep init

### ISSUE THREAD

**Issue by kamrann** [build2/build2#352]
Given a default initialized single package project `libhello` with the following additions:

```
# build/root.build
config [bool] config.libhello.debug ?= false
```
```
# libhello/buildfile
if $config.libhello.debug
{
	info "!!! Debug mode enabled !!!"
	cxx.poptions += "-DLIBHELLO_DEBUG"
}
```
Invoking `bdep init -C ../build/msvc @msvc cc config.cxx=cl config.libhello.debug=true` yields
```
initializing in project C:\build2-projects\libhello\
..\build\msvc\build\config.build: warning: dropping no longer used variable config.libhello.debug
  info: variable value: 'true'
created configuration @msvc C:\build2-projects\build\msvc\ 8 target default,forwarded,auto-synchronized
synchronizing:
  new libhello/0.1.0-a.0.19700101000000
```
Note that in the [discussion thread](https://cpplang.slack.com/archives/CDJ0Z991S/p1703147055219549) it seemed others encountered further problems, but in my testing despite the warning the configuration seemed to subsequently behave as expected, ie. I could proceed with `bdep sync config.libhello.debug=true`:
```
synchronizing:
  reconfigure libhello/0.1.0-a.0.19700101000000
    config.libhello.debug=true (user configuration)
libhello\buildfile:17:2: info: !!! Debug mode enabled !!!
```
Also note that if instead configuration creation and project initialization were separated, everything behaved as expected from the start.
`bdep config create ../build/msvc @msvc cc config.cxx=cl` then `bdep init @msvc config.libhello.debug=true`:
```
initializing in project C:\build2-projects\libhello\
synchronizing:
  new libhello/0.1.0-a.0.19700101000000
    config.libhello.debug=true (user configuration)
libhello\buildfile:17:2: info: !!! Debug mode enabled !!!
```

**Comment by boris-kolpackov** [comment]
> ```
> bdep init -C ../build/msvc @msvc cc config.cxx=cl config.libhello.debug=true
> ```

When `bdep-init` is both creating a new configuration and initializing a package, the configuration variable can be attributed to either the created configuration or to the package. Because of that you need to use the `--` separator to distinguish the two cases; see `bdep-init(1)` synopsis: https://build2.org/bdep/doc/bdep-init.xhtml

This variant does the right thing for me:

```
bdep init -C ../build/msvc @msvc cc config.cxx=cl -- config.libhello.debug=true
```

**Comment by kamrann** [comment]
That makes sense, and indeed the documentation is quite clear. 
There were some other similar issues people were having in the discussion thread, but since nothing has been added here, I'll close and if anyone has found a further repro of config problems they can re-open or create a new issue.
