### ISSUE TITLE
clang 'rc' or 'git' version numbers are not parsed correctly

### ISSUE THREAD

**Issue by DimitryAndric** [build2/build2#360]
While doing some preparation work for merging clang 18 into FreeBSD, I ran into a failure building the devel/build2 port. What appears to happen is that build2 cannot handle the version declared by the clang binary in the base system, which is (at this point):

```text
FreeBSD clang version 18.1.0rc (https://github.com/llvm/llvm-project.git llvmorg-18-init-18361-g22683463740e)
```

It appears `build2::cc::guess_clang` skips over all words except the last one (`llvmorg-18-init-18361-g22683463740e)`) and then fails to parse that string as a version. It then dies with:

```text
error: unable to extract Clang minor version from '18'
  info: use config.cxx.version to override
```

What I find a little strange is that `guess_clang` does not seem to look for the "version" word at all. Normally, the version directly follows that word. But apparently it goes over all words in the version string, and considers the first one that contains only digits and a dot as a candidate.

However, git versions of clang are typically marked `18.0.0git`, while release candidates such as the current rc1 are marked `18.1.0rc`. Maybe it is a bit overkill to also support these syntaxes, because when the final release is done the suffix is removed, and it will become a regular 3 piece decimal number with dots again.

In any case I would like your opinion on whether it is better to pass explicit `config.cxx.version` in such cases, or whether the version parser in `guess_clang` can be improved?

**Comment by kamrann** [comment]
Also ran into this recently when attempting to build `build2` project with source-built clang `main` branch. Worked around with `config.cxx.version`, but from memory @Klaim saw same thing but mentioned he had not run into it previously, suggesting possible recent change to either clang version format, or `build2` parsing?

**Comment by boris-kolpackov** [comment]
Thanks for the report. Keeping up with compiler version format "innovations" is unfortunately part of the job. If only they separated `rc`/`git` with something sensible like `-` (and thus kept the version parsable as semver). I did a bit of digging in the LLVM repository and the only bit of "documentation" I could find on this is this comment in `bump-version.py`:

```
        # LLVM_VERSION_SUFFIX should be set to -rcX or be blank if we are
        # building a final version.
```

So it sounds like it should be `-rc` (and hopefully `-git` by analogy) but apparently not. In any case, let's hope the only two possible such suffixes are `git` and `rc`, which appears to be the case for now. BTW, Debian appears to be "fixing up" the version, which is the reason why I haven't hit this earlier:

```
Debian clang version 18.1.0 (rc1-1)
```

I've fixed this in master (the commit is mentioned above). I think the best option on your side would be to apply this patch to the port until the next release is out.

> What I find a little strange is that guess_clang does not seem to look for the "version" word at all.

It probably did originally but a decade of experiences like this one transformed it into what it looks like now. Off the top of my head I see a couple of reasons:

1. We try to handle Clang flavors (for now Apple and Emscripten but potentially others in the future) and some of them don't see the need for this word. For example:

    ```
    emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.6 ()
    ```

2. The word "version" can be translated. This is not a problem on UNIX-like operating systems where we run the compiler with `LC_ALL=C` but we also use this code on Windows. Maybe there is a way to achieve an equivalent result there but experience tells me we will spend another decade cleaning out corner cases in that logic.

Let me know if there any issues with the fix.

**Comment by DimitryAndric** [comment]
Thanks, this appears to work fine:

```text
cxx build2-toolchain@/wrkdirs/share/dim/ports/devel/build2/work/build2-toolchain-0.16.0/
  cxx        c++@/usr/bin/c++
  id         clang
  version    18.1.0
  major      18
  minor      1
  patch      0
  signature  FreeBSD clang version 18.1.0rc (https://github.com/llvm/llvm-project.git llvmorg-18-init-18361-g22683463740e)
  checksum   5cb3f8e2099713cea9d89934a2bad9e2a201603d13cf2e9ab054d0af46150e70
  target     x86_64-freebsd15.0 (x86_64-unknown-freebsd15.0)
  runtime    libgcc
  stdlib     libc++
  c stdlib   freebsd
  hdr dirs
    /usr/local/include/
    --
    /usr/include/c++/v1/
    /usr/lib/clang/18/include/
    /usr/include/
  lib dirs
    /usr/local/lib/
    --
    /usr/lib/clang/18/
    /usr/lib/
LC_ALL=C clang -v
```

**Comment by DimitryAndric** [comment]
I submitted https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=276785 to fix the FreeBSD port for the time being.

**Comment by v-fox** [comment]
On Gentoo with clang+libcxx as system-wide default, clang version is reported as "`22.1.8+libcxx`", so this also breaks build. As workaround I had to use something like this in an ebuild:
```bash
	export CC_VER=""
	if [[ "$(tc-getCC)" == "gcc" ]]; then
		export CC_VER="$(gcc-fullversion)"
	elif [[ "$(tc-getCC)" == "clang" ]]; then
		export CC_VER="$(clang-fullversion)"
	fi
…
	emake -C build2 -f bootstrap.gmake \
		AR="$(tc-getAR)" \
		RANLIB="$(tc-getRANLIB)" \
		LD="$(tc-getLD)" \
		CC="$(tc-getCC)" \
		CXX="$(tc-getCXX)" \
		CXXFLAGS="${CXXFLAGS}" \
		LDFLAGS="-fuse-ld=$(tc-getLD) ${LDFLAGS}"

	edo build2/b/b-boot -V -j "$(makeopts_jobs)" \
		config.build2_toolchain.build.readonly=true \
		config.cxx="$(tc-getCXX)" \
		config.cxx.id="$(tc-getCC)" \
		config.cxx.version="${CC_VER}" \
		config.cxx.coptions="${CXXFLAGS}" \
		config.cxx.loptions="${LDFLAGS}" \
		config.c="$(tc-getCC)" \
		config.c.id="$(tc-getCC)" \
		config.c.version="${CC_VER}" \
		config.cc.coptions="${CFLAGS}" \
		config.cc.loptions="-fuse-ld=$(tc-getLD) ${LDFLAGS}" \
		config.bin.ar="$(tc-getAR)" \
		config.bin.ranlib="$(tc-getRANLIB)" \
		config.bin.lib=static \
		build2/b/exe{b}

	edo mv build2/b/{b,b-boot}
…
	edo build2/b/b-boot -V configure \
		config.cxx="$(tc-getCXX)" \
		config.cxx.id="$(tc-getCC)" \
		config.cxx.version="${CC_VER}" \
		config.cxx.coptions="${CXXFLAGS}" \
		config.cxx.loptions="-fuse-ld=$(tc-getLD) ${LDFLAGS}" \
		config.c="$(tc-getCC)" \
		config.c.id="$(tc-getCC)" \
		config.c.version="${CC_VER}" \
		config.cc.coptions="${CFLAGS}" \
		config.cc.loptions="-fuse-ld=$(tc-getLD) ${LDFLAGS}" \
		config.bin.ar="$(tc-getAR)" \
		config.bin.ranlib="$(tc-getRANLIB)" \
		config.bin.lib=shared \
		…
```

In the end, it still failed though:
```
/var/tmp/portage/dev-build/build2-0.18.1/work/build2-toolchain-0.18.1/build2/libbuild2/cc/pkgconfig-libpkgconf.cxx:231:9: error: no matching function for call to 'call_pkgconf_client_new'
  231 |         call_pkgconf_client_new (&pkgconf_client_new,
      |         ^~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/dev-build/build2-0.18.1/work/build2-toolchain-0.18.1/build2/libbuild2/cc/pkgconfig-libpkgconf.cxx:25:1: note: candidate template ignored: failed template argument deduction
   25 | call_pkgconf_client_new (pkgconf_client_t* (*f) (H, void*),
      | ^
/var/tmp/portage/dev-build/build2-0.18.1/work/build2-toolchain-0.18.1/build2/libbuild2/cc/pkgconfig-libpkgconf.cxx:34:1: note: candidate template ignored: failed template argument deduction
   34 | call_pkgconf_client_new (pkgconf_client_t* (*f) (H, void*, P),
      | ^
1 error generated.
error: process clang++ exited with code 1

```

**Comment by boris-kolpackov** [comment]
> On Gentoo with clang+libcxx as system-wide default, clang version is reported as "22.1.8+libcxx", so this also breaks build.

Ok, will take a look, thanks for the report. By this rate we will soon accept any string as a Clang version...

> In the end, it still failed though:

You seem to be trying to use external `libpkgconf` (instead of bundled `libpkg-config`) and have `config.build2.libpkgconf=true` somewhere in those `...`. Looks like they (`libpkgconfg` maintainers) broke backwards-compatibility again. We've stated that we will not be doing anything about it if they do it again so the only option is to switch to `libpkg-config`, which is generally a good idea since `libpkgconf` is buggy as hell. For background and details, see: https://lists.build2.org/archives/users/2024-June/001117.html
