### ISSUE TITLE
Expected behaviour of `bdep deinit` of a dependency

### ISSUE THREAD

**Issue by kamrann** [build2/build2#363]
In attempting (and so far failing) to reproduce various errors I'm encountering in my project in a simple repro, I have however run into a different and very easily reproduced error. I feel it's a bug, but at this point I'm second-guessing myself on everything.

```
> bdep new -t empty hello
> cd hello
> bdep new --package -l c++ -t lib libhello
> bdep new --package -l c++ -t exe hello
> cd hello
> echo 'depends: libhello' >> manifest
> cd ..
> bdep config create -@msvc ../out/msvc cc config.cxx=cl
> bdep init -d hello
> bdep init -d libhello
> bdep deinit -d libhello
error: package hello is not found in dir:path/to/hello or its complements
```

Surely it should be possible to get back to the state prior to when `libhello` was explicitly initialized (where only `hello` was initialized and `libhello` was a dependency)?

**Comment by boris-kolpackov** [comment]
There were some changes in this logic recently and with the latest staged toolchain the last command succeeds with this diagnostics:

```
deinitializing in project /tmp/hello/
fetching dir:/tmp/hello
synchronizing:
  unhold libhello
```

Translation: `libhello` was not dropped (because `hello` still depends on it) but was unheld, meaning as soon as it has no more dependents, it will be dropped:

```
$ bdep deinit -d hello
deinitializing in project /tmp/hello/
synchronizing:
  drop hello
  drop libhello
```

Feels like works correctly now?

**Comment by boris-kolpackov** [comment]
Ok, lacking further feedback I am going to close this issue. But feel free to reopen/comment if there are still problems in this area.

**Comment by kamrann** [comment]
Apologies, I recall reading this and intending to test but just haven't had time. From your explanation though it certainly sounds resolved, will report back if I run into continued problems.
