### ISSUE TITLE
Installer crashes GCC under SLURM

### ISSUE THREAD

**Issue by esiefker** [build2/build2#374]
I cannot install build2 in my HPC environment using SLURM. 

When I run the installer in the scheduler environment, it completes normally.  
When I try to take advantage of the HPC resources using srun, it crashes

```

g++ -I./../libbutl -I. -DBUILD2_BOOTSTRAP -DBUILD2_HOST_TRIPLET=\"x86_64-pc-linux-gnu\"  -finput-charset=UTF-8 -std=c++1y -w -o libbuild2/token.b.o -c libbuild2/token.cxx
In file included from /nebraska/inbre/gcc-11/include/c++/11/chrono:41,
                 from ./../libbutl/libbutl/process.hxx:12,
                 from ./../libbutl/libbutl/pager.hxx:10,
                 from build2/b.cxx:9:
/nebraska/inbre/gcc-11/include/c++/11/limits:1676:7: internal compiler error: Illegal instruction
 1676 |       max() _GLIBCXX_USE_NOEXCEPT { return __FLT_MAX__; }
      |       ^~~
In file included from /nebraska/inbre/gcc-11/include/c++/11/chrono:41,
                 from /nebraska/inbre/gcc-11/include/c++/11/mutex:39,
                 from ./libbuild2/types.hxx:36,
                 from ./libbuild2/token.hxx:7,
                 from libbuild2/token.cxx:4:
/nebraska/inbre/gcc-11/include/c++/11/limits:1676:7: internal compiler error: Illegal instruction
 1676 |       max() _GLIBCXX_USE_NOEXCEPT { return __FLT_MAX__; }
      |       ^~~
0xcb198f crash_signal
 
```

I'm guessing that this is related to the scheduler using Sandy Bridge CPUs while the SLURM environment uses Haswell.
However, setting -march in CFLAGS seems to be ignored by the installer.  

I am not sure that this is not a configuration problem with my environment, but I do have a supported compiler so I'd imagine this is intended to work.  Any tips would be appreciated.

**Comment by boris-kolpackov** [comment]
I am not familiar with SLURM but the error you are getting seems to indicate that the GCC binary that is used by the install script cannot be executed due to an illegal instruction. Trying to run it on hardware that is older than what it was built for would explain that. To me this suggests that it's a configuration problem in your environment.

You could try to compile a simple program which perhaps includes `<chrono>` and see if you get the same error.

**Comment by boris-kolpackov** [comment]
I am going to close this issue since it doesn't look like our bug and there is no further feedback to indicate otherwise. But feel free to reopen/comment if you think that's not the case.
