### ISSUE TITLE
OpenSSL v3.2+ x509 warns about reading from stdin without -in

### ISSUE THREAD

**Issue by mkrupcale** [build2/build2#379]
OpenSSL v3.2+ `x509` now [1] warns [2,3] when reading a certificate from `stdin`, causing several of the `bpkg` tests to fail during the build on Fedora 40+:

```
bpkg-0.16.0/tests/rep-info.testscript:314:3: error: bpkg-0.16.0/bpkg/bpkg unexpectedly writes to stderr
  info: stderr: bpkg-0.16.0/tests/test/rep-info/cert/email/stderr
Warning: Reading certificate from stdin since no -in or -new option is given
Warning: Reading certificate from stdin since no -in or -new option is given
  info: test id: rep-info/cert/email
  info: while testing bpkg-0.16.0/dir{tests/}
  info: while testing dir{bpkg-0.16.0/}
```

The fix on Linux at least can be adding `-in /dev/stdin` to the `openssl x509` arguments in `bpkg/auth.cxx`, although I don't know how other platforms indicate the `stdin` file.

[1] https://github.com/openssl/openssl/commit/611ef4f3737cc5812bdefe381403fdf1bacfba06
[2] https://github.com/openssl/openssl/blob/611ef4f3737cc5812bdefe381403fdf1bacfba06/apps/x509.c#L733
[3] https://github.com/openssl/openssl/blob/0e89b396197f75993c8d64c07b4af6aa2d97e2af/apps/x509.c#L760

**Comment by boris-kolpackov** [comment]
Previously: https://github.com/build2/build2/issues/353

Note that reportedly OpenSSL folks have fixed this (though not sure in which version) but it appears the version(s) with the warning got deployed wide enough to cause issues. So let's see if we can apply the `/dev/stdin` hack.

**Comment by boris-kolpackov** [comment]
Fixed for Unix in https://github.com/build2/bpkg/commit/40bb034f57cf37c1cbdcef337733507c230c6004. Seems to help our CI builds.

**Comment by mkrupcale** [comment]
Thanks for the quick fix, this fixed the Fedora builds as well [1,2].

[1] https://koji.fedoraproject.org/koji/taskinfo?taskID=116842153
[2] https://koji.fedoraproject.org/koji/taskinfo?taskID=116842154
