### ISSUE TITLE
build2 0.16.0 failed to build against pkgconf 2.2.0

### ISSUE THREAD

**Issue by chenrui333** [build2/build2#381]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
c @/private/tmp/build2-20240328-5067-1iejv6/build2-toolchain-0.16.0/libsqlite3/test/
    c          clang@/opt/homebrew/Library/Homebrew/shims/mac/super/clang
    id         clang-apple
    version    16.0.1
    major      16
    minor      0
    patch      1
    variant:
      version  15.0.0 (clang-1500.3.9.4)
      major    15
      minor    0
      patch    0
      build    (clang-1500.3.9.4)
    signature  Apple clang version 15.0.0 (clang-1500.3.9.4)
    checksum   139c5a9c7a9dd4e88f5d5c4e8d2ef534aae16[972](https://github.com/Homebrew/homebrew-core/actions/runs/8476812431/job/23226924697#step:3:973)4911381c373666ca09e334ff
    target     aarch64-apple-darwin23.4.0 (arm64-apple-darwin23.4.0)
    runtime    compiler-rt
    stdlib     apple
    hdr dirs
      /opt/homebrew/include/
      /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers/
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include/
      /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/
    lib dirs
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/
  error: library expected in ''
    info: while parsing pkg-config --libs /opt/homebrew/opt/pkgconf/lib/pkgconfig/libpkgconf.pc
    info: while applying rule cxx.link to configure updating /private/tmp/build2-20240328-5067-1iejv6/build2-toolchain-0.16.0/build2/libbuild2/cc/libus{build2-cc.?}
    info: while applying rule cxx.link to configure updating /private/tmp/build2-20240328-5067-1iejv6/build2-toolchain-0.16.0/build2/libbuild2/cc/exe{lexer.test.?}
    info: while applying rule config.alias to configure updating /private/tmp/build2-20240328-5067-1iejv6/build2-toolchain-0.16.0/build2/libbuild2/dir{cc/}
    info: while applying rule config.alias to configure updating /private/tmp/build2-20240328-5067-1iejv6/build2-toolchain-0.16.0/build2/dir{libbuild2/}
    info: while applying rule config.alias to configure updating /private/tmp/build2-20240328-5067-1iejv6/build2-toolchain-0.16.0/dir{build2/}
    info: while applying rule config.alias to configure updating /private/tmp/build2-20240328-5067-1iejv6/dir{build2-toolchain-0.16.0/}
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/8476812431/job/23226924697
relates to Homebrew/homebrew-core#167330

**Comment by boris-kolpackov** [comment]
Thanks for the report. The actual error from the build logs:

```
  error: library expected in ''
    info: while parsing pkg-config --libs /opt/homebrew/opt/pkgconf/lib/pkgconfig/libpkgconf.pc
    info: while applying rule cxx.link to configure updating /private/tmp/build2-20240328-5067-1iejv6/build2-toolchain-0.16.0/build2/libbuild2/cc/libus{build2-cc.?}
    info: while applying rule cxx.link to configure updating /private/tmp/build2-20240328-5067-1iejv6/build2-toolchain-0.16.0/build2/libbuild2/cc/exe{lexer.test.?}
    info: while applying rule config.alias to configure updating /private/tmp/build2-20240328-5067-1iejv6/build2-toolchain-0.16.0/build2/libbuild2/dir{cc/}
    info: while applying rule config.alias to configure updating /private/tmp/build2-20240328-5067-1iejv6/build2-toolchain-0.16.0/build2/dir{libbuild2/}
    info: while applying rule config.alias to configure updating /private/tmp/build2-20240328-5067-1iejv6/build2-toolchain-0.16.0/dir{build2/}
    info: while applying rule config.alias to configure updating /private/tmp/build2-20240328-5067-1iejv6/dir{build2-toolchain-0.16.0/}
```

Seeing that this is triggered after upgrading to a new version of `pkgconf`, my guess is that they broke backwards-compatibility again, which they have done several times in the past and which was one of the reasons why we forked the library as https://github.com/build2/libpkg-config. By default `build2` uses `libpkg-config` but when I submitted the Homebrew formula for `build2` I was instructed to switch to `pkgconf`. I warned that this decision will likely cause issues down the road and I guess it now has.

I am not sure what is the preferred course of action here from the Homebrew's POV. The easiest would probably be to switch to `libpkg-config` in the `build2` formula but I am not sure if this is acceptable in the already published version. FWIW, we will remove support for `pkgconf` in the upcoming `build2` release since we only [promised](https://lists.build2.org/archives/users/2022-July/001000.html) to support it until they break us again.

**Comment by boris-kolpackov** [comment]
@mkrupcale FYI, you will likely have the same issue once Fedora upgrades to `pkgconf` 2.2.0.

**Comment by mkrupcale** [comment]
> @mkrupcale FYI, you will likely have the same issue once Fedora upgrades to `pkgconf` 2.2.0.

Thanks for the heads up. Looks like they also bumped the `SOVERSION` and reworked the solver, but it's not clear from their tests what they changed on the output at least of their CLI [1].

[1] https://github.com/pkgconf/pkgconf/compare/pkgconf-2.1.0...pkgconf-2.2.0

**Comment by boris-kolpackov** [comment]
FYI, we have bundled the contents of `libpkg-config` (our fork of `libpkgconf`) with `libbutl` (the `build2` utility library). While we will support the use of `libpkgconf` for `0.17.0` (in the same way as it's done for `0.16.0`), we will remove it in `0.18.0`.

Note also that the use of `libpkg-config` vs `libpkgconf` is not merely a matter of broken backwards compatibility or bugs: in our fork we have also removed the fixed size limit on the `.pc` variable values. This was unlikely to cause issues until now but this is likely to start changing as C++20 modules become usable (e.g., in Clang). The reason is that we store the module interface to file name mapping in a `.pc` variable for installed libraries and that can easily blow through the `libpkgconf`'s limit.

**Comment by mkrupcale** [comment]
> Note also that the use of `libpkg-config` vs `libpkgconf` is not merely a matter of broken backwards compatibility or bugs: in our fork we have also removed the fixed size limit on the `.pc` variable values

Have you tried to work with upstream to remove this limit upstream? Having a fork of `libpkgconf` which can produce `pc` files that are only usable with this fork defeats the purpose of distributed `pc` files.

> This was unlikely to cause issues until now but this is likely to start changing as C++20 modules become usable (e.g., in Clang). The reason is that we store the module interface to file name mapping in a `.pc` variable for installed libraries and that can easily blow through the `libpkgconf`'s limit.

Aren't there specific formats being proposed for this purpose [1,2]? And then there's also the Common Package Specification [3] effort attempting to replace both `pc` and CMake `export`ed `target`s, although I don't know if that's really going anywhere.

[1] https://wg21.link/P1689
[2] https://wg21.link/P2977
[3] https://cps-org.github.io/cps/index.html

**Comment by boris-kolpackov** [comment]
> Have you tried to work with upstream to remove this limit upstream?

We have tried to work with upstream in the past but after multiple frustrating experiences (multiple breakages of backwards compatibility without any apparent concern for the consequences, general lack of attention to details which frequently results in bugs, etc) we have given up -- life is too short (you can find a few links to the "evidence" on https://github.com/build2/libpkg-config).

> Having a fork of `libpkgconf` which can produce `pc` files that are only usable with this fork defeats the purpose of distributed `pc` files.

It's a bit more nuanced than that. Firstly, neither `libpkgconf` nor its `libpkg-config` fork produce `.pc` files, they only parse them. The entity that actually produces them in this case is `build2` itself. It also produces two sets: the first (e.g., `libfoo.pc`) is the basic/common version which doesn't contain any of the additional metadata and can be parsed by any of the `pkg-config` implementations and should be sufficient for a typical header-based C/C++ library. The second set (e.g., `libfoo.static.pc`, `libfoo.shared.pc`) is the "extended" version which contains the extra metadata (as you can see from the names, it is extended in ways other than containing potentially large variable values).

> Aren't there specific formats being proposed for this purpose ... although I don't know if that's really going anywhere.

Yes, there are some proposals that are progressing through the WG21 at snail pace (if at all; though CPS is fairly new and not exactly a WG21 effort, so it remains to be seen). So we had a choice: either wait for these efforts to deliver something usable or to extend the `.pc` file format (which provides an easy way to do it via variables) and actual deliver something that works today and gain some experience based on that. having said that, if any of the above efforts deliver something tangible and there is adoption, then we will definitely consider supporting it.

**Comment by boris-kolpackov** [comment]
We've completed the transition to a private copy of our fork in `0.17.0` so I am going to close this issue.
