### ISSUE TITLE
Packages mixing C and C++ now fail to build on MSVC with the latest staged toolchain

### ISSUE THREAD

**Issue by wroyca** [build2/build2#383]
Specifically, build2 will exit with:
```
gnu99 is not supported by Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33523 for x64
```

This could be related to recent changes introduced with: https://github.com/build2/build2/commit/d228d6e33b460be975ac0a0325a94a7f3307c0e2

#### Example with GLFW:
Previously:
[x86_64-microsoft-win32-msvc14.3](https://cppget.org/glfw/3.3.8/log/x86_64-microsoft-win32-msvc14.3/windows_10-msvc_17.6/default/public/0.16.0)

Now:
[x86_64-microsoft-win32-msvc14.3](https://ci.stage.build2.org/@06ee2efa-d41e-4537-80cb-e536ed0a2717/glfw/3.3.8/log/x86_64-microsoft-win32-msvc14.3/windows_10-msvc_17.9/default/stage/0.17.0-a.0.20240522061717.f31928131b3e/configure)

#### Example with ImGUI:

Previously:
https://github.com/build2-packaging/imgui/actions/runs/9066711426/job/25299457368

Now:
https://github.com/build2-packaging/imgui/actions/runs/9066273752/job/24909480123

**Comment by boris-kolpackov** [comment]
The change in `build2` you refer to tightened the `c.std` check for MSVC which seems to uncover a few broken packages. If you think about it, the new diagnostics is correct: the package requests C99 with the GNU extensions and that cannot be provided by MSVC.

I searched the repository for any other cases like this and it seems there are only two packages that suffer from this:

```
[public/1/stable/lua/lua-5.4.3.tar.gz:lua-5.4.3/build/root.build]:c.std = gnu99
[public/1/stable/lua/lua-5.4.2.tar.gz:lua-5.4.2/build/root.build]:c.std = gnu99
[public/1/stable/lua/lua-5.4.0.tar.gz:lua-5.4.0/build/root.build]:c.std = gnu99
[public/1/stable/lua/lua-5.3.5+2.tar.gz:lua-5.3.5+2/build/root.build]:c.std = gnu99
[public/1/testing/lua/lua-5.4.3+2.tar.gz:lua-5.4.3+2/build/root.build]:c.std = gnu99

[public/1/stable/glfw/glfw-3.3.6+1.tar.gz:glfw-3.3.6+1/build/root.build]:c.std = gnu99
[public/1/stable/glfw/glfw-3.3.7.tar.gz:glfw-3.3.7/build/root.build]:c.std = gnu99
[public/1/stable/glfw/glfw-3.3.4+1.tar.gz:glfw-3.3.4+1/build/root.build]:c.std = gnu99
[public/1/stable/glfw/glfw-3.3.8.tar.gz:glfw-3.3.8/build/root.build]:c.std = gnu99
[public/1/stable/glfw/glfw-3.3.5.tar.gz:glfw-3.3.5/build/root.build]:c.std = gnu99
```

I believe the correct way forward is to fix this in the packages in question with a revision. I will file the issues.

**Comment by boris-kolpackov** [comment]
Both packages have now fixed the issue and the revisions are available on cppget.org.
