### ISSUE TITLE
Some (erroneous) uses of '/' character in buildfile crashes b

### ISSUE THREAD

**Issue by kamrann** [build2/build2#396]
```
//cxx.poptions += "-Dfoo"
```

The above (entered forgetting correct `buildfile` comment syntax) appears sufficient to crash `b`. A single forward slash has the same result.

```
$ bdep update -v
C:\build2\installed\bin\bpkg -v build -d C:\Coding\modules_test\out_b2\clang --no-fetch --no-refinement --no-private-config 125 --noop-exit 124 --configure-only --keep-out --plan synchronizing: --yes reachable@C:\Coding\modules_test\reachable
C:\build2\installed\bin\bpkg -v update -d C:\Coding\modules_test\out_b2\clang reachable
C:\build2\installed\bin\b -v update('C:\Coding\modules_test\reachable\')
error: process b terminated abnormally: aborted
```

**Comment by wroyca** [comment]
Can't reproduce on Fedora 40

**Comment by kamrann** [comment]
Interesting. Yeah should have mentioned I'm on Windows. It did seem surprising that something so easy to do would cause a crash, so I guess it's Windows-specific.

**Comment by kamrann** [comment]
Just to add a little more info.

As @wroyca mentions this seems to crash on Windows only, but I suspect there is some issue in the parsing that applies regardless of platform. It seems on Fedora the same cases simply get ignored, but I suspect should probably be producing an error.

It seems to be specific to the case where one or more '/'s precede what otherwise looks like a variable assignment. In those cases, while Windows crashes, Fedora simply proceeds with no diagnostic and no observable effects. The behaviour difference seems to stem from the fact that for some reason it's attempting to parse the line as a path (https://github.com/build2/build2/blob/master/libbuild2/parser.cxx#L1763), which results in an exception being thrown on Windows specific to the '/' prefix and this exception appears to be uncaught. I'm not in a position to debug it on Fedora so not sure what it's doing, but evidently it's accepted and I guess it shouldn't be.

**Comment by boris-kolpackov** [comment]
Fixed, thanks for narrowing it down to the specific line. (There is a comment a couple of lines above it that explain what kind of construct being parsed, if you want to understand what's going on.)
