### ISSUE TITLE
Will other languages be supported?

### ISSUE THREAD

**Issue by certik** [build2/build2#4]
I couldn't find this answer in the FAQ (https://build2.org/faq.xhtml). Is `build2` meant only for compiling C++ code, or would it also work for Fortran (which also has modules) or other compiled languages, such as Go or Rust?

**Comment by boris-kolpackov** [comment]
Yes, `build2` is not language specific. Its build model is general enough to handle any DAG-based operations and its package/project dependency management can be used for any language. For example, in the last release we have added the [`bash` build system module](file:///home/boris/work/build2/build2/doc/build2-build-system-manual.xhtml#module-bash) which implements modularization support for `bash` scripts. And there is the [`libbutl.bash` package](https://cppget.org/libbutl.bash) that uses it. So in a sense `build2` is already multi-lingual.

So it should be possible to support the languages you have listed (and if not, then we will need to fix that).

**Comment by certik** [comment]
@boris-kolpackov thank you, that is very interesting.
