### ISSUE TITLE
Windows: `b install` deletes DLL symlinks from configuration (`0.17.0`)

### ISSUE THREAD

**Issue by helmesjo** [build2/build2#400]
When running `b install` it removes the symlinked DLLs. This appears to be new behavior introduced in recent versions as we did not experience this behavior a few weeks ago.

Looking at the verbose output one can see it explicitly being removed:
`rmdir -r C:\Users\fho\git\tmp\hello-msvc\hello\hello\hello.exe.dlls\`

**Edit1:** See `b install --verbose 4` log [here](https://github.com/user-attachments/files/16028158/b-install-log.txt).
**Edit2:** `0.16.0` appears to have the same behavior (but we only ever noticed it just now, suggesting it could be something that changed on Windows side).

## Reproducer

**Copy paste this** into `x64 Native Tools Command Prompt for VS 2022`:

```bash
bdep new -t exe hello && cd hello
(
echo : 1
echo summary: hello project repository
echo.
echo :
echo role: prerequisite
echo location: https://pkg.cppget.org/1/stable
echo trust: 70:64:FE:E4:E0:F3:60:F1:B4:51:E1:FA:12:5C:E0:B3:DB:DF:96:33:39:B9:2E:E5:C2:68:63:4C:A6:47:39:43
)>repositories.manifest
(
echo : 1
echo name: hello
echo version: 0.1.0-a.0.z
echo language: c++
echo summary: hello C++ executable
echo license: other: proprietary ; Not free/open source.
echo description-file: README.md
echo url: https://example.org/hello
echo email: hello@mail.com
echo depends: ^* build2 ^>^= 0.16.0
echo depends: ^* bpkg ^>^= 0.16.0
echo depends: libhello ^^1.0.0
)>manifest
(
echo libs =
echo import libs += libhello%libs{hello}
echo.
echo exe{hello}: {hxx ixx txx cxx}{**} $libs testscript
echo.
echo cxx.poptions =+ "-I$out_root" "-I$src_root"
)>hello/buildfile
bdep init -C @msvc cc config.cxx=cl && bdep update
dir hello\hello.exe.dlls
b install: hello/ !config.install.root=../hello-install
dir hello\hello.exe.dlls
 
```
</details>

**Comment by boris-kolpackov** [comment]
I don't think it's a new behavior and I don't think it's a bug: `b install` runs the `update-for-install` pre-operation which rebuilds targets to be installed in way suitable for installation. For exacutables, this means relinking without automatic `-rpath` on POSIX and without the DLL assembly business that emulates it on Windows. If you think about it, it should make sense: you don't want an executable that ends up in, say, `/usr/bin/` to reference shared libraries in `~fred/`. While technically we don't need to remove the directory with DLL symlinks (but we do need to re-link the executable without the manifest that references this directory), we probably do it for good measure and to avoid any confusion.

If you want the executable that was installed to be runnable from the build again, then you will need to update it (which will cause its relink with `-rpath`/DLL assembly).
