### ISSUE TITLE
Feature tests like CMake's check_include_file

### ISSUE THREAD

**Issue by SirNate0** [build2/build2#404]
Does build2 have any comparable feature's to CMake's [check_include_file](https://cmake.org/cmake/help/latest/module/CheckIncludeFile.html#module:CheckIncludeFile) and related tests? E.g. those used by SDL all over [this file](https://github.com/libsdl-org/SDL/blob/40ed098ce8a0a4583250fa24b34f2045264a6d33/cmake/sdlchecks.cmake#L865)? If not, how would one implement something similar (e.g. how would one build SDL with build2)?

**Comment by karen-arutyunov** [comment]
The recommended way to deal with this is by adding the corresponding check to the [libbuild2-autoconf module](https://github.com/build2/libbuild2-autoconf) using the same approach as in the already existing checks. But there is a way to check for system headers in build2 by using [$\<module>.find_system_header()](https://github.com/build2/build2/blob/master/libbuild2/cc/functions.cxx#L297-L305) function, where the `<module>` can be either `c` or `cxx` (with potentially different results). 

You can find more details in the following thread in the [#build2](https://build2.org/community.xhtml#help) channel on Slack: https://cpplang.slack.com/archives/CDJ0Z991S/p1712758112177769

**Comment by boris-kolpackov** [comment]
Also see https://github.com/build2/libbuild2-autoconf/issues/67

I am going to close this issue since it's more of a question (which, BTW, are better to ask in other places: https://build2.org/community.xhtml#help).
