### ISSUE TITLE
build2 installation: bpkg - parsing of curl's output (HTTP response headers)

### ISSUE THREAD

**Issue by Replic4tor** [build2/build2#407]
Hi all, i'm trying to install build2 with the command `sh build2-install-0.17.0.sh`.
After a whole lot of output, the installation fails when libbutl is downloaded:
```
[...]
+ bpkg-stage add https://pkg.cppget.org/1/alpha
added pkg:cppget.org/alpha
+ bpkg-stage --fetch-timeout 600 fetch
fetching pkg:cppget.org/alpha
warning: authenticity of the certificate for repository pkg:cppget.org/alpha cannot be established
certificate is for **cppget.org, "Code Synthesis" <admin@cppget.org>
certificate SHA256 fingerprint:
70:64:FE:E4:E0:F3:60:F1:B4:51:E1:FA:12:5C:E0:B3:DB:DF:96:33:39:B9:2E:E5:C2:68:63:4C:A6:47:39:43
trust this certificate? [y/n] y
fetching pkg:cppget.org/beta (complements pkg:cppget.org/alpha)
fetching pkg:cppget.org/testing (complements pkg:cppget.org/beta)
fetching pkg:cppget.org/stable (complements pkg:cppget.org/testing)
1187 package(s) in 4 repository(s)
+ bpkg-stage -j 16 --fetch-timeout 600 build --for install --yes --plan= build2/0.17.0 bpkg/0.17.0 bdep/0.17.0
  new libbutl/0.17.0 (required by bdep, bpkg, build2, libbpkg)
  new build2/0.17.0
  new libbpkg/0.17.0 (required by bdep, bpkg)
  new bpkg/0.17.0
  new bdep/0.17.0
libbutl-0.17.0.tar.gz:
################################################################################################# 100,0%
error: checksum mismatch for libbutl 0.17.0
  info: pkg:cppget.org/alpha has b05a9a11feacdab17561c663c3927aa18e689793db3bdbf2e8db1e2a3aef4efb
  info: fetched archive has 7439286db9b960a4d48fb4ecb14bacf9eeadfe4f9e56b032fd051f9c65db05e9
  info: consider re-fetching package list and trying again
  info: if problem persists, consider reporting this to the repository maintainer
```

Executing the bpkg-stage command with `-v` gave me the curl command used to download the file, which is:
`curl -L -A "bpkg/0.17.0 (GNU/Linux; +https://build2.org/) libbpkg/0.17.0 libbutl/0.17.0 curl" --max-time 600 -i https://pkg.cppget.org/1/alpha/build2/libbutl-0.17.0.tar.gz`

Computing the SHA256 hash from the result gives me:
```
$ curl -L -A "bpkg/0.17.0 (GNU/Linux; +https://build2.org/) libbpkg/0.17.0 libbutl/0.17.0 curl" --max-time 600 -i https://pkg.cppget.org/1/alpha/build2/libbutl-0.17.0.tar.gz -o - | sha256sum 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2970k  100 2970k    0     0  3540k      0 --:--:-- --:--:-- --:--:-- 3536k
fd45115bb99979435cc0607dbf7198ec289452cf695a4f27729c76f0a82b2daa  -
```

When I remove the `-i` argument from the curl invocation (from the manpage: "Include  the HTTP response headers in the output."), the hash is computed as follows:
```
$ curl -L -A "bpkg/0.17.0 (GNU/Linux; +https://build2.org/) libbpkg/0.17.0 libbutl/0.17.0 curl" --max-time 600 https://pkg.cppget.org/1/alpha/build2/libbutl-0.17.0.tar.gz -o - | sha256sum 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2970k  100 2970k    0     0  4154k      0 --:--:-- --:--:-- --:--:-- 4154k
b05a9a11feacdab17561c663c3927aa18e689793db3bdbf2e8db1e2a3aef4efb  -
```

This second hash matches the one from [https://cppget.org/libbutl/0.17.0](https://cppget.org/libbutl/0.17.0)  and the one bpkg-stage outputs (`info: pkg:cppget.org/alpha has b05a9a11feacdab17561c663c3927aa18e689793db3bdbf2e8db1e2a3aef4efb`).
As far as I understand, the response header is included in the downloaded file which results in a different hash, which is then detected by bpkg-stage and results in the failure of the installation.

The curl version used is:
```
$ curl -V
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

The attached file [libbutl-0.17.0.tar.gz](https://github.com/user-attachments/files/16234752/libbutl-0.17.0.tar.gz) is produced by the following command:
`$ curl -L -A "bpkg/0.17.0 (GNU/Linux; +https://build2.org/) libbpkg/0.17.0 libbutl/0.17.0 curl" --max-time 600 -i -O https://pkg.cppget.org/1/alpha/build2/libbutl-0.17.0.tar.gz`

I'm sitting behind my company's proxy. A wild guess: The `Proxy-Agent` field causes some issues?
The response header contains the following:
```
$ head -n 12 libbutl-0.17.0.tar.gz 
HTTP/1.1 200 Connection Established
Proxy-Agent: Zscaler/6.2

HTTP/1.1 200 OK
Date: Mon, 15 Jul 2024 12:45:19 GMT
Server: Apache/2.4.25 (Debian)
Last-Modified: Tue, 18 Jun 2024 12:39:09 GMT
ETag: "2e697e-61b295e434717"
Accept-Ranges: bytes
Content-Length: 3041662
Content-Type: application/x-gzip
```

At this point I want to thank you for the whole build2 project! I'm already converting my private projects to build2 (which solves a lot of the problems I had with CMake and git/hg subrepos), and I'm currently evaluating if it could be used at my company, too.
Thumbs up, too, for the great documentation. Despite a rather steep learning curve, it's a great introduction that addresses exactly my problems/scenarios.
And thanks to @karen-arutyunov for replying so fast on the #build2 Slack channel and for nudging me to open this bug here on Github.

**Comment by karen-arutyunov** [comment]
Thanks for the report and for kind words!

It turns out that the curl's output may include the CONNECT response from the HTTP proxy besides the response from the HTTP server, which we don't handle properly.

**Comment by karen-arutyunov** [comment]
Since the CONNECT response appears in the curl's stdout I believe that curl proxies the HTTP request explicitly. 

@Replic4tor, could you check if any of the following variables are set in your environment:

http_proxy
https_proxy
HTTPS_PROXY
all_proxy
ALL_PROXY

**Comment by Replic4tor** [comment]
Oh, I could have mentioned this before, sorry.
You are exactly right, see the following output. As you may have guessed from the previous output, zscaler is in use.

```
$ env | grep -i proxy
no_proxy=localhost,127.0.0.1
ftp_proxy=http://gateway.zscloud.net:9481
https_proxy=http://gateway.zscloud.net:10402
NO_PROXY=localhost,127.0.0.1
FTP_PROXY=http://gateway.zscloud.net:9481
HTTPS_PROXY=http://gateway.zscloud.net:10402
HTTP_PROXY=http://gateway.zscloud.net:10402
http_proxy=http://gateway.zscloud.net:10402
```

**Comment by boris-kolpackov** [comment]
Ok, the fix is staged. It would be great if you could give the [staged version of `build2`](https://build2.org/community.xhtml#stage) a try to confirm everything works in your environment. Thanks!

**Comment by Replic4tor** [comment]
Hey,
I just did and it works :) Thank you!

Closing the issue now.
