### ISSUE TITLE
Incompatibility of cc.reprocess and c++20 modules support

### ISSUE THREAD

**Issue by kamrann** [build2/build2#409]
When setting `cc.reprocess = true`, iterative builds of modules-enabled projects will run into errors of the following form:
```
error: ..\..\out\msvc\hello-module\hello\main.exe.obj.ii.lz4 (or its uncompressed variant) does not exist
  info: consider cleaning the build state
```
A `clean` and `update` does indeed fix the issue, but of course this is not usable for development.

This can be reproduced easily, for example using the cxx20-modules-examples repository.
```
bdep sync config.cc.reprocess=true
bdep update
[touch a source file, such as hello.mxx]
bdep update
```

Reproduced on Windows with both msvc and clang.

**Comment by boris-kolpackov** [comment]
Fixed, thanks for the reproducer!
