### ISSUE TITLE
Support for simple projects pulling in other projects

### ISSUE THREAD

**Issue by max0x7ba** [build2/build2#41]
I have a project with three packages:
```
[~/src/atomic_queue] $ tree
.
├── benchmark
│   ├── benchmark
│   │   ├── benchmark.cxx
│   │   ├── buildfile
│   │   └── moodycamel.hxx
│   ├── build
│   │   ├── bootstrap
│   │   │   └── out-root.build
│   │   ├── bootstrap.build
│   │   └── root.build
│   ├── buildfile
│   └── manifest
├── libatomic_queue
│   ├── build
│   │   ├── bootstrap
│   │   │   └── out-root.build
│   │   ├── bootstrap.build
│   │   ├── export.build
│   │   └── root.build
│   ├── buildfile
│   ├── libatomic_queue
│   │   ├── atomic_queue.cxx
│   │   ├── atomic_queue.hxx
│   │   ├── atomic_queue_mutex.hxx
│   │   ├── barrier.hxx
│   │   ├── buildfile
│   │   ├── cpu_base_frequency.cxx
│   │   ├── cpu_base_frequency.hxx
│   │   ├── defs.hxx
│   │   ├── export.hxx
│   │   ├── spinlock.hxx
│   │   └── version.hxx.in
│   └── manifest
├── LICENSE
├── Makefile
├── packages.manifest
├── README.md
├── repositories.manifest
├── test
│   ├── build
│   │   ├── bootstrap
│   │   │   └── out-root.build
│   │   ├── bootstrap.build
│   │   └── root.build
│   ├── buildfile
│   ├── manifest
│   └── test
│       ├── buildfile
│       └── test.cxx
└── buildfile
```

I would like `b` to build all packages when invoked from the top level project directory. When I add a buildfile to the top level directory with the following content:

```
./: {*/ -build/} doc{README.md LICENSE}
```

And run `b` it dumps core:

```
[~/src/atomic_queue] $ b --version
build2 0.11.0
libbutl 0.11.0
host x86_64-linux-gnu
Copyright (c) 2014-2019 Code Synthesis Ltd
This is free software released under the MIT license.

[~/src/atomic_queue] $ cat buildfile 
./: {*/ -build/} doc{README.md LICENSE}

[~/src/atomic_queue] $ b
Segmentation fault (core dumped)

[~/src/atomic_queue] $ mv {,x}buildfile
[~/src/atomic_queue] $ b
error: no buildfile in ./
  info: consider explicitly specifying its src_base

[~/src/atomic_queue] $ cd ../atomic_queue-gcc/
[~/src/atomic_queue-gcc] $ b
mkdir libatomic_queue/fsdir{libatomic_queue/}
mkdir test/fsdir{test/}
mkdir benchmark/fsdir{benchmark/}
version.in ../atomic_queue/libatomic_queue/libatomic_queue/version.hxx.in
c++ ../atomic_queue/libatomic_queue/libatomic_queue/cxx{atomic_queue}@libatomic_queue/libatomic_queue/
c++ ../atomic_queue/libatomic_queue/libatomic_queue/cxx{atomic_queue}@libatomic_queue/libatomic_queue/
c++ ../atomic_queue/libatomic_queue/libatomic_queue/cxx{cpu_base_frequency}@libatomic_queue/libatomic_queue/
c++ ../atomic_queue/libatomic_queue/libatomic_queue/cxx{cpu_base_frequency}@libatomic_queue/libatomic_queue/
c++ ../atomic_queue/benchmark/benchmark/cxx{benchmark}@benchmark/benchmark/
c++ ../atomic_queue/test/test/cxx{test}@test/test/
ar libatomic_queue/libatomic_queue/liba{atomic_queue}
ld libatomic_queue/libatomic_queue/libs{atomic_queue}
ld test/test/exe{test}
ld benchmark/benchmark/exe{benchmark}
```

Stacktrace:
```
(gdb) r -V
Starting program: /usr/local/bin/b 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6803700 (LWP 12432)]
[New Thread 0x7ffff5fb2700 (LWP 12451)]
[New Thread 0x7ffff5761700 (LWP 12452)]

Thread 2 "b" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6803700 (LWP 12432)]
0x000055555587e944 in butl::project_name const& build2::cast<butl::project_name>(build2::value const&) ()
(gdb) bt
#0  0x000055555587e944 in butl::project_name const& build2::cast<butl::project_name>(build2::value const&) ()
#1  0x000055555587c78b in build2::import(build2::scope&, build2::name, build2::location const&) ()
#2  0x00005555557c3c47 in build2::parser::parse_import(build2::token&, build2::token_type&) ()
#3  0x00005555557cd425 in build2::parser::parse_clause(build2::token&, build2::token_type&, bool) ()
#4  0x00005555557ce959 in build2::parser::parse_buildfile(std::istream&, butl::basic_path<char, butl::any_path_kind<char> > const&, build2::scope&, build2::scope&) ()
#5  0x00005555558769cb in build2::source(build2::scope&, build2::scope&, butl::basic_path<char, butl::any_path_kind<char> > const&, bool) ()
#6  0x0000555555876d90 in build2::source_once(build2::scope&, build2::scope&, butl::basic_path<char, butl::any_path_kind<char> > const&, build2::scope&) ()
#7  0x00005555556f28ff in build2::dir_search(build2::target const&, build2::prerequisite_key const&) ()
#8  0x0000555555839a5d in build2::search(build2::target const&, build2::prerequisite_key const&) ()
#9  0x000055555565db9b in build2::search(build2::target const&, build2::prerequisite const&) ()
#10 0x000055555583f83b in build2::match_prerequisites(build2::action, build2::target&, std::function<build2::prerequisite_target (build2::action, build2::target const&, build2::prerequisite const&, build2::include_type)> const&, build2::scope const*) ()
#11 0x0000555555845582 in build2::alias_rule::apply(build2::action, build2::target&) const ()
#12 0x000055555583a20d in build2::apply_impl(build2::action, build2::target&, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::reference_wrapper<build2::rule const> > const&) ()
#13 0x000055555583b8a5 in build2::match_impl(build2::target_lock&, bool, bool) ()
#14 0x000055555583bb28 in build2::match(build2::action, build2::target const&, unsigned long, std::atomic<unsigned long>*, bool)::{lambda(build2::diag_frame const*, build2::target_lock const*, build2::target&, unsigned long)#1}::operator()(build2::diag_frame const*, build2::target_lock const*, build2::target&, unsigned long) const ()
#15 0x000055555583bc33 in void build2::scheduler::task_thunk<build2::match(build2::action, build2::target const&, unsigned long, std::atomic<unsigned long>*, bool)::{lambda(build2::diag_frame const*, build2::target_lock const*, build2::target&, unsigned long)#1}, build2::diag_frame const*&, build2::target_lock const*&, std::reference_wrapper<build2::target>, unsigned long&>(build2::scheduler&, std::unique_lock<std::mutex>&, void*) ()
#16 0x00005555557eece1 in build2::scheduler::helper(void*) ()
#17 0x00007ffff773f6db in start_thread (arg=0x7ffff6803700) at pthread_create.c:463
#18 0x00007ffff6ec788f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

(gdb) info registers
rax            0x7ffff67fc5a0	140737328956832
rbx            0x7ffff67fcf30	140737328959280
rcx            0x0	0
rdx            0x0	0
rsi            0x5f626173	1600282995
rdi            0x0	0
rbp            0x7ffff67ff0e0	0x7ffff67ff0e0
rsp            0x7ffff67fc3d0	0x7ffff67fc3d0
r8             0x0	0
r9             0x555555b622a0	93824998580896
r10            0x7ffff00008d0	140737219922128
r11            0x5555558c6bd4	93824995847124
r12            0x555555b636c8	93824998586056
r13            0x555555b636d8	93824998586072
r14            0x7ffff67fc5a0	140737328956832
r15            0x7ffff67fcd10	140737328958736
rip            0x55555587e944	0x55555587e944 <butl::project_name const& build2::cast<butl::project_name>(build2::value const&)+4>
eflags         0x10202	[ IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb) disassemble
Dump of assembler code for function _ZN6build24castIN4butl12project_nameEEERKT_RKNS_5valueE:
   0x000055555587e940 <+0>:	sub    $0x8,%rsp
=> 0x000055555587e944 <+4>:	cmpb   $0x0,0x8(%rdi)
   0x000055555587e948 <+8>:	jne    0x55555587e9b9 <_ZN6build24castIN4butl12project_nameEEERKT_RKNS_5valueE+121>
   0x000055555587e94a <+10>:	mov    (%rdi),%rdx
   0x000055555587e94d <+13>:	test   %rdx,%rdx
   0x000055555587e950 <+16>:	je     0x55555587e96e <_ZN6build24castIN4butl12project_nameEEERKT_RKNS_5valueE+46>
   0x000055555587e952 <+18>:	lea    0x2b65e7(%rip),%rcx        # 0x555555b34f40 <_ZN6build212value_traitsIN4butl12project_nameEE10value_typeE>
   0x000055555587e959 <+25>:	cmp    %rcx,%rdx
   0x000055555587e95c <+28>:	jne    0x55555587e965 <_ZN6build24castIN4butl12project_nameEEERKT_RKNS_5valueE+37>
   0x000055555587e95e <+30>:	jmp    0x55555587e990 <_ZN6build24castIN4butl12project_nameEEERKT_RKNS_5valueE+80>
   0x000055555587e960 <+32>:	cmp    %rcx,%rdx
   0x000055555587e963 <+35>:	je     0x55555587e990 <_ZN6build24castIN4butl12project_nameEEERKT_RKNS_5valueE+80>
   0x000055555587e965 <+37>:	mov    0x10(%rdx),%rdx
   0x000055555587e969 <+41>:	test   %rdx,%rdx
   0x000055555587e96c <+44>:	jne    0x55555587e960 <_ZN6build24castIN4butl12project_nameEEERKT_RKNS_5valueE+32>
   0x000055555587e96e <+46>:	lea    0x4a36b(%rip),%rcx        # 0x5555558c8ce0 <_ZZN6build24castIN4butl12project_nameEEERKT_RKNS_5valueEE19__PRETTY_FUNCTION__>
   0x000055555587e975 <+53>:	mov    $0x9d,%edx
   0x000055555587e97a <+58>:	lea    0x20b4f(%rip),%rsi        # 0x55555589f4d0
   0x000055555587e981 <+65>:	lea    0x20c2f(%rip),%rdi        # 0x55555589f5b7
   0x000055555587e988 <+72>:	callq  0x5555555c36e0 <__assert_fail@plt>
   0x000055555587e98d <+77>:	nopl   (%rax)
   0x000055555587e990 <+80>:	mov    (%rdi),%rax
   0x000055555587e993 <+83>:	cmpq   $0x0,0x58(%rax)
   0x000055555587e998 <+88>:	je     0x55555587e9b0 <_ZN6build24castIN4butl12project_nameEEERKT_RKNS_5valueE+112>
   0x000055555587e99a <+90>:	mov    (%rdi),%rax
   0x000055555587e99d <+93>:	lea    0x2b659c(%rip),%rsi        # 0x555555b34f40 <_ZN6build212value_traitsIN4butl12project_nameEE10value_typeE>
   0x000055555587e9a4 <+100>:	mov    0x58(%rax),%rax
   0x000055555587e9a8 <+104>:	add    $0x8,%rsp
   0x000055555587e9ac <+108>:	jmpq   *%rax
   0x000055555587e9ae <+110>:	xchg   %ax,%ax
   0x000055555587e9b0 <+112>:	lea    0x10(%rdi),%rax
   0x000055555587e9b4 <+116>:	add    $0x8,%rsp
   0x000055555587e9b8 <+120>:	retq   
   0x000055555587e9b9 <+121>:	lea    0x4a320(%rip),%rcx        # 0x5555558c8ce0 <_ZZN6build24castIN4butl12project_nameEEERKT_RKNS_5valueEE19__PRETTY_FUNCTION__>
   0x000055555587e9c0 <+128>:	mov    $0x95,%edx
   0x000055555587e9c5 <+133>:	lea    0x20b04(%rip),%rsi        # 0x55555589f4d0
   0x000055555587e9cc <+140>:	lea    0x3087b(%rip),%rdi        # 0x5555558af24e
   0x000055555587e9d3 <+147>:	callq  0x5555555c36e0 <__assert_fail@plt>
End of assembler dump.

```

**Comment by boris-kolpackov** [comment]
Interesting. Any chance you can share this project so that we can try to debug this?

**Comment by max0x7ba** [comment]
The source code is in https://github.com/max0x7ba/atomic_queue/tree/dev-build2

**Comment by boris-kolpackov** [comment]
Thanks. We've tried to reproduce this but couldn't. What were the setup steps that led to this? I see you have `atomic_queue-gcc` so maybe there were some `bdep` commands leading up to this?

**Comment by max0x7ba** [comment]
`bdep` commands issued:
```
bdep new -t empty,no-readme atomic_queue
bdep new --package -t lib,no-tests,no-readme libatomic_queue
bdep new --package -t exe,no-tests,no-readme benchmark
bdep new --package -t exe,no-tests,no-readme test
bdep init -C @gcc cc config.cxx=g++
```

**Comment by boris-kolpackov** [comment]
Thanks, but we still seem to be missing some pieces. In particular, there are no `build/` subdirectories in your repository.

**Comment by max0x7ba** [comment]
I have pushed `build/` subdirectories into the repo now.

**Comment by boris-kolpackov** [comment]
Ok, I've finally managed to reproduce the issue, thanks for your patience. I understand what the problem is (your `atomic_queue` is a *simple project* with subprojects) but I need to ruminate on what the fix should be.

**Comment by max0x7ba** [comment]
Well, I worked around the issue by adding a top level `build` directory with all the files the subprojects' `build` directories contain:
```
[~/src/atomic_queue] $ tree build/                                                                                                                                      
build/                                                                                                                                                                  
├── bootstrap                                                                                                                                                           
│   └── out-root.build                                                                                                                                                  
├── bootstrap.build                                                                                                                                                     
└── root.build              
```

However, that doesn't feel like an elegant solution because now I have a per-sub-project `build` directory along with the top level `build` directory. It feels like there should only be one top level `build` directory and its settings should be propagated to the sub-projects` scopes. 

Again, I only learn `build2` and quite like its ideas, but am not sure I am using it correctly.

**Comment by boris-kolpackov** [comment]
Yes, I agree, the workaround is inelegant plus it will have to be setup in ad hoc manner (`bdep` won't be able to arrange this automatically).

> Again, I only learn build2 and quite like its ideas, but am not sure I am using it correctly.

Yes, the way you have arranged things is a bit unorthodox. Usually you won't have tests or benchmark as separate packages but rather have them as part of the package that they test/benchmark (`libatomic_queue` in your case). Or, if you really wanted them as separate packages, then they would be called something like `libatomic_queue_test` and `libatomic_queue_benchmark`.

But there are valid use-cases for having multi-package projects in which case having a root `buildfile` that allows one to update/test/etc all the packages seems quite natural. So I am still thinking how we can fit this support into our existing model.

**Comment by max0x7ba** [comment]
> Yes, the way you have arranged things is a bit unorthodox. Usually you won't have tests or benchmark as separate packages but rather have them as part of the package that they test/benchmark (`libatomic_queue` in your case). Or, if you really wanted them as separate packages, then they would be called something like `libatomic_queue_test` and `libatomic_queue_benchmark`.

I do not need `test` and `benchmark` to be separate packages. However, `test` also depends on `boost`; `benchmark` depends on `boost`, `tbb` and `moodycamel`; whereas `libatomic_queue` doesn't depend on any of those. Adding all these dependencies to `libatomic_queue` doesn't feel right, so I extracted all my executables into their own packages with their own dependencies and hit this issue.

In other words, I am not sure how to best express this scenario using `build2`.

**Comment by boris-kolpackov** [comment]
Yes, that's a difficult one and I don't think the current "state of the art" handles such cases well. For example, Rust has `dev` dependencies to solve this very problem. However, to me `tests` in particular don't feel like a development-only dependency; I think it's a good idea for a package user to run tests and we have support for this in our tooling (e.g., the ability to run tests recursively in all the dependencies).

A proper way to solve this would probably be a fully dynamic dependency discovery where a build system has a feedback loop to the package manager so that, in this specific case, additional dependencies are only in effect when the user actually tries to run tests. But this feels like a fairly complex logic that can get confusing when things go wrong. We do have some hooks/ideas to try this, eventually.

So for now I see two ways forward:

1. Simplify not to have extra dependencies for tests/examples/benchmarks.

2. Make tests/examples/benchmarks separate packages (probably with `libatomic_queue_tests`, etc., names).

It can also be a combination of the two. I would personally try hard to at least keep tests in the package itself or maybe split the tests into "core" (live in the package) and "extra" (live in a separate package).

Regarding #2, there is an idea to support *package components*, something like `libatomic_queue:tests`, `libatomic_queue:examples`, etc (exact syntax is not final). They will be like normal packages where the dependency resolution is concerned except they actually come from a single package manifest.

**Comment by max0x7ba** [comment]
> Rust has dev dependencies to solve this very problem.

> However, to me tests in particular don't feel like a development-only dependency; I think it's a good idea for a package user to run tests and we have support for this in our tooling (e.g., the ability to run tests recursively in all the dependencies).

Thinking more about tests, the standard C++ library doesn't provide unit testing facilities (apart from may be `assert`), so that people often use 3rd-party unit testing libraries, such as boost, googletest, etc. IMO, it would be a win-win for `build2` and its users if it provided a way for tests to be a part of the package but have extra dependencies.

Or, may be, `build2` should allow each target (rather than a package) to have their own dependencies. Otherwise, whenever a target wants an extra dependency it needs to be extracted into its own package. So that in the extreme, each target is its own package (and this is where I arrived).

I am okay with all of my targets to be their own packages. In this case it would be ideal:

1. To not have an extra directory level for the sources, e.g. `atomic_queue/benchmark/benchmark.cxx` instead of current `atomic_queue/benchmark/benchmark/benchmark.cxx`.
2. And have a way to invoke `b` from the top level directory without having to make it look like a package with nested packages (the documentation says nested packages aren't supported, IIRC).

Just thinking out loud.

**Comment by Klaim** [comment]
> Or, may be, build2 should allow each target (rather than a package) to have their own dependencies. Otherwise, whenever a target wants an extra dependency it needs to be extracted into its own package. So that in the extreme, each target is its own package (and this is where I arrived).

An alternative would be to allow sub-projects to have different dependencies than other sub-projects and than the root project.

Though that would mean that some ways to build the root project without the sub-projects could be necessary OR some way for bpkg to determine that some dependencies do not need to be resolved until we try to build/depends on targets which are in sub-projects, which seem a bit too much magic.

**Comment by boris-kolpackov** [comment]
> Thinking more about tests, the standard C++ library doesn't provide unit testing facilities (apart from may be `assert`), so that people often use 3rd-party unit testing libraries, such as boost, googletest, etc. IMO, it would be a win-win for `build2` and its users if it provided a way for tests to be a part of the package but have extra dependencies.

I think adding a non-optional dependency on catch/gtest/etc in order to run tests is perfectly reasonable (chances are other dependencies will also use them). It's the case where you have a large number of extra dependencies just for running tests that I think is problematic. And in this case I would recommend splitting the tests into core and extra with extra being a separate package (for now) or a separate package component (once we have this facility).

> Or, may be, `build2` should allow each target (rather than a package) to have their own dependencies. 

That's essentially the idea behind package components. We still need this separate notion (*package component*) because dependencies are specified in package manifests which have no knowledge of build system targets.

> 1. To not have an extra directory level for the sources, e.g. `atomic_queue/benchmark/benchmark.cxx` instead of current `atomic_queue/benchmark/benchmark/benchmark.cxx`.

While I agree this is a bit unwieldy, it will be hard to get rid of (until we have package components) without violating the canonical project structure. When things are distributed as separate packages, the second-level directory becomes the package  root, so you will have something like `benchmark-1.2.3/benchmark/benchmark.cxx`.

> 2. And have a way to invoke b from the top level directory [...]

Yes, I think this is an important usability shortcoming so we are going to look into supporting this (after you brought it up we actually realized we run into this ourselves).

> An alternative would be to allow sub-projects to have different dependencies than other sub-projects and than the root project.

The idea with package components is to allow you to map them to various build system entities: sub-projects, targets, configuration variables, etc. It is still fuzzy how exactly we will do this, however (probably via configuration variables).

**Comment by boris-kolpackov** [comment]
As of 0.13.0 we now have support for "glue buildfiles" that allow one to "pull" several projects: https://build2.org/release/0.13.0.xhtml#adhoc-import

Such a `buildfile` is also now automatically generated by `bdep-new` in the `--package` mode.

Please reopen if you think there are still issues.
