### ISSUE TITLE
Problem with bin.whole and transitive static libs

### ISSUE THREAD

**Issue by kamrann** [build2/build2#411]
This is a pretty horrible corner case and I wonder if perhaps there is a better approach to take, but regardless it feels like it's either a shortcoming, or something that could maybe be diagnosed if I'm doing something fundamentally wrong here. 

Given the following dependency chain:
```
liba{static_1}: ...
liba{static_2}: ... liba{static_1}

# case A
libs = liba{static_1} liba{static_2}
# case B
#libs = liba{static_2} liba{static_1}

libs{shared}: $libs: bin.whole = true
```
So the intention is to link multiple static libs into a shared lib in whole archive mode, but one of the static libs happens to depend on another.

On Windows, case A works as expected with `/WHOLEARCHIVE` being applied to both static libraries on the `link.exe` command line. But with case B, where the downstream static lib with a dependency on the other comes first in the `libs` list, the resulting command line applies `/WHOLEARCHIVE` only to `static_2`. Presumably this is because the linker input for `static_1` is generated as a result of the dependency of `static_2`, `bin.whole` doesn't apply in that case because it's being linked to a static library, but then I guess subsequently build2 is detecting that `static_1` has already been linked so doesn't add it again when processing the dependency from `shared`, which is where `bin.whole` would have been applied.

Could build2 perhaps just not deduplicate in this case and repeat the library input? Or am I simply doing something that I shouldn't here?

Edit: I suppose another option would be to apply `bin.whole` recursively to dependencies, but my gut feeling is that probably wouldn't be the generally expected semantics.

**Comment by boris-kolpackov** [comment]
Yes, that's a pretty accurate analysis: we skip duplicates but don't take `bin.whole` differences into account. Should be fixed now, thanks for the report and the reproducer!
