### ISSUE TITLE
Clang-cl for cross compilation

### ISSUE THREAD

**Issue by b4dW01ff** [build2/build2#415]
Hello. As the title says, I've been trying to cross compile on Linux for Windows. 
The Toolchain introduction on the docs uses Mingw as a cxx compiler and it just works. But apparently, clang-cl, with a "cl" in it's name, is seen as the VC compiler, and so Build2 attempts to extract MSVC information, which obviously fails.
I'm using [xwin](https://github.com/Jake-Shadle/xwin) to create a sysroot equivalent of Windows, and clang-cl works with that from the command line. But Build2 always treats clang-cl as the VC compiler, so the flags used in the command line, when used in the `config.cxx.coptions`, have no effect over Build2's search for MSVC information. The flag automatically used to get target information when `config.cxx.target` is omitted (`-dumpmachine`) also isn't compatible with clang-cl, it prints the info using the `-v` flag.  Also, using `config.cxx.target` as a workaround for the lack of the `-dumpmachine`  flag doesn't work, as soon as that is configured for a Windows target, like `x86_64-PC-Windows-msvc`, Build2 also looks for MSVC info.
Is there anyone else trying to use clang-cl as well?

**Comment by Klaim** [comment]
> Is there anyone else trying to use clang-cl as well?

Most of us prefer to just use `clang`/`clang++` directly on Windows as by default `build2` use the msvc toolchain in that case (linker, standard library etc.). That's also [recommended by the build-system manual, with a rational for why and some help if you still want to use `clang-cl` (at the end of section)](https://build2.org/build2/doc/build2-build-system-manual.xhtml#cc-clang-msvc).

**Comment by b4dW01ff** [comment]
> Most of us prefer to just use `clang`/`clang++` directly on Windows as by default `build2` use clang with the msvc toolchain in that case (linker, standard library etc.). That's also [recommended by the build-system manual, with a rational for why and some help if you still want to use `clang-cl` (at the end of section)](https://build2.org/build2/doc/build2-build-system-manual.xhtml#cc-clang-msvc).

So, Mingw is still the best way to cross-compile to Windows...
Thank you for your reply. I'm closing the issue.

**Comment by boris-kolpackov** [comment]
> So, Mingw is still the best way to cross-compile to Windows.

You are misunderstanding what @Klaim means: when you use Clang to target the MSVC runtime (as opposed to the MinGW runtime), you have two options where the compiler driver is concerned: vanilla `clang/clang++` drivers the same as on Unix and the `clang-cl` wrapper which mimics the `cl.exe` interface. The latter (`clang-cl`) is a very approximate wrapper (more like a hack, really) and is not recommended when using `build2`. Instead, you should use the vanilla driver.

Whether it's easier to cross-compile when targeting MSVC or MinGW runtime is an orthogonal question.
