### ISSUE TITLE
HTTPS compatibility of Build2 packaged libcurl

### ISSUE THREAD

**Issue by b4dW01ff** [build2/build2#416]
Hello there. I'm trying to use libcurl on my project to connect to a HTTPS site. But the [libcurl](https://cppget.org/?packages=libcurl) package available on cppget.org only connects to HTTP sites. I know there's a lot involved in libcurl's (correct) usage, but I've used different examples and can't get it to work. However, when I change the URL to HTTP, the program works normally (not really, but it's not blank as it is when using HTTPS). 
 Apparently, when libcurl is built from source the build can detect the system's ca-certificate and I have the ca-certificates package installed on my OpenSUSE Tumbleweed system; also I can get a normal response in a simple command like `curl  https://duckduckgo.com`. I haven't tried compiling libcurl from source normally (I mean outside of Build2) and then passing it's include and lib directories to Build2's compiler configuration yet. What I tried was also adding the [libca-certificates-curl](https://cppget.org/libca-certificates-curl) package to the project but that didn't change anything.

**Comment by b4dW01ff** [comment]
It works now. But cannot just automatically use the system's ca-certificates in my project. Using information from [this blog post](https://pranavprakash.net/2014/09/27/using-libcurl-with-ssl/), [this doc from curl](https://curl.se/docs/sslcerts.html) - specifically point 02 - and [this other doc from curl](https://curl.se/libcurl/c/CURLOPT_CAINFO.html), I pointed libcurl to the ca-certificates installed on my system using `curl_easy_setopt(curl, CURLOPT_CAINFO, cacert.c_str());`. The `cacert` is a string variable containing the absolute path to a `ca-bundle.pem` file installed on my system. 
For Tumbleweed and other RHEL based distros [this Stack Exchange (unrated) answer helps](https://unix.stackexchange.com/questions/80131/how-do-i-install-a-system-wide-ssl-certificate-on-opensuse#:~:text=I%20would%20take%20a%20look%20for%20a%20package%20called%20ca%2Dcertificates%20(that%27s%20the%20name%20it%20goes%20by%20on%20Red%20Hat%20distros).%20All%20of%20the%20main%20distros%20bundle%20certificates%20and%20they%27re%20generally%20in%20the%20same%20location.).  Using this command: `rpm -ql ca-certificates` I could find where my certificates were. Notice that the answer on Stack Exchange recommends `rpm -qi ca-certificates`, which shows information about the ca-certificates package if you have it installed, but I've made a typo that actually helped me.

**Comment by boris-kolpackov** [comment]
Using certificates in `libcurl` in a portable manner is actually quite complicated and is the reason why we provide `libca-certificates-curl`. You can find an example of how to use it in the `curl` package which we have patched to support HTTPS/certificates portably (see `tool_main.c`).

I am closing this issue since this is really a question (which, BTW, are better asked in other places: https://build2.org/community.xhtml#help).
