### ISSUE TITLE
Why does clangd call for XCode on Macs? (Arduino-ESP32 Issue)

### ISSUE THREAD

**Issue by SurryDesignLab** [build2/build2#418]
Good afternoon,
I'm not really a clangd user, but I do spend a sizeable time on Macs and working with students on Arduino projects. Everything has been pretty smooth sailing up until this week. 

In the Arduino IDE, if I select one of the regular boards (Uno, Nano, etc) and select "verify", everything is fine. However if I select an ESP32-Cam board and select Verify (not even upload), it gives me an error that it can't find XCode. A friend showed how I could put a dummy Xcode.app file in my Applications folder, but I still get the error and it says to run "xcode-select". Just downloading this is almost 10gb - which is less than Xcode but still a lot more that I want. 

After posting all over the Arduino forum, someone posted that this is actually a clangd issue. Specifically they said, "Get the clangd/LLVM developers to remove the unnecessary XCode dependency of their application, then update the version of clangd used by Arduino IDE to the new version of clangd once they ship that change." 

So how do I make that happen? Arduino IDE 1.x doesn't call for clangd, apparently, so that's a workaround for now. But at some point I'm going to need to make the switch to Arduino 2.x. And, respectfully, I'm not going to install Xcode just because clangd said I have to for the one ESP32 project I have going on. 

So what's the story here? Can I load a different version of clangd on my individual laptop or do I have to wait for Arduino to incorporate a new version into the source code?

**Comment by boris-kolpackov** [comment]
Hm, I don't see what this has to do with `build2` (which is where you are posting this issue)? It has nothing (directly) to do with Arduino/Clangd/LLVM.

**Comment by SurryDesignLab** [comment]
Apologies if this landed in the wrong place. Can you suggest where it should be? I'm not really a clangd user but wanted to share this because having clangd look for Xcode on a Mac means the Arduino IDE 2.x is useless in working with ESP32 modules of any kind. I figured it needed to be documented somewhere.

**Comment by wroyca** [comment]
> Apologies if this landed in the wrong place. Can you suggest where it should be? I'm not really a clangd user but wanted to share this because having clangd look for Xcode on a Mac means the Arduino IDE 2.x is useless in working with ESP32 modules of any kind. I figured it needed to be documented somewhere.

Hello, 

For *clangd* specifically, you can look in https://github.com/clangd/clangd
For *llvm*, that'd be https://github.com/llvm/llvm-project
