### ISSUE TITLE
Problem with dist and filenames with leading period

### ISSUE THREAD

**Issue by kamrann** [build2/build2#424]
Files with names starting with a '.' do not appear to make it through the `dist` process.

A quick test showed that an arbitrary file added to a package will in general show up in the package's folder within a build configuration when that package is added as a dependency, but files starting with a period do not. Further, even in cases where the file is referenced in a `buildfile`, it will still fail to be distributed. 

Example (details likely irrelevant but taken as-is just in case):
```
lib{example}: include/{hxx}{**} source/{hxx cxx}{** --component.defn.h} hxx{component.defn.h} $libs file{.component}

hxx{component.defn.h}: file{.component}
{{
  diag gen $>
  echo 'something' > $path($>)
}}
```
In the above case, the `.component` file sits alongside the above `buildfile` in the source, but no copy ends up located in the distributed package, and as such the build fails.

**Comment by karen-arutyunov** [comment]
Unfortunately cannot reproduce the issue. 

Could you provide the full reproducer: the project and the exact commands which end up with the package distribution? Also, please specify the OS which you are using to reproduce the issue.

**Comment by kamrann** [comment]
I'm on Windows.
It looks like the issue isn't the `dist` command itself, since when just running that directly the file appears as expected. It seems it's related to the `install` (?) step, or anyway whatever `bpkg` is doing after `dist`.

From the `bdep init` command (full repro steps are below) output:
```
C:\build2\installed\bin\b -v --no-external-modules !config.dist.bootstrap=true config.dist.root='C:\Coding\Build2\bug-repros\build2\temp-repro\dist-leading-period\out\' dist('C:\Coding\Build2\bug-repros\build2\temp-repro\dist-leading-period\out\.bpkg\tmp\9e584fc157cf\.\'@'C:\Coding\Build2\bug-repros\build2\temp-repro\dist-leading-period\out\.bpkg\tmp\dist-leading-period\')
install -d -m 755 ..\out\dist-leading-period-0.1.0-a.0.20240911024458.454d1f3edc5f
install -d -m 755 ..\out\dist-leading-period-0.1.0-a.0.20240911024458.454d1f3edc5f\build
install -p -m 644 ..\out\.bpkg\tmp\9e584fc157cf\build\bootstrap.build ..\out\dist-leading-period-0.1.0-a.0.20240911024458.454d1f3edc5f\build
install -p -m 644 ..\out\.bpkg\tmp\9e584fc157cf\build\export.build ..\out\dist-leading-period-0.1.0-a.0.20240911024458.454d1f3edc5f\build
install -p -m 644 ..\out\.bpkg\tmp\9e584fc157cf\build\root.build ..\out\dist-leading-period-0.1.0-a.0.20240911024458.454d1f3edc5f\build
install -p -m 644 ..\out\.bpkg\tmp\9e584fc157cf\buildfile ..\out\dist-leading-period-0.1.0-a.0.20240911024458.454d1f3edc5f
install -d -m 755 ..\out\dist-leading-period-0.1.0-a.0.20240911024458.454d1f3edc5f\dist-leading-period
install -p -m 644 ..\out\.bpkg\tmp\9e584fc157cf\dist-leading-period\buildfile ..\out\dist-leading-period-0.1.0-a.0.20240911024458.454d1f3edc5f\dist-leading-period
install -p -m 644 ..\out\.bpkg\tmp\9e584fc157cf\dist-leading-period\dist-leading-period.hxx ..\out\dist-leading-period-0.1.0-a.0.20240911024458.454d1f3edc5f\dist-leading-period
install -p -m 644 ..\out\.bpkg\tmp\9e584fc157cf\dist-leading-period\version.hxx.in ..\out\dist-leading-period-0.1.0-a.0.20240911024458.454d1f3edc5f\dist-leading-period
install -p -m 644 ..\out\.bpkg\tmp\9e584fc157cf\manifest ..\out\dist-leading-period-0.1.0-a.0.20240911024458.454d1f3edc5f
install -p -m 644 ..\out\.bpkg\tmp\9e584fc157cf\README.md ..\out\dist-leading-period-0.1.0-a.0.20240911024458.454d1f3edc5f
install -p -m 644 ..\out\.bpkg\tmp\9e584fc157cf\repositories.manifest ..\out\dist-leading-period-0.1.0-a.0.20240911024458.454d1f3edc5f
checked out dist-leading-period/0.1.0-a.0.20240911024458.454d1f3edc5f
```
I can see that the result of the `dist` within the `.bpkg` folder is as it should be, but it can be seen that there is no `install` command generated for the `.example` file.

[Here's the repro](https://github.com/user-attachments/files/16957319/dist-leading-period-repro.zip). Note there are two side by side projects, `dist-leading-period` library containing a `.example` file and some associated `buildfile` logic, and `dist-leading-period-test` executable depending on the former package (via relative path in `repositories.manifest`).

```
> cd dist-leading-period/dist-leading-period-test
> bdep -v init -C ../out cc config.cxx=cl
> bdep update
```
```
error: no rule to update ..\out\dist-leading-period-0.1.0-a.0.20240911024458.454d1f3edc5f\dist-leading-period\file{.example}
```

**Comment by boris-kolpackov** [comment]
Fixed and the fix is available in the latest staged toolchain.
