### ISSUE TITLE
Built-in `find` doesn't work for sym-linked directory: `xxx is not a directory`

### ISSUE THREAD

**Issue by helmesjo** [build2/build2#434]
Eg. when used in an ad-hoc recipe:

```c++
{{
  depdb dyndep \
    --dyn-target \
    --target-cwd $directory($>) \
    --target-what 'test' \
    --format lines \
    --file "$directory($>)/test.d" \
    -- \
      find "$src_base/upstream/" -type l -name "*" >$directory($>)/test.d
}}
```

**Error:**
```
find: 'C:\Users\doe\git\libhello\libhello\upstream' is not a directory
buildfile:102:3: error: builtin find exited with code 1
  info: command line: find C:\Users\doe\git\libhello\libhello\upstream\ -type f -name *
```

The equivalent (system) command in the terminal works fine.

**Comment by helmesjo** [comment]
Actually, this might be an issue with path separators (most likely). Wrapping the start directory in `$path.posix_string($src_base/upstream/)` makes it happy. I guess this makes sense and is expected?

**Comment by boris-kolpackov** [comment]
Probably has something to do with the brain-dead symlink support on Windows. I am guessing `upstream` is a junction. Maybe we don't handle this case in `find`?

**Comment by boris-kolpackov** [comment]
We seem to have run into the same issue in ICU and it appears to be a problem on non-Windows platforms as well. Adding `/.` (e.g., `find "$src_base/upstream/."`) appears to work around the problem.
