### ISSUE TITLE
Unclear step in BOOSTRAP-UNIX.cli w/r to build2/b

### ISSUE THREAD

**Issue by gl-yziquel** [build2/build2#435]
Hi.

I've tried to follow BOOSTRAP-UNIX.cli by using a source tarball to bootsrap a build of build2.

I did essentially what was described there:

```console
tar -xzvf build2-toolchain-0.17.0.tar.gz
mkdir _prefix
cd build2-toolchain-0.17.0
./build.sh --install-dir $(pwd)/../_prefix g++
cd build2
./bootstrap.sh g++ -w
build2/b-boot config.cxx=g++ config.bin.lib=static build2/exe{b}
```

The instructions then say to do `mv build2/b build2/b-boot`. But I do not see any build2/b file...

So: Either 1. the build instructions are out of date or 2. they are up to date and something fishy is happening.

The step `build2/b-boot config.cxx=g++ config.bin.lib=static build2/exe{b}` updates the files b.o, b.d, b-stage, b-stage.d. I'm therefore wondering whether or not the build2/b file is in fact the build2/b-stage file.

**Comment by boris-kolpackov** [comment]
I am going to close this since I don't believe any changes are required.
