### ISSUE TITLE
`error: invalid compilation database json input: beginning of array expected`

### ISSUE THREAD

**Issue by helmesjo** [build2/build2#441]
Notice that the `compile_commands.json` is indeed empty. I had is initialized with `config.cc.compiledb=@<projdir>/compile_commands.json` (in a script), then stashed the changes, reinitialized the project and built again with `bdep update` (meaning the `compile_commands.json` was still lingering around, which I assume should just work and not error out).

[compile_commands.json](https://github.com/user-attachments/files/17476051/compile_commands.json)
[update.txt (`--verbose=6`)](https://github.com/user-attachments/files/17476048/update.txt)

```
$ bdep --version
bdep 0.18.0-a.0.e9a2eb940d6d
libbpkg 0.18.0-a.0.0bd2f5a8b8c3
libbutl 0.18.0-a.0.8f892e075668
```

**Additional `Assertion failed`:**
When I'm in the same state as above, I can provoke an assertion failure by instead invoking `b -v --dry-run "config.cxx='C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.41.34120/bin/HostX64/x64/cl.exe'" config.config.load='./configs/x86_64-windows-msvc-debug.build' update('C:\Users\fho\git\qme\pkgs\camera_module\')` manually.

[b-update-dryrun.txt](https://github.com/user-attachments/files/17476289/b-update-dryrun.txt)

**Comment by boris-kolpackov** [comment]
> Notice that the `compile_commands.json` is indeed empty.

The one you have attached contains an empty array (i.e., `[]`). Is this what you mean by empty or was the file actually empty (0 bytes)?

**Comment by boris-kolpackov** [comment]
I just tried to produce an empty array and it is always printed as:

```
[
]
```

That is, the braces are on separate lines, which is the expected (by `build2`) format. You will need to understand how/who produced the version with `[]` on the same line.

**Comment by helmesjo** [comment]
> That is, the braces are on separate lines, which is the expected (by build2) format. You will need to understand how/who produced the version with [] on the same line.

Then it would be [`compiledb`](https://github.com/nickdiego/compiledb) that generated it (which I use normally). The point with this issue though was rather the fragility. Eg. it's easy for someone to edit the file to contain `[]` in separate lines (which is still valid `json`) & not expect it to fail and certainly not crash.
