### ISSUE TITLE
Allow using symlink timestamp instead of source file in adhoc recipes

### ISSUE THREAD

**Issue by helmesjo** [build2/build2#445]
Consider an adhoc recipe like this:

```
define dyn_target: group

./: dyn_target{input}: h{input}
{{
  depdb dyndep \
      --dyn-target \
      --adhoc \
      --target-cwd "$out_base" \
      --format lines \
      -- echo 'input.h'

  env -c $directory($>[1]) -- ln --symbolic $path($<) input.h
}}
```

The above will generate the error:
```
error: backwards modification times detected:
    2024-10-31 13:33:02.679834600 sequence start
    2024-10-31 13:33:02.678820400 <out-base>/input.dyn_target.d
    2024-10-31 13:30:59.604435400 <out-base>/input.h
    2024-10-31 13:33:02.680191600 sequence end
```

This renders `ln` quite unusable in adhoc recipes for dynamic targets (possibly other variants as well).
The reason `ln` is useful is for example with [`FFmpeg`](https://github.com/helmesjo/build2-FFmpeg) where some headers requires some patching that realistically won't be fixed upstream for a while (or at all) but at the same time relies on other header files using `#include "input.h"` to favor `input.h` that is in the same directory to find the correct file (there may be other `input.h` that are in the `"-I$src_base/"` directory). In this case the patching is for proper symbol exportation/importation of global variables with `cl.exe` & `clang-cl.exe`.
Since timestamps for symlinks differs from the source file/directory it seems reasonable to at least have the option to use it instead.

**Comment by boris-kolpackov** [comment]
Implemented and available in the latest staged toolchain. Please test.
