### ISSUE TITLE
`error: unable to query terminal color support for stderr: the handle is invalid` (`git-bash Msys2`)

### ISSUE THREAD

**Issue by helmesjo** [build2/build2#447]
See discussion [here](https://cpplang.slack.com/archives/CDJ0Z991S/p1731079874840519).

Running  `bpkg cfg-create` in `git-bash Msys`) spits out this error:
```bash
bpkg cfg-create \
            --quiet \
            --directory "." \
            --wipe \
            cc
error: unable to query terminal color support for stderr: the handle is invalid
```

```
uname -a
MINGW64_NT-10.0-22631 my-pc 3.4.10-87d57229.x86_64 2024-02-14 20:17 UTC x86_64 Msys
```

Install git and choose `Use MinTTY (the default terminal MSYS2)`:

![image](https://github.com/user-attachments/assets/4b451469-1b58-45d4-b693-c98cc7e6bdee)

**Comment by boris-kolpackov** [comment]
I've attempted a fix and it's available in the latest staged toolchain. Could you test it and see if it makes a difference?

**Comment by helmesjo** [comment]
Yep, that did it. Thanks.
