### ISSUE TITLE
When your build system has bad intuition

### ISSUE THREAD

**Issue by FlightBlaze** [build2/build2#46]
Hey developer!

I have three modules: **AbstractWindow**, **Window** and **Manager**.

**Manager** imports **Windows**...
**Windows** imports **AbstractWindow**...

..._BOOOOM!!_ (compilation error, my chair is burn)

```
kawaii/Manager.cc: error: failed to correctly guess module name from ~ /kawaii-clang/kawaii/kawaii/:mxx{AbstractWindow}
  info: guessed: kawaii.Window
  info: actual:  kawaii.AbstractWindow
  info: consider adjusting module interface file names or
  info: consider specifying module name with cxx.module_name
  info: while extracting module dependencies from kawaii/mxx{Manager}@~/kawaii-clang/kawaii/kawaii/
  info: while applying rule cxx.compile to update ../kawaii-clang/kawaii/kawaii/bmie{Manager}
  info: while applying rule cxx.link to update ../kawaii-clang/kawaii/kawaii/exe{kawaii}
  info: while applying rule alias to update ../kawaii-clang/kawaii/dir{kawaii/}
  info: while applying rule alias to update ../kawaii-clang/dir{kawaii/}
info: failed to update ../kawaii-clang/dir{kawaii/}
```

My intuition (which is better than build2's) suggested that i rename module **AbstractWindow** to something not containing **Window** module name. Bingo! It working!
```
c++ kawaii/mxx{Manager}@~/kawaii-clang/kawaii/kawaii/
c++ kawaii/mxx{Application}@~/kawaii-clang/kawaii/kawaii/
c++ kawaii/cxx{kawaii}@~/kawaii-clang/kawaii/kawaii/
ld ../kawaii-clang/kawaii/kawaii/exe{kawaii}
ln ../kawaii-clang/kawaii/kawaii/exe{kawaii} -> kawaii/
skipped updating 1 targets
```
Success compiling!

**Comment by boris-kolpackov** [comment]
From the diagnostics it does look like our heuristics is misfiring but I am a bit unclear on the exact setup (file names, module names, etc). Could you share this project (or a similar test  project) that reproduces the problem?

**Comment by FlightBlaze** [comment]
https://github.com/FlightBlaze/build2-bug-repr

**Comment by boris-kolpackov** [comment]
Thanks for the reproducer. I've fixed this for the next release and the fix is available in the latest staged version: https://build2.org/community.xhtml#stage

It would be great it you could try it and confirm things work for you. And feel free to reopen the issue if things still don't work.
