### ISSUE TITLE
Circular dependencies makes building infinitely long

### ISSUE THREAD

**Issue by FlightBlaze** [build2/build2#47]
ModuleOne.mxx:
```c++
export module ModuleOne;
export import ModuleTwo;
```
ModuleTwo.mxx
```c++
export module ModuleTwo;
import ModuleOne;
```

The universe will be dead before it is built

**Comment by boris-kolpackov** [comment]
Thanks for the report. I've fixed this for the next release and the fix is available in the latest staged version: https://build2.org/community.xhtml#stage

It would be great it you could try it and confirm things work for you. And feel free to reopen the issue if things still don't work.
