### ISSUE TITLE
Docs: Add install requirements

### ISSUE THREAD

**Issue by lunakid** [build2/build2#48]
The [canonical install guide](https://build2.org/install.xhtml) appears to be silent about the 

* ~30-40 minutes build time (on my system), 
* 1 - 2 GB free disk space required for bootstrapping (or will that be the same magnitude also for upgrades?),
* <del>whether it is safe (or costly, in terms of subsequent updates?) to delete the ~half gig build cruft left behind after the install script had finished.</del> _(OK, I found it: keeping it is recommended.)_
* the install dir will contain yet another instance of Git + MSYS (+ the usual GNU survival kit), so placing it on the `PATH` as recommended, may cause subtle, unexpected issues with your existing toolset.

MSVC16 (VS2019) here, I'm not sure about other systems, but it may be worth explicitly noting in the docs that this is certainly and significantly a more involved process than just copying `ninja.exe` or `premake5.exe` to your `PATH`.

_(Note: the slight sardonic overtone you may think you hear is real. ;) I do think this model of insisting on building the tool from scratch may end up being a "suicide feature".)_

**Comment by boris-kolpackov** [comment]
Thanks for the feedback. I will add a FAQ entry with some of these points. A couple of comments:

> ~30-40 minutes build time

Hm, I just tried to build on my i7 4-core laptop inside a Windows VM and it took 7min. I could kind of reproduce your time (24min) on an old (2012) 2-core i5 Mac Mini. Is this the kind of hardware we are talking about? If so, I am not sure we should try to optimize for that.

> the install dir will contain yet another instance of Git + MSYS [...] may cause subtle , unexpected issues with your existing toolset.

True. But, in our experience, that's unfortunately the reality of life on Windows. This is the only way we know how to do more or less reliable Windows builds (as in, thousands of builds on CI without any flaky failures). If, however, you feel adventurous, you can always omit `build2-baseutils` and try to build everything using your existing MSYS installation.

I also don't think comparing `build2` to `ninja.exe`, etc., is comparing apples to apples: `ninja` is a build tool while `build2` is a build system and a package/project dependency manager. Also, people who don't care whether they use `ninja.exe` or `build2` is not our target audience. Ours is people for whom the pain of other approaches far outweighs the inconvenience of a 5-10min from-source build (for which, BTW, there are good reasons as described in https://build2.org/install-faq.xhtml#binaries).

**Comment by boris-kolpackov** [comment]
I've added a FAQ entry which will be live after the release. We've also done some optimizations for the install process (e.g., only building shared libraries by default) which helps a bit.

**Comment by boris-kolpackov** [comment]
FYI, in 0.12.0 we've added `--local` option which reduces the build time by about half: https://build2.org/install-faq.xhtml#offline

**Comment by lunakid** [comment]
Thank you very much for the update + extending the docs!

Sorry I didn't respond: "Is this the kind of hardware we are talking about?"
Actually yes, kinda. I like it frugal... (I did it either on a Lenovo T400, or a small DigitalOcean server, can't remember now; should've clarified, I guess.)

**Comment by boris-kolpackov** [comment]
I think we can close this. Feel free to reopen if you think there is still room for improvement.
