### ISSUE TITLE
[testscript] Improvement: test timeout

### ISSUE THREAD

**Issue by Klaim** [build2/build2#52]
Proposition of improvement
-------------------------------

Allow `testscript` users to specify a *`timeout`* value in time (seconds or milliseconds)
  - A) for a specific test;
  - B) for all tests (any test is constrained by this timeout);
  - C) for the whole testscript;

In case A) we start a timer when the tested program is launched. If the program didn't end before the timeout, it is killed (nicely, then if still blocking, less nicely `kill -9`) and we report a failure.
This is for detecting blocking programs.

In case B) we apply A) on all tests of the same testscript file using a common timeout value except if specified otherwise.
This is a convenience for using A) generally when we know that a group of tests should be constrained to the same timeout.

In case C) we start the timer before starting all the tests of a testscript. If the timeout is reached before the end of all the scripts, we kill the test currently executing and report a failure.
This is useful for preventing CIs from executing for too long because of programs either blocking (if the timeout is 1 minute and all the tests are affected, and there is 100 tests we end up waiting 100 minutes), or programs abnormally slow.

To clarify: this is not about performance.

Experience with our tools
----------------------------

We usually are using `qibuild` which provides setting timeouts to test executables specified in the CMakeLists.txt fo the tests (covers cases A and B).
We also have specific CI (python) scripts which implements whole test batches timeouts (case C).

Our tests currently use `googletest` so we cannot express this using that library. But it could be provided by external libraries. However doing so would make the test implementations contain the timing code, which is not directly to the code being tested.
So we prefer this kind of constrains to be done by the system launching the tests.

This kind of timeout options helped us detect "early"  issues with deadlocks (or other issues related to badly handled concurrency) and unresponsive systems or contexts (when networking is involved, most of the time).
It might make sense to specify C at a different level than testscripts though, in CI scripts.

And today I found a bug with a program built with build2 which didn't end properly and blocked, but we never saw the issue because it's an interractive program that we usually exited using ctrl+c. When I added an exit command I saw in it's testscripts checking that command that it was never ending. I fixed the issue but it would have been useful if testscript had reported that the test is abnormally long (it should have been instant).

**Comment by boris-kolpackov** [comment]
This has been implemented and is available in the staged toolchain. For details, see the description of `config.test.timeout` variable in https://build2.org/stage/build2/doc/build2-build-system-manual.xhtml#module-test and the `timeout` builtin description in https://build2.org/stage/build2/doc/build2-testscript-manual.xhtml#builtins-timeout.

**Comment by Klaim** [comment]
Thanks! Installing this to check.
Do I understand correctly that the seconds must be integers? It's not completely clear from the docs if you can set something like `0.5`? (not a request, just clarification)

**Comment by Klaim** [comment]
It seems to work as expected at least in testscripts with this version, LGTM, good job!
```
$ b --version
build2 0.14.0-a.0.56a6082494a6
libbutl 0.14.0-a.0.759f588c35e0
host x86_64-microsoft-win32-msvc14.2
```

**Comment by boris-kolpackov** [comment]
> Do I understand correctly that the seconds must be integers?

Yes, no fractions.

Thanks for testing!
