### ISSUE TITLE
[testscript] b sefgault/access violation with incorrect testscript using cout twice with regex

### ISSUE THREAD

**Issue by Klaim** [build2/build2#53]
Context
---------

I wrote a `testscript` test and forgot to use `2` to express that I wanted `stderr` in one of the tokens, which lead to this crash. I figured my mistake and everything works when the test is correct.
That error does not appear exactly the same on Windows and Ubuntu depending on if you use `b` or `bdep` but I think it's the exact same segfault/access violation but I think it's just how it is reported that differs, it seems to be the same error on both platforms.

Windows:
```
> b --version
build2 0.12.0-a.0.7c426821e7fb
libbutl 0.12.0-a.0.69ed8e0c82e4
host x86_64-microsoft-win32-msvc14.2
Copyright (c) 2014-2019 Code Synthesis Ltd
This is free software released under the MIT license.
```

Ubuntu:
```
$ b --version
                           1 ↵
build2 0.12.0-a.0.7c426821e7fb
libbutl 0.12.0-a.0.69ed8e0c82e4
host x86_64-linux-gnu
Copyright (c) 2014-2019 Code Synthesis Ltd
This is free software released under the MIT license.
```

How To Reproduce
---------------------

1. In a new project (`bdep new ...`), replace the content of the `wrong_test/testscript` file with:

```
: wrong
$* >>~/FIRST/ >>SECOND # this is wrong/weird on purpose
wgerfw
FIRST
wefgdsfg
SECOND
```

Note: the output values are not important to trigger the crash.
The important line is the token definition. See notes below.

2. Launch the test, with `b test` and `bdep test` (after a `bdep init`)

Observed
-----------

### 1. `b test` (with or without configuration):

 - Windows:
```
> b test
c++ wrong_test\cxx{wrong_test}
ld wrong_test\exe{wrong_test}
test wrong_test\testscript{testscript} wrong_test\exe{wrong_test}
```
If there was a crash, it is not reported (I think it's msvc that inject a fast-fail or something like that).

 - Ubuntu:
```
$ b test
test wrong_testscript/testscript{testscript} wrong_testscript/exe{wrong_testscript}
[1]    9802 segmentation fault (core dumped)  b test
```

### 2. `bdep init -C ../build-wrong`  then `bdep test`:

 - Windows:
```
> bdep test
warning: working directory ..\build-wrong\wrong_test\wrong_test\test-wrong_test\ exists and is not empty at the beginning of the test
  info: while testing ..\build-wrong\wrong_test\wrong_test\exe{wrong_test}
  info: while testing ..\build-wrong\wrong_test\dir{wrong_test\}
  info: while testing ..\build-wrong\dir{wrong_test\}
test wrong_test\testscript{testscript}@..\build-wrong\wrong_test\wrong_test\ ..\build-wrong\wrong_test\wrong_test\exe{wrong_test}
error: process b terminated abnormally: access violation
```

- Ubuntu:
```
$ bdep test
mkdir ../build-wrong/wrong_testscript/fsdir{wrong_testscript/}
c++ wrong_testscript/cxx{wrong_testscript}@../build-wrong/wrong_testscript/wrong_testscript/
ld ../build-wrong/wrong_testscript/wrong_testscript/exe{wrong_testscript}
test wrong_testscript/testscript{testscript}@../build-wrong/wrong_testscript/wrong_testscript/ ../build-wrong/wrong_testscript/wrong_testscript/exe{wrong_testscript}
error: process b terminated abnormally: segmentation fault (SIGSEGV) (core dumped)
```

Notes
-------

`$* >>~/FIRST/ >>SECOND`

Removing the regex mode in the `FIRST` token  or not reusing the same output will not trigger the access violation:
- `$* >>FIRST >>SECOND` : test fails as expected, no segfault/access-violation.
- `$* >>FIRST >>~/SECOND/` : test fails as expected, no segfault/access-violation. 
- `$* >>~/FIRST/ 2>>SECOND` : test fails as expected, no segfault/access-violation. 
 - `$* >>~/FIRST/ >>~/SECOND/` : test fails as expected, no segfault/access-violation.

**Comment by karen-arutyunov** [comment]
Thanks for the report. 

The build2 bugfix version is staged.
