### ISSUE TITLE
Non-crossplatform test code generated with bdep new C library

### ISSUE THREAD

**Issue by Klaim** [build2/build2#54]
Context
---------

Visible only on Windows (or with msvc's library?):
```
PS G:\work\next\prototypes\libdeleteme> b --version
build2 0.12.0-a.0.6e84c0f9c5e4
libbutl 0.12.0-a.0.b80818e87a57
host x86_64-microsoft-win32-msvc14.2
Copyright (c) 2014-2019 Code Synthesis Ltd
This is free software released under the MIT license.
```

How To Reproduce
---------------------

```
bdep new libdeleteme -t lib -l c
cd .\libdeleteme\ 
b
```

Observed
----------

```
PS G:\work\next\prototypes\libdeleteme> b
version.in libdeleteme\version.h.in
c tests\basics\c{driver}
c libdeleteme\c{deleteme}
c libdeleteme\c{deleteme}
G:\work\next\prototypes\libdeleteme\tests\basics\driver.c(16): warning C4047: 'initializing': 'FILE *' differs in levels of indirection from 'int'
G:\work\next\prototypes\libdeleteme\tests\basics\driver.c(25): warning C4047: 'initializing': 'FILE *' differs in levels of indirection from 'int'
ld libdeleteme\libs{deleteme}
ar libdeleteme\liba{deleteme}
ld tests\basics\exe{driver}
driver.exe.obj : error LNK2019: unresolved external symbol fmemopen referenced in function main
tests\basics\driver.exe : fatal error LNK1120: 1 unresolved externals
info: failed to update dir{.\}
```

`fmemopen` does not seem to exist in VS documentation or headers so I suppose it should be replaced by something more cross-platform.

Workaround
--------------

Simply remove usage of `fmemopen`.

**Comment by boris-kolpackov** [comment]
Yeah, it turns out writing cross-platform C is hard ;-). We tried to write a C++ equivalent of our simple "Hello, World" library and the best we could come up with without complicating things is the use of `fmemopen()`, which is known to be non-portable:

```
char b[256];

FILE *o = fmemopen (b, sizeof (b), "w");
assert (say_hello (o, "World") > 0);
fclose (o);
assert (strcmp (b, "Hello, World!\n") == 0);
```

If anyone can propose a simple alternative, we can try to fix this.

**Comment by Klaim** [comment]
While I understand that it would not be exactly the same, could using the buffer direcly instead of the stream and `sprintf` instead of `fprintf` be sufficient? Or do you really want a stream?

For a Hello World it seems sufficient to me but maybe you have reasons I'm not seeing?

**Comment by boris-kolpackov** [comment]
This is a test that tries to exercise the library's interface which uses `FILE` as an output stream.

**Comment by Klaim** [comment]
Yes, I am suggesting to change that interface and semantic.
Example: https://github.com/Klaim/build2-new-libc

I am not seeing a specific reason why it have to be a stream (in my example it's a buffer) other than making it as close as the c++ version, so I'm asking if it wouldn't be ok to allow it not be a `FILE` stream?

**Comment by boris-kolpackov** [comment]
Yes, we would prefer to keep it `FILE` since that's a natural analog to C++'s `iostream`. I've fixed this in master by using `tmpfile()` instead of `fmemopen()` (and it happens we need a custom implementation for Windows).
