### ISSUE TITLE
Assertion failure with incorrect syntax in for-loop block

### ISSUE THREAD

**Issue by Klaim** [build2/build2#56]
Context
---------

```
PS G:\test\testcase> b --version                                                                                     build2 0.12.0-a.0.6e84c0f9c5e4
libbutl 0.12.0-a.0.b80818e87a57
host x86_64-microsoft-win32-msvc14.2
Copyright (c) 2014-2019 Code Synthesis Ltd
This is free software released under the MIT license.
```

I didn't try yet to reproduce it on other platforms.

How To Reproduce
---------------------

Add this code to any buildfile:
```
names = a b c
for n : $names
  : exe{n} # Invalid syntax
```

Observed
-----------

```
PS G:\test\testcase> b 
Assertion failed: tt == (block ? type::rcbrace : type::eos), file G:\tools\build2\build2-toolchain-0.12-a.0\build2-0.12.0-a.0.20190919144646.6e84c0f9c5e4\libbuild2\parser.cxx, line 2206
```

Workaround
--------------

Fix the wrong syntax.

Notes
-------

 - The error mention braces (`type::rcbraces`) but the assertion fails with or without braces with a for-loop block; 
 - A normal error report occurs in all variations I tried: using `if` instead of `for`, using directory scopes instead of `for`, etc.

Looks like just one specific case not caught by syntax checking.

**Comment by boris-kolpackov** [comment]
Fixed in master and will be available on the next restage. Thanks for the report!
