### ISSUE TITLE
Error when the Linux(Fedora) is in Chinese

### ISSUE THREAD

**Issue by wzh19960613** [build2/build2#60]
At the beginning my system language was set to Chinese. I tried to run 
`bdep init -C ../xxx @gcc cc config.cxx=g++ --wipe` 
in the shell, it returned
`initializing in project /home/xxx/xxx/xxx/`
`error: unable to extract C++ compiler system library search paths`

Then I changed the system language to English and the problem was solved.

And also I encountered the same error when I tried to intsall build2 with `build2-install-0.11.0.sh`.
The error command is `build2/b-boot config.cxx=g++ config.bin.lib=static build2/exe{b}`.
After that I used `dnf` to install it and it worked.

I guess maybe the output of `cpp -v` in Chinese cause this problem. Is that influential?

The output of `cpp -v /dev/null -o /dev/null` in the Chinese OS:
> 使用内建 specs。
COLLECT_GCC=cpp
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
目标：x86_64-redhat-linux
配置为：../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 9.2.1 20190827 (Red Hat 9.2.1-1) (GCC) 
COLLECT_GCC_OPTIONS='-E' '-v' '-o' '/dev/null' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/9/cc1 -E -quiet -v /dev/null -o /dev/null -mtune=generic -march=x86-64
忽略不存在的目录“/usr/lib/gcc/x86_64-redhat-linux/9/include-fixed”
忽略不存在的目录“/usr/lib/gcc/x86_64-redhat-linux/9/../../../../x86_64-redhat-linux/include”
#include "..." 搜索从这里开始：
#include <...> 搜索从这里开始：
 /usr/lib/gcc/x86_64-redhat-linux/9/include
 /usr/local/include
 /usr/include
搜索列表结束。
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/9/:/usr/libexec/gcc/x86_64-redhat-linux/9/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/9/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/9/:/usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/9/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-E' '-v' '-o' '/dev/null' '-mtune=generic' '-march=x86-64'

And the output of `cpp -v /dev/null -o /dev/null` in the English OS:
> Using built-in specs.
COLLECT_GCC=cpp
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 9.2.1 20190827 (Red Hat 9.2.1-1) (GCC) 
COLLECT_GCC_OPTIONS='-E' '-v' '-o' '/dev/null' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/9/cc1 -E -quiet -v /dev/null -o /dev/null -mtune=generic -march=x86-64
ignoring nonexistent directory "/usr/lib/gcc/x86_64-redhat-linux/9/include-fixed"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-redhat-linux/9/../../../../x86_64-redhat-linux/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-redhat-linux/9/include
 /usr/local/include
 /usr/include
End of search list.
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/9/:/usr/libexec/gcc/x86_64-redhat-linux/9/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/9/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/9/:/usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/9/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-E' '-v' '-o' '/dev/null' '-mtune=generic' '-march=x86-64'

**Comment by wzh19960613** [comment]
I found the problem here:
https://github.com/build2/build2/blob/d0842f4a05ac691dc296347ff872eb7a9b83b42d/libbuild2/cc/gcc.cxx#L205

When the system is in Chinese, this line doesn't start with `libraries: =` but `库：=`

**Comment by wzh19960613** [comment]
Patch here #61

**Comment by boris-kolpackov** [comment]
Thanks for the report, further investigation, and the patch!

Yes, this is unfortunate. Our approach up until now has been to carefully work around translation issues rather than forcing a specific locale (which has its own issues). But I am not sure how we can work around things in this case. So maybe it's time for the approach that you are suggesting.

I did a bit of research and I think a more correct way to do this would be like this:

```
LC_ALL=C gcc -print-search-dirs
```

Could you confirm that this works as expected on your machine?

**Comment by wzh19960613** [comment]
@boris-kolpackov 
I test on Fedora 30 & Ubuntu 19 and it works as expected.
And it's clearer than my patch.
Thanks for your advice.

**Comment by boris-kolpackov** [comment]
I took a closer look at the code and it appears we actually deal with the potential translation of "library". What we didn't expect, if the ": " sequence after it also being potentially translated. I've changed the code slightly to account for that: c2599b0d28270d8d1ddcc6e890fddeb41615a833

Could you try the latest [staged](https://build2.org/community.xhtml#stage) version and let us know if there are still issues?
