### ISSUE TITLE
How can I compile different executables with different compile options?

### ISSUE THREAD

**Issue by asartori86** [build2/build2#63]
Hi,
I was puzzled by how I can add a couple of compile flags just for few executables (or targets) out of many. I couldn't find the way. Thanks

**Comment by boris-kolpackov** [comment]
Hi Alberto,

Filing an issue to ask a question is not something we would like to encourage. Do you think you can send this either to the mailing list (you don't need to subscribe) or the slack channel: https://build2.org/community.xhtml#help

Also, I would suggest that you include a bit more concrete details, maybe a `buildfile` fragment that shows your layout and what you would like to build differently.

**Comment by asartori86** [comment]
thanks @boris-kolpackov, I'll write there
