### ISSUE TITLE
Assertion failure when attempting `bdep init -A` for a repo already added through `bpkg add`

### ISSUE THREAD

**Issue by Klaim** [build2/build2#65]
It's basically an assertion failure.

Context
---------

```
╰─$ b --version
build2 0.12.0-a.0.9d477ab892a7
libbutl 0.12.0-a.0.5ea81f5bc791
host x86_64-linux-gnu
```

Seems to be the same on Ubuntu and Windows.

How To reproduce
----------------

The basic idea is to:
 1. create or clone a repository of a build2 project;
 2. `bpkg add` the local directory to a configuration (a new one or not);
 3. attempt to `bdep init` the same project from the local directory into the same configuration.

(I found this one after forgetting what I did in a configuration dir, then later attempting a `bdep init` on one of the project I already initialized in that configuration dir).

```
bdep new myapp && cd myapp
git add . && git commit -m "initial state"
cd ..
bpkg create cc -d ./build-bad
bpkg add ./myapp -d build-bad
cd myapp
bdep init -A ../build-bad
```
The last line fails.

Observed
--------

The `bdep init` step results in:
```
╰─$ bdep init -A ../build-bad
initializing in project /home/klaim/tests/repro-build2-protox-3/myapp/
added configuration /home/klaim/tests/repro-build2-protox-3/build-bad/ 1 default,forwarded,auto-synchronized
bpkg: /home/klaim/tools/build2/build2-toolchain-0.12-a.0/libodb-2.5.0-b.16.20191009083228.5e6ab77ee4ef/odb/result.txx
:18: odb::result<T>::pointer_type odb::result<T>::one() [with T = bpkg::repository; odb::result<T>::pointer_type = st
d::shared_ptr<bpkg::repository>]: Assertion `++i == end ()' failed.
error: process bpkg terminated abnormally: aborted (SIGABRT)
```

The project seem to be considered added in the configuration, so doing `bdep init` can reproduce the issue at this point:

```
╰─$ bdep init
initializing in project /home/klaim/tests/repro-build2-protox-3/myapp/
bpkg: /home/klaim/tools/build2/build2-toolchain-0.12-a.0/libodb-2.5.0-b.16.20191009083228.5e6ab77ee4ef/odb/result.txx
:18: odb::result<T>::pointer_type odb::result<T>::one() [with T = bpkg::repository; odb::result<T>::pointer_type = st
d::shared_ptr<bpkg::repository>]: Assertion `++i == end ()' failed.
error: process bpkg terminated abnormally: aborted (SIGABRT)
```

With `--verbose 4`: https://pastebin.com/q3Cia4Qk

It results in a similar error on Windows.
```
$ bdep init -A ../build-bad
initializing in project C:\Users\jlamotte\tests\repro-bug-build2-protox-3\myapp\
added configuration C:\Users\jlamotte\tests\repro-bug-build2-protox-3\build-bad\ 1 default,forwarded,auto-synchronized
Assertion failed: ++i == end (), file G:\tools\build2\build2-toolchain-0.12-a.0\libodb-2.5.0-b.16.20191009083228.5e6ab77ee4ef\odb/result.txx, line 18
error: process bpkg terminated abnormally: aborted
```

Expected
----------

Either:
 - no error, or 
 - a report that the project is already initialized there.

For example, the semantically similar following commands: `
```
bdep new myapp && cd myapp
bdep init -C ../build-bad cc
bdep init -A ../build-bad
```
will result in a clear error:
```
$ bdep init -A ../build-bad
initializing in project /home/klaim/tests/repro-build2-protox-3/myapp/
error: configuration with directory /home/klaim/tests/repro-build2-protox-3/build-bad/ already exists in project /home/klaim/tests/repro-build2-protox-3/myapp/
```

It looks like the main difference is the `bpkg add` step. However when attempting to start with this previous script and then doing `bpkg add . -d ../build-bad` , I didn't manage to reproduce the initial problem.

**Comment by karen-arutyunov** [comment]
Thanks for the report! The fix is staged.
