### ISSUE TITLE
Paths

### ISSUE THREAD

**Issue by optomux** [build2/build2#7]
How are compiler paths discovered? Is it possible to set this through b.exe?

**Comment by boris-kolpackov** [comment]
For the C++ compiler this is done via the `config.cxx` configuration variable:

```
b config.cxx=g++-8
```

Please also note that this is a question rather than an issue for which you should use either the mailing list or the slack channel. See https://lists.build2.org for details on both options.

**Comment by optomux** [comment]
This can cause conflicts. Why can't we set paths ourselves?

**Comment by boris-kolpackov** [comment]
This allows you to set the compiler name/path yourself. Or are you talking about some other paths? See also a note on providing more context in another issue.

**Comment by optomux** [comment]
Oh I see. This works now.
"b config.cxx=C:\msys64\mingw64\bin\g++.exe"

I was just worried that by having 4 compilers installed it could cause some conflicts.
If you are building with MSVC it may use GCC libraries etc.
