### ISSUE TITLE
[Windows] `bpkg fetch <github-repo-url>` fails to fetch (git error)

### ISSUE THREAD

**Issue by Klaim** [build2/build2#72]
Context
---------

This issue appears with 
```
$ b --version
build2 0.13.0-a.0.8fbc673998ed
libbutl 0.13.0-a.0.6b482c6d405f
host x86_64-microsoft-win32-msvc14.2
[...]
$ git --version
git version 2.20.1.windows.1
```

It does not appear with build2 `v0.12.0`. It does not seem to appear on this linux setup either:
```
$ b --version
build2 0.13.0-a.0.8fbc673998ed
libbutl 0.13.0-a.0.6b482c6d405f
host x86_64-linux-gnu
[...]
$ git --version
git version 2.17.1
```

Therefore I suspect this issue to only appear on the current stage version (`0.13.0-`) and only on Windows. I used git-bash on windows provided with git, but it does not seem to be related (not sure though).
See Notes for more information.

To switch between versions I installed both versions of build2 in different directories and used a symbolic link to switch from one to the other (though on windows you have to delete the link which appear like a normal directory, and then recreate a link).

How To Reproduce
---------------------

```
bpkg create cc -d ./build-msvc
bpkg build "https://github.com/Klaim/lua-build2.git#weird2" -d ./build-msvc/
```

See Notes for variations.

Observed
----------

```
klaim@KLAIMDEV MINGW64 /c/temp
$ bpkg create cc -d ./build-msvc                                                                                                      created new configuration in C:\temp\build-msvc\

klaim@KLAIMDEV MINGW64 /c/temp
$ bpkg build "https://github.com/Klaim/lua-build2.git#weird2" -d ./build-msvc/                                                        added git:github.com/Klaim/lua-build2#weird2
fetching git:github.com/Klaim/lua-build2#weird2
querying https://github.com/Klaim/lua-build2.git
fetching from https://github.com/Klaim/lua-build2.git
remote: Enumerating objects: 96, done.
remote: Counting objects: 100% (96/96), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 96 (delta 0), reused 91 (delta 0), pack-reused 0
Unpacking objects: 100% (96/96), done.
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=<n>
    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
    --count
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
error: https://github.com/Klaim/lua-build2.git did not send all necessary objects

error: unable to fetch .\build-msvc\.bpkg\tmp\832365e850c4\
  info: re-run with -v for more information
```

With `--verbose 4` : https://pastebin.com/d9wyDGR6

Notes & Analysis
-------------------

 - It looks like the issue might be related to github.com's behaviour, though I couldn't confirm that  at the moment.
 - I also tried with `"https://github.com/build2-packaging/plf-colony.git"` and `"https://github.com/build2-packaging/sqlite.git"` and obtained the same error so it is not a repo-specific issue.
 - Cloning manually then building (using `bdep init` then `b`) works as expected for these repositories.
 - Doing `bpkg add <repo-url>` then `bpkg fetch` triggers the same issue. Basically I couldn't find a way to fetch automatically that didn't fail. The main workaround is to clone the repository locally and use that.
 - I tested on 2 different Windows computers (with the same versions of build2) to help figure out what was the issue. The issue appears on both. However, it was tested with both in the same place and the linux is in another place. So if the issue is related to networking, I will only be able to confirm on a 3rd windows machine in a separate location tomorrow.

**Comment by karen-arutyunov** [comment]
Thanks for the report.

The build2 toolchain bugfix version is staged.
