### ISSUE TITLE
Install operation gives different results depending on how the package was acquired (and one of these is incorrect).

### ISSUE THREAD

**Issue by Klaim** [build2/build2#73]
(the title isn't perfect but it's getting late, feel free to change it to something more useful/appropriate)

The core idea of this issue is that `install` operation does not seem to be the same depending on if we are building from a local cloned source directory or from a remote (github) repository - and one of these is wrong (the from-remote-repo one apparently).

The repository in question is `https://github.com/klaim/lua-build2.git`. The issue was revealed through the CI, the `test-install` failing everywhere except on my working computer (see below for the CI logs).

Context
---------

This issue appears at least on Linux but I suspect it to be general:
```
$ b --version
build2 0.13.0-a.0.8fbc673998ed
libbutl 0.13.0-a.0.6b482c6d405f
host x86_64-linux-gnu
```

I believe I saw that issue with `v0.12.0` and before but can't 100% confirm that at the moment.
I couldn't confirm this issue on Windows because of #71 but now that it's fixed I still can't confirm because of #72 .

In particular, I have CI reports suggesting that the issue seems general, but I don't know why they manage to not hit #72 on windows: https://ci.stage.build2.org/@c1536138-30d0-4dbd-9882-e72c7426dbb5 I'm also not 100% sure all these errors are the same, see below.

I didn't try with another repository as I don't know what's the condition in the buildfiles to trigger this issue. I still suspect that something in the buildfile might be wrong. See notes below.
Just note that I think I hit that issue before with some other packaging attempts but it was hidden in a forest of issues (most of them because my buildfile was faulty).

How To Reproduce
---------------------

Note the output of the lines marked `#1` and `#2`
```
bpkg create -d build-local cc config.install.root=./install-local
bpkg create -d build-from-github cc config.install.root=./install-from-github
git clone https://github.com/Klaim/lua-build2.git
cd lua-build2
bdep init -A ../build-local
git checkout weird2
b install
ls ../install-local/include #1
cd ../build-from-github/
bpkg build "https://github.com/Klaim/lua-build2.git#weird2"
bpkg install lua
ls ../install-from-github/include #2
```

The branch `weird2` here is only used to make sure we are checking the same exact commit (I will not move this branch until this issue is fixed).

Observed
----------

Line `#1` displays:
```
╰─$ ls ../install-local/include #1
lauxlib.h  luaconf.h  lua.h  lua.hpp  lualib.h
```

Line `#2` displays:
```
╰─$ ls ../install-from-github/include #2
lauxlib.h  luaconf.h  lua.h  lualib.h
``` 

Here is the complete log on my linux machine: https://pastebin.com/paZftppu

Here is the output of `bpkg install lua --verbose 4`: https://pastebin.com/EU7FwJbY

Expected
----------

 - Both output of lines marked `#1` and `#2` should be exactly the same (same headers installed).
 - Assuming the buildfile is correct, the output should show that `lua.hpp` is installed (as for the local clone version).

Notes & Analysis
-------------------

 - We can read `install lua-5.3.5-a.0.20191124162136.4e7e7c95dc79/src/hxx{lua}` in the output of the second `bpkg install lua`, which **implies that the operation to install `lua.hpp` should have succeeded** (there is no error or warning following that line). However...
 - When trying the same `bpkg install lua` with either `-v` or `-V` or `--verbose 4` (as linked before), **we see no mention of `hxx{lua}` or `lua.hpp`**. I would expect it to appear even if the operation fails somehow.
 - Repeating the install does not fix the issue, so the problem is systematic (not like #71 )
 - In the CI logs that lead me to this issue, we can see that the file missing is either `lua.h` or `lua.hpp`. At first glance, on Windows it's `lua.h` that's missing while on other platforms it's `lua.hpp`. Note that #72 might be interracting with the issue on Windows. It does prevent me to check it locally for example.

**Comment by karen-arutyunov** [comment]
Adding the ```print src/{h hxx}{$lua_public_headers}``` into the buildfile you can see that ```src/{h hxx}{$lua_public_headers}``` expands into the following list of names: 
```
src/h{lua.h} src/h{luaconf.h} src/h{lualib.h} src/h{lauxlib.h} src/h{lua.hpp} 
src/hxx{lua.h} src/hxx{luaconf.h} src/hxx{lualib.h} src/hxx{lauxlib.h} src/hxx{lua.hpp}
```
When iterating over this list and assigning the target-specific install variable, build2 also adjusts target file extensions (making it .h for hxx target, etc) which doesn't seems to be desired. Normally you don't use the target type and extension simultaneously, unless you need to overwrite the extension implied by the type.

The right way to handle the header installation in your buildfile would be something like:
```
include_dir = include/
lua_public_headers = lua luaconf lualib lauxlib

h{*}: install = false

for public_header : src/h{$lua_public_headers}
  $public_header@./src/ : install = $include_dir
```
Feel free to reopen the issue if it still reproduces after the buildfile fix.

**Comment by Klaim** [comment]
Thanks! 
I agree with your analysis, though the issue that led me here is that while the libraries and executable of Lua are made of C files, it provides both `lua.h` and `lua.hpp` which are part of the main library interface (as per the library document and the makefile).

So I need to have both `lua.h` and `lua.hpp` installed, and the current buildfile is one attempt to do that (I also managed to make it work in some other ways in the previous commits, maybe it worked better - it was more specific at least).

So I suspect I should modify your suggestion to:

```
lua_public_headers = lua luaconf lualib lauxlib lua.hpp
```
? 
`lua.hpp` is never used in compiling this project, it should only be provided to (C++) users, so I don't really care if build2 takes it as a C header file.

OR maybe just add `hxx{lua}` explicitely 
```
for public_header : src/h{$lua_public_headers}
  $public_header@./src/ : install = $include_dir
hxx{lua}@./src/ : install = $include_dir
```



Anyway I will try that when I reach home, thanks for your time.

One thing that still worry me is that even if I fix that, it still means that I need to check (at least) 2 different ways to install the project to make sure all the install scenario works.

**Comment by karen-arutyunov** [comment]
Adding lua.hpp to lua_public_headers doesn't seems as a good idea since it may end up badly for h{lua} target due to its extension overwrite.

But actually I don't see a problem with the fix I suggested. Note that lua.hpp is still installed since installation of hxx targets is not disabled with ```h{*}: install = false``` (being enabled by default).

If later you will get some non-public hpp headers, then you can convert to something like:
```
include_dir = include/
lua_public_h = lua luaconf lualib lauxlib
lua_public_hxx = lua

{h hxx}{*}: install = false

for public_header : src/h{$lua_public_h} src/hxx{$lua_public_hxx}
  $public_header@./src/ : install = $include_dir
```

**Comment by Klaim** [comment]
> But actually I don't see a problem with the fix I suggested. Note that lua.hpp is still installed since installation of hxx targets is not disabled with h{*}: install = false (being enabled by default).

True! That should work then, I'll confirm soon.

**Comment by Klaim** [comment]
The change in the buildfile seems to have fixed the issue. (I kept an explicit version to not forget about `lua.hpp`).
