### ISSUE TITLE
[feature request] header extraction phase need to print compiler error for IDE error parser

### ISSUE THREAD

**Issue by reset199** [build2/build2#77]
I run build from my IDE and I see log and can jump to error line in case this is compiler error, but if this is error on headers extraction phase I can't do the same.

When build2 traces which headers included by `.cpp` files and do not find header it prints just 
`error: no rule to update /home/san/code/hello_build2/libcornet/libcornet-clang/libcornet/libcornet/tls/hxx{record_layer.hpp}` but do not print which `.cpp` file initiated this error. I want to see this error in format produced by compiler because almost every IDE cat parse compiler output log and go to error file and line on click to error line in build log.

**Comment by boris-kolpackov** [comment]
Hm, I don't think showing the translation unit (`.cpp`) that causes this will solve the problem entirely since the header may be included indirectly through a chain of other headers. I think it would be better to let the compiler itself issue this diagnostics which would normally include the information about any intermediate headers. Let me see what can be done here.

**Comment by reset199** [comment]
I think if You do not make header extraction phase and just run compiler on `.cpp` file it will produce error pointing to that `.cpp` file and intermediate headers. This error will show .cpp file and headers chain. This is what required (exact compiler error with `.cpp` and intermediate headers).

I think this is easy to implement and probably similar compiler exec is happen in header extraction phase. I think that compiler error will solve this task.

**Comment by boris-kolpackov** [comment]
Ok, I've implemented deferring the failure until the compiler diagnostics is issued. If you could try it using the [staged toolchain](https://build2.org/community.xhtml#stage) and confirm it works as expected for you, that would be great.

**Comment by reset199** [comment]
Thank You for quick update. Staged version works almost exactly I asked. Except `-s` mode. With `--serial-stop|-s` `b` stops as earlier without error message. I use this mode when I do not want to flood log by error messages (got error - fix it, do not wait for build finished).

Anyway, I will close this ticket.

**Comment by boris-kolpackov** [comment]
I was on the fence about `-s` but now with your feedback and some more thinking I believe it is correct to allow deferment in this mode. The change is staged.
