### ISSUE TITLE
Project-specific configuration

### ISSUE THREAD

**Issue by asartori86** [build2/build2#79]
Hi,
It is not clear to me how to customize the build of, say, a library. For example, with `CMake` or `Meson`, I can type `-DMPI=true` to build the library with mpi. If I don't specify the flag, the library/executable is built without mpi. Or I want to use `mkl` over `openblas` and so forth.

What is the `build2`nic way of doing it?

Thanks

**Comment by boris-kolpackov** [comment]
The `build2` way is (or more precisely, will be) to use the `config.<proj>.*` *configuration variables* (say, `config.libhello.mpi=true|false` or `config.libhello.math=mkl|openblass`). This is the same mechanism as what's used for build system modules configuration (say, `config.cxx.coptions`) as well as the import machinery (those `config.import.<proj>.*` variables).

Configuration variables are pretty much like ordinary `buildfile` variables with the major difference being that they are persisted (by the `config` module) in the `config.build` file. While this persistence support is already available to the build system modules, it is not yet exposed in `buildfiles`.

That's the bad news. The good news is that this feature is on our [roadmap](https://github.com/build2/README/blob/master/roadmap.md) and, in fact, I am working on it right now. So if you would like to try it out before the next release and provide feedback, that would be great. I will ping this issue when we have something available to try.

**Comment by asartori86** [comment]
@boris-kolpackov I look forward to trying this out as soon as you have something available. Thanks

**Comment by boris-kolpackov** [comment]
Ok, this functionality is in the latest [staged toolchain](https://build2.org/community.xhtml#stage) and while I am still working on the documentation, you can start playing with it if you like. Feedback on real-world usage is much appreciated.

In a nutshell, you can now put the following directives into your `root.build` file (continuing with your example):

```
config [bool] config.libhello.mpi ?= false
config [string] config.libhello.math ?= 'openblass'
```

With this you get persistence and the default value semantics. Then, in your `root.build` or other `buildfiles` you can do something along these lines:

```
if $config.libhello.mpi
  cxx.options += -DWITH_MPI

switch $config.libhello.math
{
  case 'mkl'
    cxx.options += -DWITH_MKL

  case 'openblass'
    cxx.options += -DWITH_OPENBLASS

  default
    fail "unknown math configuration value '$config.libhello.math'"
}
```

You could also use the `in` module to generate `config.h` from `config.h.in` taking into account these configuration values.

If you run the build with `-v`/`-V`, you will also now automatically get the project configuration report (similar to the build system module reports) along these lines:

```
config libhello@/tmp/libhello/
  mpi      true
  math    mkl
```

For more advanced features, in the meantime, you can use [tests](https://github.com/build2/build2/blob/master/tests/directive/config.testscript) as a reference.

**Comment by boris-kolpackov** [comment]
This is done: https://build2.org/release/0.13.0.xhtml#proj-config
