### ISSUE TITLE
use config.cxx to specify??

### ISSUE THREAD

**Issue by optomux** [build2/build2#8]
Why am I getting this error?
"error: not built with default C++ compiler
  info: use config.cxx to specify"

> C:\Hello>dir
>  Volume in drive C has no label.
>  Volume Serial Number is EA14-76E4
> 
>  Directory of C:\Hello
> 
> 17.11.2018  12:50    <DIR>          .
> 17.11.2018  12:50    <DIR>          ..
> 15.11.2018  23:14         4.177.920 b-boot.exe
> 15.11.2018  23:18         3.791.360 b.exe
> 16.11.2018  21:33               255 bla.cxx
> 16.11.2018  20:16                39 buildfile
> 17.11.2018  12:50               128 config.build
> 16.11.2018  22:08               345 hello.cxx
> 17.11.2018  12:44           570.594 hello.exe
>                7 File(s)      8.540.641 bytes
>                2 Dir(s)  23.158.472.704 bytes free

**Comment by boris-kolpackov** [comment]
What is the command line that gives you this error? Also, how did you obtain that `b.exe` in your listing?

**Comment by optomux** [comment]
just running b.exe in the folder. 

b.exe config.cxx=cl works however.

**Comment by boris-kolpackov** [comment]
`b.exe` should default to the compiler you built it with (presumable `cl.exe`). How did you build `b-boot.exe` and `b.exe`?

**Comment by optomux** [comment]
Through build-msvc.bat. But why can't it find the config.build file???

**Comment by optomux** [comment]
I am affraid the solution is FastBuild.

**Comment by boris-kolpackov** [comment]
I will take a look at why the result of `build-msvc.bat` does not default to cl.exe. As for your second question, I have no idea what "it" is. 

Also, on a more general note, all your issues and questions have virtually zero context (i.e., what you are trying to do, what your project setup is, what diagnostics you are getting, etc). It is very tiresome to try to pull this information out of you one drop at a time.

**Comment by optomux** [comment]
I meant why doesn't (b.exe) discover config.build file in the directory? Seems trivial no?

**Comment by boris-kolpackov** [comment]
Closing for lack of detail (see my previous comment). Feel free to reopen if/when you are ready to provide a detailed description of what you are doing.

**Comment by optomux** [comment]
Will reimplement the features of build2 on fastbuild. Not to worry!
