### ISSUE TITLE
`license` short name unification in manifest

### ISSUE THREAD

**Issue by pioneer19** [build2/build2#82]
Current recommended `license` [names](https://build2.org/bpkg/doc/build2-package-manager-manual.xhtml#manifest-package-license) in `manifest` is incompatible to [spdx licenses short names](https://spdx.org/licenses/). For example Apache-2.0 license have different names in those list. Apache even allow http://www.apache.org/foundation/license-faq.html#Apply-My-Software to use in files short notice (just two lines instead of usual two paragraphs)
```
Copyright [yyyy] [name of copyright owner]
SPDX-License-Identifier: Apache-2.0
```
My suggestion - use spdx license short identifer for manifest's license field.Or better to add `SPDX-License-Identifier` field and deprecate (with some deprecation period) `license`. The aim is to use same unified license short names as in [spdx licenses](https://spdx.org/licenses/).

**Comment by boris-kolpackov** [comment]
I think it's a good idea to switch to the SPDX names: their list is more complete than ours and also it seems to be fairly widely-adopted. We can still support our small subset for backwards compatibility if necessary. One thing we should remember to update (besides the manifests themselves) is the license detection code in `bdep-new`.

**Comment by boris-kolpackov** [comment]
This is done: https://build2.org/release/0.13.0.xhtml#spdx

Please reopen if you think there are any remaining issues.
