### ISSUE TITLE
[testscript] Assert violation with incorrect syntax (involving multiple commands)

### ISSUE THREAD

**Issue by Klaim** [build2/build2#83]
Context
---------

```
$ b --version
build2 0.13.0-a.0.3d08bfb688cf
libbutl 0.13.0-a.0.0598a6d315ec
host x86_64-microsoft-win32-msvc14.2
```

Didn't try yet with other versions or plateforms.

How To Reproduce
---------------------

1. `bdep new myapp`
2. Edit `myapp/myapp/testscript` to:
```

: basics
:
{
    ln -s $0 $~/ok ;
    end;
    $* 'World' >'Hello, World!'
}
```

Notice the `end;` which is an error (I removed an `if` and forgot to remove the associated `end`, and the `;`).

3. `b test`

Observed
-----------

```
$ b test
c++ myapp\cxx{myapp}
ld myapp\exe{myapp}
test myapp\testscript{testscript} myapp\exe{myapp}
Assertion failed: false, file E:\tools\build2\build2-toolchain-0.13-a.0\build2-0.13.0-a.0.20200331141248.3d08bfb688cf\libbuild2\test\script\parser.cxx, line 3325
```

Expected
----------

Usually, having a `end` in the middle of nowhere will generate an error stating that.

Notes
-------

It's very late so I didn't try variants of the reproduction yet, it's the simplest I could get for now.

**Comment by boris-kolpackov** [comment]
Thanks, will look into it before the next release.

**Comment by karen-arutyunov** [comment]
The fix is staged.
