### ISSUE TITLE
[MSVC] Assertion failure when attempting `#import` with an existing header

### ISSUE THREAD

**Issue by Klaim** [build2/build2#88]
Context
---------

On Windows 10, with msvc preview `14.27.28919`  (cl `19.27.28919.3`) 
```
$ b --version
build2 0.13.0-a.0.57a8dbd7fe63
libbutl 0.13.0-a.0.af85a3694788
host x86_64-microsoft-win32-msvc14.2
Copyright (c) 2014-2020 the build2 authors.
This is free software released under the MIT license.
```

I didn't try yet with stable msvc.

How To Reproduce
---------------------

Basic `buildfile`:
```
using cxx

./ : exe{test} : cxx{main}
```

`main.cxx`:
```
#import <vector> // or any other header that exist
```

Observed
----------

```
$ b
Assertion failed: !good_error, file E:\tools\build2\build2-toolchain-0.13-a.0\build2-0.13.0-a.0.20200624074752.57a8dbd7fe63\libbuild2\cc\compile-rule.cxx, line 3822
```

Expected
----------

Either is fine to me:
 - This feature working: https://docs.microsoft.com/en-us/cpp/preprocessor/hash-import-directive-cpp?view=vs-2019
 - An error stating that `#import` is not supported (at least when using msvc or clang-cl?).

Notes
------

- I found this assertion failure by mistake, I did not intend to use `#import`, I am not requesting `build2` to support `#import`;
- We obtain a normal error of header not found if the name doesnt exist (for example `#import <dontexist>` will report an error instead of an assertion failure).
- When I found this issue, I was using modules, so I had the necessary flags and variables set, but the issue is independant from the C++ version or other flags related to modules.

**Comment by boris-kolpackov** [comment]
Thanks for the report. Should be fixed in the latest staged version of the toolchain.
