### ISSUE TITLE
cli generates incorrect man file (build2-toolchain-0.8.0.tar.xz contains wrong man files)

### ISSUE THREAD

**Issue by masterspline** [build2/build2#9]
Failed send this in cli-users, so posting here.

I am not sure this is bug in cli, but some generated man files in build2-toolchain-0.8.0.tar.xz is incorrect.
To reproduce

1. download build2-toolchain from https://download.build2.org/0.8.0/build2-toolchain-0.8.0.tar.xz
2. extract it and cd to build2-toolchain-0.8.0/bpkg/doc
3. run command
LC_ALL=en_US.UTF-8 MANROFFSEQ='' MANWIDTH=80 man --warnings -E UTF-8 -l -Tutf8 ./bpkg-pkg-build.1 > /dev/null

You will get error (not warning actually, but error because it leads to incorrect text rendering)
warning: macro `*'.' not defined
Similar error exist for bpkg-pkg-status.1

My opinion is that this warnings is due to '\fB*\fR' combination in this man files. Single quotes (') there must be escaped with slashes (\'\fB*\fR\'). Currently '*' in rendered text will not be displayed ('\fB*\fR' will be rendered blank). Just run

man ./bpkg-pkg-build.1
and find "Such a version is displayed as" with nothing after it (but there must be "'*'.").
I think this two files (bpkg-pkg-build.1 and bpkg-pkg-status.1) was generated by cli so I sent this message here. Changing '\fB*\fR' to \'\fB*\fR\' fix error in man pages (but this files was generated).

Quote from https://manpages.debian.org/stretch/groff/groff_mdoc.7.en.html

> Troff is limited as a macro language, and has difficulty when presented with a string containing a member of the mathematical, logical or quotation set:
> 
> {+,-,/,*,%,<,>,<=,>=,=,==,&,`,',"}
> 
> The problem is that troff may assume it is supposed to actually perform the operation or evaluation suggested by the characters. To prevent the accidental evaluation of these characters, escape them with ‘\&’. Typical syntax is shown in the first content macro displayed below, ‘.Ad’.

**Comment by boris-kolpackov** [comment]
Thanks for the detailed report and analysis! I will take a look at it in more detail on the fresh head (you do need a fresh head for groff). Regarding cli-users, I just checked and you email got caught by the spam filter. I will let it through shortly, sorry about that.

**Comment by boris-kolpackov** [comment]
Fixed in `cli`:

https://scm.codesynthesis.com/cgit/cli/cli/commit/?id=49e1a3e6c7b756763e6a7d2f1ea33d23a5c9da04

The affected pages will be updated with the upcoming release. Thanks again for the report and let me know if there are any other issues.
