### ISSUE TITLE
build2 stage install script uninstall will trigger a build

### ISSUE THREAD

**Issue by Klaim** [build2/build2#92]
To be specific, I remember there was a similar issue in the past but I also remember that you fixed it and I didn't have this issue for 0.12.0 on any of my computers.

```
╰─$ b --version
build2 0.13.0-a.0.fc4bea587f91
libbutl 0.13.0-a.0.205c54bf10f4
host x86_64-linux-gnu     
```

On my 2 windows and 1 linux I installed this specific stage version by:
 a) downloading the script and replacing my previous copy of it (.bat msvc for windows, .sh on linux)
 b) running install-script --uninstall
 c) running install-script --yes --trust yes (with a specific install directory in windows, because I install a stable and stage version separately)

On Windows b) will just remove the appropriate directories and that's it.

On Linux, I skipped a) and directly tried b) with the stage script I already had installed which was for build2 from 2/3 weeks ago I think? I don't have the specific version. It started to build so I stopped it on the way and downloaded the last stage version after deleting the previous, following the script from a). At b) it still attempted to build so I let it finish that and it did preform the uninstall at the end.

Here is the log of that last uninstall that built: https://pastebin.com/XESAstA8

**Comment by boris-kolpackov** [comment]
Normally the expected sequence of steps is:

1. uninstall using the old script (i.e., the same as what was used to install the old version)
2. download the new script
3. install using the new script

I just tried to do the following using the latest staged version:

```
sh ./build2-install-0.13.0-a.0-stage.sh --yes --trust yes /tmp/install
export "PATH=/tmp/install/bin:$PATH"
sh ./build2-install-0.13.0-a.0-stage.sh --uninstall
```

And for me uninstall did not trigger a rebuild. Could you try this on your machine to see if it makes any difference?

**Comment by Klaim** [comment]
Yes.

I first tried with same machine, same build2 install script (`build2 0.13.0-a.0.fc4bea587f91`), the exact lines you provided, except with `--no-check` for the first line to not have to change the script version.

I still got a build at uninstall. Here is the complete log (uninstall starts at line 3146): https://pastebin.com/qhzUPmFH

Then I tried with the latest stage
```
$ b --version
build2 0.13.0-a.0.ca6aef882b30
libbutl 0.13.0-a.0.b2a83ba28ef6
host x86_64-linux-gnu
```

The uninstall was immediate, no build. Here is the complete log (uninstall starts at line 2975): https://pastebin.com/24tTx1rs

Did the script change between these versions?

**Comment by boris-kolpackov** [comment]
I am not sure what's going on here. When you are using the old script to install, you still get the new packages from the repository so your "old" build was kind of half old/half new.

Another thing to keep in mind is that your system-installed packages (like your C++ compiler, standard library, etc) could be upgraded between the time you have installed `build2` and when you are uninstalling it. This will also trigger a rebuild on uninstall (which, I agree, could be surprising).

**Comment by Klaim** [comment]
I remember doing a system packages upgrade just before trying the first uninstall that triggered the build, so that would explain it.

**Comment by Klaim** [comment]
I think we can close this one, I didn't reproduce the issue on other linux machines with more recent stage scripts, even when I upgraded the system.
