### ISSUE TITLE
Assertion failure when specifying an lib import path in cli with incorrect Windows path

### ISSUE THREAD

**Issue by Klaim** [build2/build2#93]
Context
---------

```
$ b --version
build2 0.13.0
libbutl 0.13.0
host x86_64-microsoft-win32-msvc14.2
```

I suspect the issue to be only visible on Windows because it seems related to Windows paths.
But I didn't have time to try on linux.

How To Reproduce
---------------------

1. `bdep new importfail && cd importfail`
2. Uncomment dependence on libhello in `manifest`
3. Uncomment import of `libhello@lib{hello}` in `importfail/buildfile`

We do NOT modify the `repositories.manifest` to make the package available, on purpose: the issue is related to the manual import mechanism.

Observed
----------

```
$ b
error: unable to import target libhello%lib{hello}
  info: use config.import.libhello configuration variable to specify its project out_root
  info: or use config.import.libhello.hello.lib configuration variable to specify its path
  info: while applying rule cxx.link to update importfail\exe{importfail}
  info: while applying rule alias to update dir{importfail\}
  info: while applying rule alias to update dir{.\}
info: failed to update dir{.\}
```

This is expected: the library is not found, so we decide to specify a specific lib file local to the machine, but doing so we make a mistake in the path, specifying a directory instead of a file:

```
$ b "config.import.libhello.hello.lib='X:\some\directory\path\that\might\not\exist'"
Assertion failed: !k.ext, file E:\tools\build2\build2-toolchain-0.13\build2-0.13.0\libbuild2\target.cxx, line 550
```

Expected
----------

If I tried to use the same path but with `/` instead of `\` 
```
$ b "config.import.libhello.hello.lib='X:/some/directory/path/that/might/not/exist'"
error: no rule to update X:\some\directory\path\that\might\not\lib{exist}
  info: re-run with --verbose=4 for more information
  info: while applying rule cxx.link to update importfail\exe{importfail}
  info: while applying rule alias to update dir{importfail\}
  info: while applying rule alias to update dir{.\}
info: failed to update dir{.\}
```

which is what I would expect (although the error would be better if it was saying that the file does not exist or the path refers to something that is not a file or etc.).

Notes
------ 

This assert **does not fail if**: 
 - I use `/` instead of `\` in the path (see in expected section)
 - the path is a file that exists: `C:\Users\klaim\temp\importfail\manifest` (here we correctly get another error)

**Comment by boris-kolpackov** [comment]
This should be fixed in the latest staged toolchain.

**Comment by Klaim** [comment]
I can confirm the issue is fixed (we get the expected error message) in
```
$ b --version
build2 0.14.0-a.0.714142573cf1
libbutl 0.14.0-a.0.ab080add2681
host x86_64-microsoft-win32-msvc14.2
```
